### ISSUE TITLE
add to conda-forge

### ISSUE THREAD

**Issue by matanster** [more-itertools/more-itertools#275]
any plans to package this for conda-forge?
is the API already frozen / stable enough for that?

**Comment by bbayles** [comment]
Re: plans, I didn't have any; I don't use Conda. I'm not opposed to someone packaging this for distribution.

Re: API, I'm not sure what the criteria are. See [here](https://github.com/erikrose/more-itertools/blob/master/docs/versions.rst) for changes.

**Comment by matanster** [comment]
Thanks for responding much appreciated! I think `conda install` is currently a little broken (performance issues that aren't entirely predictable) so I would put this on the back-burner for a while. Thanks for this library! and looking forward to using it without conda in the near future.

**Comment by bbayles** [comment]
Good news - somebody is doing this now:
https://github.com/conda-forge/more-itertools-feedstock
