### ISSUE TITLE
New function indicating whether the current element is first or last

### ISSUE THREAD

**Issue by arturbalabanov** [more-itertools/more-itertools#351]
Quite often when iterating over an iterable, I need to know whether the current element is the first one or I've reached the last element. The check for the first element can be performed using `enumerate`, however the check for the last one is not so trivial.

If we're working with a list (or any other iterable with with a known and finite length), this can be achieved by using the `len` function, which, albeit on the uglier side, works fine:

```python
values = [1, 2, 3]
for idx, value in enumerate(values):
    is_first = idx == 0
    is_last = idx == len(values) - 1
```

However, the same method cannot be used for iterables which don't define `__len__` and the approach that needs to be used then requires more setup and being extra careful with how the iterator is used. This results in harder to read code (due to a large amount of lower-level logic) and, depending on how often this pattern is used, code repetition.

So, my proposal is to add a new function to this package, which returns each element of the iterable along with two booleans indicating whether it's the first and last element. Here's an example implementation (I assume some improvements need to be done to make it work with all data structures and/or some edge cases I haven't thought of yet):

```python
def first_last_iter(iterable):
    """
    Iterate over an interable returning each element along with whether that
    element is first or last in the sequence.

    Example:

    >>> for is_first, is_last, value in first_last_iter([1, 2, 3]):
    ...     print(is_first, is_last, value)
    ...
    True False 1
    False False 2
    False True 3
    """

    iterable = iter(iterable)
    following = next(iterable)

    is_first = True
    while True:
        value = following

        try:
            following = next(iterable)
            yield is_first, False, value
        except StopIteration:
            yield is_first, True, value
            raise

        is_first = False
```

The main drawback of this implementation is that when iterating, the next element needs to be retrieved in order to determine whether it exists in the iterable. If the iterable is an expensive generator, this may be a problem. However, my counterpoints are that:

1. I doubt that such a scenario occurs often enough
2. I don't think the problem has a big enough impact to justify this function not being used
3. Even if 1) and 2) are false for a very specific usecase, then this function can be simply not used there

That being said, any feedback for this would be more than helpful!

Personally, I find this scenario occurring often enough to justify adding a function to `more-itertools`, so I don't need to re-implement it for every project I'm working on. However, I'm still opening this issue, as opposed to directly making a PR, to gather feedback and to understand whether the problem it's solving occurs often enough in other people's projects. Of course, if people are happy with this idea, I'm ready to make the patch myself and open a PR.

**Comment by bbayles** [comment]
Many thanks for this writeup.

My first impression is that I probably wouldn't want to encourage a pattern like this:

```python
for i, item in enumerate(sequence):
    if i == 0:
        handle_first(item)
    elif i == len(sequence) - 1:
        handle_last(item)
    else:
        handle_middle(item)
```

If I were reviewing that code (with sequences), I'd ask for it to be rewritten like this:

```python
handle_first(sequence[0])
for item in sequence[1:-1]:
    handle_middle(item)
handle_last(sequence[-1])
```

We don't need to check on every iteration of the loop - so let's not!

Can we extend this method to non-sliceable iterables? We can at least do it for the first element:

```python
from more_itertools import spy
(first,), rest = spy(iterable)
handle_first(first)
for item in rest:
    handle_middle(item)
```

Maybe it would make sense to have a function that returns: an iterable over all but the last `n` items, and the last `n` items?
