### ISSUE TITLE
Link "Edit on GitHub" in documentation page is down

### ISSUE THREAD

**Issue by vezeli** [more-itertools/more-itertools#358]
I tried to go from readthedocs.io page to GitHub page and I get 404. Maybe you want to update your configuration files for docs.

Thanks for maintaining the project. I find it very useful.

**Comment by bbayles** [comment]
Thanks - it works for me on the "stable" docs, but not on "latest." Is it the same for you?

**Comment by vezeli** [comment]
Yes, it is the same. Oh, is that the default behavior maybe?

**Comment by bbayles** [comment]
@erikrose , could I trouble you to grant me Admin access on this repo? The webhook with ReadTheDocs seems to have broken, and I don't have the permissions to fix it. Send me an e-mail (username at gmail) if you need more info? Many thanks.

**Comment by bbayles** [comment]
Fixed!
