### ISSUE TITLE
Link to documentation at the top of the repository

### ISSUE THREAD

**Issue by MSeifert04** [more-itertools/more-itertools#359]
GitHub allows adding a link to the top of the repository "main page". It can be set when "edit"ing the description.

![Unbenannt](https://user-images.githubusercontent.com/14200878/71349929-6b00c980-2570-11ea-8589-8a1f360f5dcf.png)

I would find it helpful if there were a link to https://more-itertools.readthedocs.io/en/stable/ (or one of the shorter links).

**Comment by bbayles** [comment]
Great suggestion. I think I need @erikrose to change my access level to make this happen.

**Comment by bbayles** [comment]
Done!
