### ISSUE TITLE
segment function

### ISSUE THREAD

**Issue by Marco-Sulla** [more-itertools/more-itertools#361]
This segment(iterable, n=1) function splits the iterable in a list of lists. Every sublist must contain as elements slices of the iterable, and must have length n. The list must contain all the possible sublist. Example:

```python
>>> segment('12345', 3)
[['1', '23', '45'], ['12', '3', '45'], ['12', '34', '5'], ['1', '2', '345'], ['1', '234', '5'], ['123', '4', '5']]
>>> segment((x for x in range(5)), 2)
[[(0, 1), (2, 3, 4)], [(0, 1, 2), (3, 4)]]
```

Source code:
https://mail.python.org/archives/list/python-ideas@python.org/message/KYMYVYHLILBWOSQ4LSVBWON723HJKH3D/

The idea was requested here:
https://mail.python.org/archives/list/python-ideas@python.org/thread/VYDU3JF2MFFUUHU3XUCIAW3UXJGXZCKD/

Thanks to [Mark Dickinson](https://mail.python.org/archives/list/python-ideas@python.org/message/LLJJIWRGC726Y4OSGIETP3SE55PIQOYT/) for the algorithm.

**Comment by bbayles** [comment]
Good news - I think we already have a function that does this: [`partitions`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.partitions).

I would accept a PR that gave it a second argument that caused only the length-n segments to be emitted.

**Comment by Marco-Sulla** [comment]
I know about `partitions`, but they have not the same behaviors. `segment` divide the iterable in slices, if possible, and returns the slices. `partitions` divide the elements in sublists. Example:

```python
>>> import more_itertools as mi
````
1. It's (more or less) the same

```python
>>> iterable = (1, 2, 3)
>>> tuple(mi.partitions(iterable))
([[1, 2, 3]], [[1], [2, 3]], [[1, 2], [3]], [[1], [2], [3]])
>>> tuple(segment(iterable, 2))
([(1,), (2, 3)], [(1, 2), (3,)])
```

2. It's NOT the same

```python
>>> iterable = "abc"
>>> tuple(mi.partitions(iterable))
([['a', 'b', 'c']], [['a'], ['b', 'c']], [['a', 'b'], ['c']], [['a'], ['b'], ['c']])
>>> tuple(segment(iterable, 2))
(['a', 'bc'], ['ab', 'c'])
```

Furthermore I think a dedicated function is more fast.

PS: anyway, my previous implementation was wrong. This is the correct one:
https://mail.python.org/archives/list/python-ideas@python.org/message/KYMYVYHLILBWOSQ4LSVBWON723HJKH3D/

**Comment by bbayles** [comment]
Thanks for the clarification. I don't think the difference is big enough for a new function - but do post performance numbers if you have them?

**Comment by Marco-Sulla** [comment]
```bash
(venv) marco@buzz:~/sources/tests/more_itertools$ python3.9 -m pyperf timeit --rigorous --affinity 0 -s 'import more_itertools as mi' '[x for x in mi.partitions("Lorem ipsum dolor sit") if len(x) == 3]'
.........................................
Mean +- std dev: 2.58 sec +- 0.06 sec

(venv) marco@buzz:~/sources/tests/more_itertools$ python3.9 -m pyperf timeit --rigorous --affinity 0 -s '
import itertools as itools

def segment(it, n=1):
    if n < 1:
        raise ValueError(f"Number of segment must be > 0, {n} found")
    
    try:
        len_it = len(it)
        it[0:0]
        it_true = it
    except TypeError:
        it_true = tuple(it)
        len_it = len(it_true)
    
    if len_it < n:
        err = f"Iterable length {len_it} must be greater than number of segments {n}"
        raise ValueError(err)
    
    return (
        [it_true[i:j] for i, j in zip((0, ) + startends, startends + (len_it, ))] 
            for startends in itools.combinations(range(1, len_it), n-1)
    )

' '[x for x in segment("Lorem ipsum dolor sit", 3)]'
.........................................
Mean +- std dev: 205 us +- 3 us
```

**Comment by jferard** [comment]
I think that this is a good idea. Some thoughts on the topic.

# Functions
`more-itertools` has two functions to partition a sequence of elements: `partitions`, that is order preserving, and `set_partitions` that is not. The latter has an optional parameter to set the number of parts (or classes), while the former has not. It would be interesting to have a similar signature, and maybe to update the name of the `partitions` function (but keep it for compatibility reasons):

    def segments(iterable, k=None): # with a 's', synonym for partitions
        # order preserving

    def set_partitions(iterable, k=None):
        # not order preserving

# Segment counting
I wrote a small program to compare the number of partitions in segments when the  number of segments is fixed or not:

    >>> def segments_count(n, k=None):
    ...     if k is None: # number of elements of `partitions(range(n))`
    ...         return 2**(n-1)
    ...     else:         # segments of size k
    ...         import math
    ...         # combinations of k-1 boundaries out of n-1 positions
    ...         return math.factorial(n-1)//(math.factorial(n-k)*math.factorial(k-1))

    >>> s = "Lorem ipsum dolor sit"
    >>> L = len(s)
    >>> S = segments_count(L, 3)
    >>> S
    190
    >>> len(list(segment(s, 3))) # check
    190
    >>> B = segments_count(L)
    >>> B
    1048576
    >>> import more_itertools as mi
    >>> len(list(mi.partitions(s))) # check
    1048576
    >>> (1-S/B)*100
    99.98188018798828

That means that, in @Marco-Sulla's example, if you want to generate all 3-segments of the sequence `"Lorem ipsum dolor sit"` by filtering *all* segments (the return of `partitions`), you just **throw away more than 99.98% of the partitions**. Conclusion: a dedicated function would definitely be useful.

# Benchmark
The most intriguing:

    >>> int(B/S)
    5518
    >>> int(2.55/202e-9) # from @Marco-Sulla's timeit
    12623762

Meaning: we pick 1 partition out of 5518, but only need 1 out of 12623762 portion of time. Since the implementation is almost the same, the times should be proportional.

Here's my test:

    >>> from timeit import timeit as ti
    >>> S0 = ti(lambda: [x for x in segment("Lorem ipsum dolor sit", 3)], number=10)
    >>> S0
    0.0012054299950250424
    >>> B0 = ti(lambda: [x for x in mi.partitions("Lorem ipsum dolor sit") if len(x) == 3], number=10)
    >>> B0
    15.179263051999442
    >>> int(B0/S0)
    12592

That seems more realistic. @Marco-Sulla: can you check your benchmark?

# Implementation
The loop:

    for startends in powerset(range(1, n)):
        ...

is similar to:

    for k in range(1, n + 1):
        for startends in itools.combinations(range(1, n), k - 1):
            ...

that is

    for k in range(1, n + 1):
        yield from segments(iterable, k)
    # or itertools.chain(*(... for k in ...)) if faster

We just need to "unfold" the current implementation to get the `segments` function.

**Comment by Marco-Sulla** [comment]
> I think that this is a good idea. 

:-)

> It would be interesting to have a similar signature [from set_partitions]

Well, no problem. I prefer `n` because `k` remembers me more the factorials, but there's no problem to rename it.

> and maybe to update the name of the `partitions` function (but keep it for compatibility reasons):
> 
> ```
> def segments(iterable, k=None): # with a 's', synonym for partitions
>     # order preserving

So you're proposing to change `partitions` to `segments`, add an optional `k` parameter and return the "old" `partitions` if `k` is `None`, otherwise return the proposed `segments` output?

Beware: as I wrote before, the two functions as similar but different outputs. While `partitions` returns a list of lists, `segments` returns a list of slices. This is the same for the most of iterables, except for text sequences like `str`, `bytes` etc. Indeed, in `partitions` example a string is used, and an additional `for` loop with a `join` is used to recompose the slice.

So IMHO `partitions` and `segments` are better to be separate.

About `segment` VS `segments`, as for `k`, I prefer `segment`, but maybe it's better to follow the library convention.

About `segments` returning all the segments `if k is None`, I don't think it's a good idea. It's a completely different behavior, that maybe requires another function. And to speed up checks, it could be simply triggered if `k < 1` (that currently raises error). 

> `>>> S0 = ti(lambda: [x for x in segment("Lorem ipsum dolor sit", 3)], number=10)`

Well, I don't know why you use lambda :-)

```
>>> ti(lambda: [x for x in segment("Lorem ipsum dolor sit", 3)], number=10)
0.0022441959008574486
>>> ti('[x for x in segment("Lorem ipsum dolor sit", 3)]', globals={"segment": segment}, number=10)
0.0015578940510749817
```

Anyway, I didn't use `timeit` directly. I used `pyperf`, a tool that is used by py devs themselves to compare performance of different Python releases. And before to use it properly, it's recommended to do a system tuning:

```bash
(venv) marco@buzz:~/sources/tests/more_itertools/venv$ sudo python3.9 -m pyperf system tune
Tune the system configuration to run benchmarks

Actions
=======

Perf event: Max sample rate set to 1 per second
CPU Frequency: Minimum frequency of CPU 0-3 set to the maximum frequency
CPU scaling governor (intel_pstate): CPU scaling governor set to performance
Turbo Boost (intel_pstate): Turbo Boost disabled: '1' written into /sys/devices/system/cpu/intel_pstate/no_turbo
IRQ affinity: Stop irqbalance service
IRQ affinity: Set affinity of IRQ 122-124,126,129-131 to CPU 0-3

System state
============

CPU: use 4 logical CPUs: 0-3
Perf event: Maximum sample rate: 1 per second
ASLR: Full randomization
Linux scheduler: No CPU is isolated
CPU Frequency: 0-3=min=max=2600 MHz
CPU scaling governor (intel_pstate): performance
Turbo Boost (intel_pstate): Turbo Boost disabled
IRQ affinity: irqbalance service: inactive
IRQ affinity: Default IRQ affinity: CPU 0-3
IRQ affinity: IRQ affinity: IRQ 0-17,51,67,120-131=CPU 0-3
Power supply: the power cable is plugged

Advices
=======

Linux scheduler: Use isolcpus=<cpu list> kernel parameter to isolate CPUs
Linux scheduler: Use rcu_nocbs=<cpu list> kernel parameter (with isolcpus) to not schedule RCU on isolated CPUs
```

and I used subsequently `--affinity` option, to use every time the same, single core, because I have not isolated the cores (too much work :-D In teory, if your computer does not do something else, it's okay)

Why the results are so different? I don't know. Maybe `partitions` performs better with multicore, or `segments` performs better in single thread.

> The loop:
> 
> ```
> for startends in powerset(range(1, n)):
>     ...
> ```
> 
> is similar to:
> 
> ```
> for k in range(1, n + 1):
>     for startends in itools.combinations(range(1, n), k - 1):

Well, but `segments` does not do this. It does:

```python
[iterable[i:j] for i, j in zip((0, ) + startends, startends + (n, ))] 
            for startends in combinations(range(1, n), k-1)
```

that is, in a slower but more readable manner:

```python
res = []

all_flat_startends = combinations(range(1, n), k-1)

for flat_startends in all_flat_startends:
    slices = []
    starts = (0, ) + flat_startends
    ends = flat_startends + (n, )
    startends = zip(starts, ends)
    
    for i, j in startends:
        slice = iterable[i:j]
        slices.append(slice)
    
    res.append(slices)

return res

```

PS: for a premature optimization :-D, maybe it's better to use `from itertools import combinations`. Dots slows down the operations of some nanoseconds :-D

**Comment by bbayles** [comment]
I would still merge a PR that adds a second argument (length) to `partitions`, but I'm not up for renaming the existing function or changing its output types.

**Comment by jferard** [comment]
> While partitions returns a list of lists, segments returns a list of slices

Yes, but if you wrap the iterable in a `list` (as in `partitions`), this is the same. Are you specifically interested in string slices? (By the way, you made me notice that I may have introduced an issue in my last PR!).

> So you're proposing to change partitions to segments, add an optional k parameter and return the "old" partitions if k is None, otherwise return the proposed segments output?

Yes, that was the idea, but with a consistant output (lists of chars instead of string slices).

> but I'm not up for renaming the existing function or changing its output types. (from @bbayles)

Okay.

> About segments returning all the segments if k is None, I don't think it's a good idea. It's a completely different behavior, that maybe requires another function.

That seems consistent to me. And that's the way `set_partitions` works. Plus, the algorithm is the same (see below).

> Well, I don't know why you use lambda :-)

To not to have to write my code in a string.

> Why the results are so different? I don't know. Maybe partitions performs better with multicore, or segments performs better in single thread.

When I saw the benchmark, I thought that with something like:

    for k in range(1, n+1):
        yield from segments(iterable, k)

We could dramatically speed up `partitions`. But that's already what `partitions` makes (see below). Hence I don't see the cause of the difference.

*Here's the below...*

You have currently:

    def partitions(iterable):
        sequence = list(iterable)
        n = len(sequence)
        for i in powerset(range(1, n)):
            yield [sequence[i:j] for i, j in zip((0,) + i, i + (n,))]

    def powerset(iterable):
        s = list(iterable)
        return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))

What I'm saying is that this is *exactly* the same algorithm as segments.

First, rename one of the arguments to avoid confusions:

    def partitions(iterable):
        sequence = list(iterable)
        n = len(sequence)
        for start_end in powerset(range(1, n)):
            yield [sequence[i:j] for i, j in zip((0,) + start_end, start_end + (n,))]

Now,

    for start_end in powerset(range(1, n)):
        yield [sequence[i:j] for i, j in zip((0,) + start_end, start_end + (n,))]

Is (`len(range(1, n)) == n - 1`):

    for start_end in chain.from_iterable(combinations(range(1, n), r) for r in range(n)):
        yield [sequence[i:j] for i, j in zip((0,) + start_end, start_end + (n,))]

That is equivalent to (unfold `chain.from_iterable`):

    for r in range(n):
        for start_end in combinations(range(1, n), r):
            yield [sequence[i:j] for i, j in zip((0,) + start_end, start_end + (n,))]

And to (shift `r`):

    for r in range(1, n + 1):
        for start_end in combinations(range(1, n), r - 1):
            yield [sequence[i:j] for i, j in zip((0,) + start_end, start_end + (n,))]

And to (list comprehension and generator):

    for r in range(1, n + 1):
        yield from ([sequence[i:j] for i, j in zip((0,) + start_end, start_end + (n,))]
                    for start_end in combinations(range(1, n), r - 1))

That is (if `segments` is only the returned generator of the complete function):

    for r in range(1, n + 1):
        yield from segments(sequence, r)

You have exactly the same structure as in `set_partitions`.

**Comment by jferard** [comment]
> (By the way, you made me notice that I may have introduced an issue in my last PR!).

False alarm, because `divide` returns an iterable of iterators on slices.

**Comment by Marco-Sulla** [comment]
Well, you can change it to this:

```
from itertools import combinations
from more_itertools import powerset

def partitions(iterable, k=0):
    sequence = list(iterable)
    n = len(sequence)
    
    if k < 1:
        all_startends = powerset(range(1, n))
    else:
        all_startends = combinations(range(1, n), k-1)
    
    return (
        [sequence[i:j] for i, j in zip((0, ) + startends, startends + (n, ))] 
            for startends in all_startends
    )
```

Anyway, this forces you to rejoin strings and strings-like objects if you want the slices. Furthermore, it uses `sequence = list(iterable)`, that is slower than `sequence = tuple(iterable)`: 239 us +- 6 us vs 216 us +- 5 us. Furthermore `tuple` uses less memory.

The difference between `partitions` and `segments` it's all here:

```
    try:
        n = len(iterable)
        iterable[0:0]
        sequence = iterable
    except TypeError:
        sequence = tuple(iterable)
        n = len(sequence)
```

`segments` first tries to see if the iterable supports `len()` (ie it's not an iterator) and if it supports slicing. If yes, it uses it directly, otherwise tries to convert to a tuple.
`partitions`, on the contrary, converts any iterable to a list, so also special sequences, like `str`, that perfectly supports `len()` and slicing.

That's why IMHO `segments` is more appropriate and fast for text sequences.

But if you want to simply add a parameter to `partitions`, ok, that's no problem.

**Comment by jferard** [comment]
> Well, you can change it to this:

That's a clean version.

> sequence = list(iterable), that is slower than sequence = tuple(iterable)

You're right. I see another reason to use `tuple`: the sequence is designed to be immutable, thus we should not use a (mutable) list.

> The difference between partitions and segments it's all here:

That's funny because I used a similar trick [here](https://github.com/erikrose/more-itertools/pull/362/files) (without looking at your code). It's indeed a good idea and can avoid an expensive copy, but has an impact on the output, as you stated. @bbayles will decide if that's acceptable (I think he already gave the answer).

Note that in this case, if the copy is O(n), you are fighting against O(2^n) (`partitions`) or O((n k)) (`segments`) hence the time used for the copy should be negligible in most cases. And if the memory is an issue, then the iterable size would be too big for the generator to end in a reasonable time...

**Comment by Marco-Sulla** [comment]
> > The difference between partitions and segments it's all here:
> 
> That's funny because I used a similar trick [here](https://github.com/erikrose/more-itertools/pull/362/files) (without looking at your code). It's indeed a good idea and can avoid an expensive copy, but has an impact on the output, as you stated. @bbayles will decide if that's acceptable (I think he already gave the answer).

Yes, that's because IMHO **also** a new function is better. We can have them both, the parameter for `partitions` and a new function `segments`.
Furthermore, if you pass `segments(tuple("ABCDEF"), 3)`, you will have the same output of `partitions("ABCDEF", 3)`. But I suspect that people wants slices for strings the majority of times... it's in the example of `partitions` too! :-)

> Note that in this case, if the copy is O(n), you are fighting against O(2^n) (`partitions`) or O((n k)) (`segments`) hence the time used for the copy should be negligible in most cases

Not if k is small or very near to n :-)
