### ISSUE TITLE
Add a maxsplit, reverse parameters to split_

### ISSUE THREAD

**Issue by jferard** [more-itertools/more-itertools#381]
# maxsplit
more-itertools has various `split_` functions (`split_at`, `split_after`, `split_before`, `split_when`, `split_into`) but none of these functions has a way to stop the split after a given number of elements. Of course, we can take the first elements of a `split_...` iterator and swtich to the original iterator:

    >>> import more_itertools as mi, itertools
    >>> s = '0,1,2,3,4,5,6,7,8,9'
    >>> it1 = iter(s)
    >>> it2 = mi.split_after(it1, lambda x: x == ",")
    >>> list(itertools.islice(it2, 3)) # it *2*
    [['0', ','], ['1', ','], ['2', ',']]
    >>> list(it1) # it *1*
    ['3', ',', '4', ',', '5', ',', '6', ',', '7', ',', '8', ',', '9']

But it would be more convenient to write, as we do with [`str.split`](https://docs.python.org/3/library/stdtypes.html#str.split):

    >>> import more_itertools as mi, itertools
    >>> s = '0,1,2,3,4,5,6,7,8,9'
    >>> it2 = mi.split_after(s, lambda x: x == ",", maxsplit=3)
    >>> list(it2) # it *2*
    [['0', ','], ['1', ','], ['2', ','], ['3', ',', '4', ',', '5', ',', '6', ',', '7', ',', '8', ',', '9']]

(The last parameter could be an iterator to remain lazy).

# reverse
We could have another parameter, named `reverse` to mimic [`str.rsplit`](https://docs.python.org/3/library/stdtypes.html#str.rsplit):

    >>> it2 = mi.split_after(s, lambda x: x == ",", maxsplit=3, reverse=True)
    >>> list(it2) # it *2*
    [['0', ',', '1', ',', '2', ',', '3', ',', '4', ',', '5', ',', '6', ','], ['7', ','], ['8', ','], ['9']]

(Or create `rsplit_at`, `rsplit_after`, ... but that would be a little cumbersome)

Implementation should not be difficult.

**Comment by bbayles** [comment]
I'd entertain a PR for the `maxsplit` additions, and a separate one for `reverse`.

**Comment by jferard** [comment]
@bbayles Would you allow:
* a `keep_separator` parameter for `split_at` (useful for the implementation)
* the name `rsplit` for the parameter instead of `reverse` because `reverse` might be confusing
?

Examples (handwritten):

    >>> list(mi.split_at("a,bc,def", lambda c: c==',', keep_separator=True))
    [['a'], [','], ['bc'], [','], ['def']]

    >>> list(mi.split_at("a,bc,def", lambda c: c==',', maxsplit=1, rsplit=True))
    [['a,bc'], ['def']]
