### ISSUE TITLE
proposals on distinct_permutations

### ISSUE THREAD

**Issue by SergBobrovsky** [more-itertools/more-itertools#388]
Standard python's permutation has signature
`itertools.permutations(iterable, r=None)`
where **r** means length of permutations.
distinct_permutations has no this option. Is it drawback? Yes. A few days ago I felt it on my own.
There is a trick to bypass this: to combine distinct_combinations of length **r** with distinct_permutations, it works. So first variant is to add this combination to codebase or to replace resent realisation or distinct_permutations to thouse combine. Something like this:
`
def partial_distinct_permutations(iterable, r=None):

    return chain.from_iterable(

        map(distinct_permutations,

            distinct_combinations(iterable, r)))
`It has a disadvantages:
- non-elegant
- chaotic output instead lexicographical

Another one is to rewrite distinct_permutations on way like this:`

def distinct_permutations(iterable, r=None):

    def helper(abc, depth):

        if depth:

            depth -= 1

            a, *bc = abc

            for cb in helper(bc, depth):

                yield [a, *cb]

            for i, b in enumerate(bc):

                if a == b:

                    continue

                a, bc[i] = b, a

                for cb in helper(bc, depth):

                    yield [a, *cb]

        else:

            yield abc

    l = sorted(iterable)

    if r is None:

        r = len(l)

    return (res[:r] for res in helper(l, r - (r == (len(l))))) 
`
Lexicographical. This variant is 4+ times slowly compared with resent distinct_permutations realization (on full width, of course), but is it so important? No, I hope and I can illustrate it.

There is a third way - to rewrite second one to more complex and fast. It is unlikely that the maintainer will be interested in this )

**Comment by bbayles** [comment]
Thanks for the note.

Is your method any faster than this?

```python
from more_itertools import ilen, unique_justseen
iterable = 'mississippi'
r = 9
ilen(unique_justseen(p[:r] for p in distinct_permutations(iterable)))
```

It looks like you're building things up and then chopping them off - can we just do that the way we do already, keeping a buffer of one since we're lexicographically sorted?

**Comment by bbayles** [comment]
Ah, that doesn't work because the current function doesn't actually output in lexicographic order.

**Comment by SergBobrovsky** [comment]
> can we just do that the way we do already, keeping a buffer of one since we're lexicographically sorted?

No. 
The difference between current realization and my proposal seems like one between BFS algorithm vs DFS.
[example.py.txt](https://github.com/more-itertools/more-itertools/files/4279674/example.py.txt)


I dive into recursion, making permutation till depth **r**, and avoiding them deeper.
You (current algorithm, I mean) can't do this way: you starts from empty seed of permutations, and if you try to cut process on width **r**, you just loose tail chars.

As for speed, we must understand: typical use for distinct_permutation is bruteforce scripts. So if producing of permutation takes less time, then processing ones - it's allright.
I attach illustration of this thesis.

**Comment by bbayles** [comment]
Thanks for the explanation. I've merged in your code!
