### ISSUE TITLE
PR in the README

### ISSUE THREAD

**Issue by pylang** [more-itertools/more-itertools#389]
The other kind of PR ;)

It's not often I see writeups on `more_itertools`.  Lately, I heard about a [blog][1] on an episode of [Python Bytes][0] (double publicity).  Should we include a publicity section in the README?

I think tutorials/tours like this help guide people through a subset of the 95+ tools we have.  They can serve as "entry points" to new users to a growing library.  It's nice to have some external recommendations.

P.S. Kudos to @erikrose and @bbayles on maintaining a great library.

  [0]: https://pythonbytes.fm/episodes/show/170/visualize-this-visualizing-python-s-visualization-ecosystem
  [1]: https://martinheinz.dev/blog/16

**Comment by bbayles** [comment]
Wow, what a great blog entry. I'll definitely add a link to this.

**Comment by pylang** [comment]
Not sure where to comment this, but I noticed more-itertools suggested in the [Python 3.8.5 itertools docs](https://docs.python.org/3/library/itertools.html#itertools-recipes):

> Substantially all of these recipes and many, many others can be installed from the more-itertools project found on the Python Package Index:

    pip install more-itertools

wow

**Comment by erikrose** [comment]
Fantastic! Wow, how far we've come! Congratulations to all!

**Comment by bbayles** [comment]
Related: I recently discovered that this package is among the [top 50](https://hugovk.github.io/top-pypi-packages/) on PyPI.

**Comment by erikrose** [comment]
Cool! Probably helped by the fact that pytest (which we are just ahead of) uses us. :-)
