### ISSUE TITLE
spy: changing the result list changes the returned iterable

### ISSUE THREAD

**Issue by has2k1** [more-itertools/more-itertools#409]
Changing the result list of `spy` also alters the iterable.

```python
In [1]: from more_itertools import spy

In [2]: it = range(10)

In [3]: head, it = spy(it, 3)

In [4]: head[1] = 'bad'

In [5]: list(it)
Out[5]: [0, 'bad', 2, 3, 4, 5, 6, 7, 8, 9]
```

 I think it is a case of implementation details leaking out.

**Comment by bbayles** [comment]
> I think it is a case of implementation details leaking out.

I think you're right - would you rather see this called out in docs, or return `head.copy()` [here](https://github.com/more-itertools/more-itertools/blob/d6e773411087fa494991d7a8ad81e6a9ad5ddd56/more_itertools/more.py#L932)?

**Comment by has2k1** [comment]
As it is a simple fix, I think returning `head.copy()` is the better option.

**Comment by bbayles** [comment]
Are you up for making a PR with that change, plus a test?

**Comment by has2k1** [comment]
I'll make one.
