### ISSUE TITLE
Why isn't more-itertools built-in

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [more-itertools/more-itertools#421]
Don't take this the wrong way.  I just wonder why more-itertools is just a third-party module because it looks like quite light-weight and universal. some functions of more-itertools make my code more readable and maintainable. I think if it's a feature, not a module, it'll make python better(well, it's already pretty good though). I know that this question like a request isn't appropriate here. But I just want to know your opinions.

Sorry for my poor English, If you feel uncomfortable, I didn't mean to it. 

In brief, Why isn't more-itertools built-in? It would look pretty good to be built-in(well this is quite subjective)

**Comment by bbayles** [comment]
Thanks for writing. See https://github.com/more-itertools/more-itertools/issues/393 for a similar discussion!
