### ISSUE TITLE
Deprecate `zip_equal()`?

### ISSUE THREAD

**Issue by pylang** [more-itertools/more-itertools#438]
[PEP 618](https://www.python.org/dev/peps/pep-0618/) has been [accepted](https://mail.python.org/archives/list/python-dev@python.org/message/NLWB7FVJGMBBMCF4P3ZKUIE53JPDOWJ3/), adding `strict=False` to `zip()`.  `zip(strict=True)` will throw an exception if lengths are unequal.  

In light of this PEP, should `zip_equal()` be deprecated?  If so, it may be helpful to warn users early of a future deprecation.

**Comment by bbayles** [comment]
Surprised this made it in. I'll mark it with `DeprecationWarning` when Python 3.10 is released.
