### ISSUE TITLE
unique_when_justseen

### ISSUE THREAD

**Issue by pylang** [more-itertools/more-itertools#439]
I saw a [post](https://stackoverflow.com/q/62430679/4531270) on squashing consecutive duplicates of a particular number.  It led me to generalize a kind of `unique_justseen()` with a predicate.  The predicate let's you chose what elements you wish to be unique.

```python
def unique_when_justseen(seq, pred=None):
    """Yield unique values when a predicate is satisfied; default unique_justseen."""
    if pred is None:
        pred = lambda x: x

    for k, g in it.groupby(seq):

        if pred(k):
            yield k
        else:
            yield from g

```

*How can it be used?*

Perhaps you want to compress certain contiguous values (as seen in the post):

```python
values = [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1]
list(unique_when_justseen(values, pred=lambda x: x in (0,)))
# [0, 1, 1, 1, 0, 1, 1, 0, 1, 1]
```

Or you want to screen background noise from repeated values you care about (clustering):

```python
cpu_usage = [0, 0, 0, 0, 80, 80, 100, 100, 100, 100, 100, 100, 100, 60, 60, 20, 0, 0]
list(unique_when_justseen(cpu_usage, pred=lambda x: x < 70))
# [0, 80, 80, 100, 100, 100, 100, 100, 100, 100, 60, 20, 0]

message = "      111     111             11      1        1111       "
"".join(unique_when_justseen(message, pred=lambda x: x not in ("1",)))
# ' 111 111 11 1 1111 '
```

I had trouble locating many real world examples.  I decided to post it anyway, in case anyone had ideas.  

See also 

- `unique_justseen`
- `unique_everseen`
- `unique_to_each`

**Comment by bbayles** [comment]
The `cpu_usage` example is good, but like you say this doesn't seem to be general-purpose.

This inspired me to https://github.com/more-itertools/more-itertools/pull/440 - see what you think.
