### ISSUE TITLE
Recipe recommendation: "all_same_type"

### ISSUE THREAD

**Issue by lmmx** [more-itertools/more-itertools#442]
I'd like to suggest a new recipe to be included in the package, [via](https://stackoverflow.com/a/13252614/2668831) StackOverflow:

```py
def all_same_type(iterable):
    iterable = iter(iterable)
    try:
        first = type(next(iterable))
        return all(isinstance(i,first) for i in iterable)
    except StopIteration:
        return True
```

Can I recommend it for inclusion into the list of itertools recipes ([here](https://docs.python.org/3/library/itertools.html#itertools-recipes)) which ship with this package?

I think it'd fit in alongside the funcdef `all_equal`, which checks for value equality. This funcdef checks for _type_ equality (and can handle subclasses).

Since it requires exception handling in the case of a "void iterator" i.e. where calling `next` the first time raises `StopIteration` (such as `range(0)`), it can't be done in a one-liner so it warrants its own funcdef.

The handling of the void iterator is made to match the behaviour of all, returning `True` in the case that the assignment of `first` to `type(next(iterable))` throws `StopIteration` from the next call.

Credit: StackOverflow users EnricoGiampieri (who wrote the answer) and mgilson (who made a correction to it).

**Comment by bbayles** [comment]
Many thanks for the writeup. 

I think I'll decline this one. We have `all_equal` and `map` that can be composed to do this already: `all_equal(map(type, iterable))`. Make sense?

**Comment by lmmx** [comment]
Ahh apologies for overcomplicating it :man_facepalming: I'll add your suggestion to the source thread, thanks Bo
