### ISSUE TITLE
distinct_combinations() crashing with large r value

### ISSUE THREAD

**Issue by Minabsapi** [more-itertools/more-itertools#451]
For a personal project I wanted to use this handy function to avoid unnecessary duplicates, turns out it won't work when using it against a large iterable and `r` value (respectively of size 2000 and value 1000).

I'd suggest either to rewrite the function to avoid recursions as much as possible or warn (in the documentation or at runtime) that `r` should not exceed the maximum recursion call system limit.

**Comment by bbayles** [comment]
Any details you could share about: (a) the iterable, (b) the calculation or operation you're doing with it, (c) what error you got?

**Comment by Minabsapi** [comment]
Thanks for your reply
1. The iterable is a 1000-elements long list of integers
2. I am iterating through this generator function, doing some comparisons and testing some conditions. So nothing intensive or eventually impacting the function
3. The error is, as suggested in my initial message, a recursion error:
```
File "/home/minabsapi/SomeProject/main.py", line 69, in <module>
    for combination in more_itertools.distinct_combinations(sorted(working_group), len(local_fraction[0])):
  File "/home/minabsapi/.local/lib/python3.8/site-packages/more_itertools/more.py", line 3080, in distinct_combinations
    for suffix in distinct_combinations(pool[i + 1 :], r - 1):
  File "/home/minabsapi/.local/lib/python3.8/site-packages/more_itertools/more.py", line 3080, in distinct_combinations
    for suffix in distinct_combinations(pool[i + 1 :], r - 1):
  File "/home/minabsapi/.local/lib/python3.8/site-packages/more_itertools/more.py", line 3080, in distinct_combinations
    for suffix in distinct_combinations(pool[i + 1 :], r - 1):
  [Previous line repeated 993 more times]
  File "/home/minabsapi/.local/lib/python3.8/site-packages/more_itertools/more.py", line 3079, in distinct_combinations
    for i, prefix in unique_everseen(enumerate(pool), key=itemgetter(1)):
  File "/home/minabsapi/.local/lib/python3.8/site-packages/more_itertools/recipes.py", line 389, in unique_everseen
    iterable, keys = tee(iterable)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by bbayles** [comment]
What's the density of repetitions in the iterable, and what's your `r`? I'm wondering if this weren't recursive if you'd just run out of memory.

```
from more_itertools import distinct_combinations, ilen

n = 500
ilen(distinct_combinations('A' * n + 'B' * n, n))
```

That returns fine, but it's because there's the iterable is mostly repeated elements.

**Comment by Minabsapi** [comment]
The iterable is sorted, which greatly decreases the number of combinations (thus generator repetitions).
There's a lot of repetitions in it, with around 200 distinct integers for 2000 elements.
As previously stated, `r` had a value of 1000.
The function crashed almost immediately, so the RAM use didn't even increase.

From my investigation with the source code and the traceback it's all about the self recursion of `distinct_combinations`. Python doesn't have recursion limit as large as 1000.

**Comment by bbayles** [comment]
I missed the `r = 1000`, you're right.

Below is an iterative version of the algorithm adapted from [here](https://stackoverflow.com/q/32119075/353839), though it's (a) 
not very good, and (b) doesn't work for non-sorted input.

I looked at converting the existing recursive algorithm, but it isn't easily translated: not tail recursive, multiple stacks to maintain, etc. Suggestions welcome!

---

```python
def distinct_combinations_iter(iterable, r):
    pool = tuple(iterable)

    def next_combo(combo):
        items = list(pool)
        new_combo = list(combo)

        for x in new_combo:
            items.remove(x)

        for i in range(r - 1, -1, -1):
            larger = [x for x in items if x > new_combo[i]]
            if len(larger) < r - i:
                items.append(new_combo[i])
            else:
                larger.sort()
                new_combo[i:] = larger[:r - i]
                return new_combo
        return None

    combo = pool[:r]
    while combo is not None:
        yield tuple(combo)
        combo = next_combo(combo)

```
