### ISSUE TITLE
last() can try to use reversed()

### ISSUE THREAD

**Issue by brianmaissy** [more-itertools/more-itertools#453]
Hey, first of all, I'm new new to more-itertools, and wanted to say thanks! I'm currently in the process of migrating a codebase to use this instead of some of its own hand-rolled utils.

What follows is a suggestion for a possible improvement, based on behavior that one of those utils supported. If you like the idea I'm happy to open a PR.

If I call `last()` on an iterable which doesn't support indexing but does have a `__reversed__()` method, the entire iterable will be consumed. Is there a reason `last()` doesn't try to call `reversed()`?

Here's a toy example of the type of iterable which would benefit from that behavior:

```
class ReversibleSlowRange:
    def __init__(self, start, stop, step=1):
        self.start = start
        self.stop = stop
        self.step = step
        self.current = start

    def __iter__(self):
        return self

    def __next__(self):
        if self.current == self.stop:
            raise StopIteration()
        time.sleep(1)
        result = self.current
        self.current += self.step
        return result

    def __reversed__(self):
        return self.__class__(self.stop-self.step, self.start-self.step, -self.step)
```

I don't think this is relevant for any of the builtins or types from the standard library, and there might not be too many real-world examples of data structures like this, so if this is rejected for falling into the category of "bloat", I understand. Just thought I would suggest it in case it might be useful to somebody.

**Comment by brianmaissy** [comment]
For what it's worth, as of python 3.8 dicts fall into this category, so if someone is doing `last(some_dict)` in order to get the last key it would be faster if `last()` used `reversed()`. Still probably an uncommon use case, but the fact that it's relevant to a builtin type might make the difference.

**Comment by bbayles** [comment]
What do you think of [this implementation](https://github.com/more-itertools/more-itertools/compare/last-reversed?expand=1)?

One issue I ran into on my machine: due to [Python issue 38525](https://bugs.python.org/issue38525), version 3.8.0 will crash when trying to reverse an empty `dict`. That was fixed in [3.8.1](https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-1-release-candidate-1), but unfortunately Ubuntu packages 3.8.0 in [18.04](https://packages.ubuntu.com/bionic-updates/python3.8).

**Comment by brianmaissy** [comment]
The implementation looks good.

I might still leave the attempt to access the last item directly with `return iterable[-1]`, in case we get a data type that supports `getitem` but not `len`, and therefore isn't reversible). It isn't so likely, but might be worth it for the backwards compatibility, just in case someone relies on the behavior. It might also be faster than the common case for things like lists, tuples, etc, because of the overhead of the function calls (just from a very quick first look, some more serious profiling might be necessary before making that call):

```
In [1]: a = list(range(100000))

In [2]: %timeit a[-1]
23 ns ± 0.345 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [3]: %timeit next(reversed(a))
136 ns ± 4.75 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: dis.dis("a[-1]")
  1           0 LOAD_NAME                0 (a)
              2 LOAD_CONST               1 (-1)
              4 BINARY_SUBSCR
              6 RETURN_VALUE

In [5]: dis.dis("next(reversed(a))")
  1           0 LOAD_NAME                0 (next)
              2 LOAD_NAME                1 (reversed)
              4 LOAD_NAME                2 (a)
              6 CALL_FUNCTION            1
              8 CALL_FUNCTION            1
             10 RETURN_VALUE
```

Regarding the empty dict crash, wow, that's a pretty annoying bug. While I would hate to put a special `sys.hexversion == 0x030800F0 and isinstance(iterable, dict) and len(dict) == 0` check, I would hate crashing people's interpreters even more.

**Comment by bbayles** [comment]
See what you think of https://github.com/more-itertools/more-itertools/pull/454?
