### ISSUE TITLE
New feature proposal: all_unique

### ISSUE THREAD

**Issue by brianmaissy** [more-itertools/more-itertools#456]
I frequently find myself using the following idiom to check if all the elements of a collection are unique:

```python
if len(set(elements)) == len(elements):
    ...
```

Things that bother me about this:
1. repetitive idiom, but seems too small to extract to a utility function
2. doesn't support general iterables
3. inefficient, because it doesn't fail fast

I was wondering if a generalized `all_unique` function useful addition to this library? It would be an elegant complement to `all_equal`. There are many possible implementations, but I was imagining something along these lines (very similar to the implementation of `unique_everseen`):

```python
def all_unique(iterable, key=None):
    seenset = set()
    seenlist = []

    for element in map(key, iterable) if key else iterable:
        try:
            if element in seenset:
                return False
            else:
                seenset.add(element)
        except TypeError:
            if element in seenlist:
                return False
            else:
                seenlist.append(element)

    return True
```

What do you think? If you like it I'm happy to open a PR.

**Comment by bbayles** [comment]
I dig it. Could you go ahead and make a PR?

**Comment by brianmaissy** [comment]
sorry for the delay, just got around to it

**Comment by brianmaissy** [comment]
resolved
