### ISSUE TITLE
unzip: Handling the zero length case

### ISSUE THREAD

**Issue by servadestroya** [more-itertools/more-itertools#457]
For unzip, there's the case were if the iterable of sequences is empty, then unzip returns an empty tuple instead of a tuple of empty iterators. I understand that with no entries the unzip function cannot deduce any dimensions, so it is reasonable to return nothing.

Original post:
https://discuss.python.org/t/zip-and-more-itertools-unzip-handling-the-zero-length-case/5103

This function removes the need of checking for the zero length cases.
```python
T = TypeVar("T")
def unzipd(iterable: Iterable[Sequence[T]], dimension: int
) -> Tuple[Iterator[T], ...]:
    """
    Transposes iterable, similar to more_itertools.unzip
    except it retuns the correct number of iterables even
    when the iterable is empty
    """
    if not dimention > 0:
        raise ValueError(f"Dimention must be larger than 0, got {dimension}")
    unzipped = unzip(iterable)
    if len(unzipped) == dimension:
        return unzipped
    if len(unzipped) == 0:
        return tuple(map(iter, [()]*dimention))
    raise ValueError(f"Dimention provided does not match dimentions"
                     f"of unzipped iterable, provided {dimension}, "
                     f"got {len(unzipped)}")
```

Should something like this be added to unzip? I'm guessing adding a new function would be better.

**Comment by bbayles** [comment]
Thanks for the writeup.

My first thought is that it might make more sense to use `more_itertools.padded` on your input, so you're guaranteed to not have an empty iterable of iterables. Have you tried that?

**Comment by servadestroya** [comment]
Hmm I'm not sure that will work, doesn't ``more_itertools.padded`` add items to the iterable?

**Comment by servadestroya** [comment]
```
[[a1, b1], [a2, b2]] -> [[a1, a2], [b1, b2]]
[[a1, b1]] ->           [[a1],     [b1]]
[] ->                   [[],       []]     # what my function does
[] ->                   []                 # what unzip does
```
This function is intended to solve the last case

**Comment by bbayles** [comment]
Ah, OK. How about using `padded` on the *output*?

**Comment by servadestroya** [comment]
I guess I'm not seeing where ``padded`` could be used as ``unzip`` returns a tuple of iterators and not an iterator of iterators, you'd need to consume them into a tuple, and even then you'd need to map those tuples to iterators unless you want to hand out the same empty iterator object for each transposed row (does not really matter since they're empty but idk).

**Comment by jtwool** [comment]
Would something like this work? Do you need the arity check?

```python
def unzip_default(iterable, default_len=3):
    """Unzip an iterable but return default if empty."""
    unzipped = unzip(iterable)
    return unzipped if unzipped else [()]*default_len
```
