### ISSUE TITLE
Convert some keyword arguments to keyword-only

### ISSUE THREAD

**Issue by cool-RR** [more-itertools/more-itertools#460]
Check out this function signature:

```python
def windowed(seq, n, fillvalue=None, step=1):
    ...
```

Ideally, there should be a `*` before `fillvalue`, because the last two arguments shouldn't be positional. This is probably true in other functions.

It'll be difficult to add these now because of backward compatibility (existing code passing them as positional arguments,) but if you're interested it's possible to start a slow deprecation cycle that'll allow you to switch to keyword-only arguments in a year or two.

**Comment by bbayles** [comment]
Hmm, I don't mind if people want to do `windowed(iterable, 4, '', 2)`. Seems fine to me! If I add more keyword arguments they'll be to the end.
