### ISSUE TITLE
Feature request: `strict` keyword argument to `chunked`

### ISSUE THREAD

**Issue by cool-RR** [more-itertools/more-itertools#461]
I suggest a `strict` keyword argument to `chunked` that makes it raise an exception if there's a small chunk at the end. Ditto for `sliced` and maybe `windowed` if it has similar behavior.

**Comment by bbayles** [comment]
Given that this is coming to `zip`, I'll accept a PR for `chunked` and `sliced`, provided they don't mess with the implementation for the default case.

**Comment by cool-RR** [comment]
Cool. Right now I'm too busy to implement, but if someone will be interested in implementing, feel free to take this on. I'll be there to assist if anyone gets stuck.

**Comment by shlomif** [comment]
@cool-RR : @bbayles : I'd like to work on it. That put aside, I'd rather not block other potential contributors.

**Comment by cool-RR** [comment]
Good, go ahead.

**Comment by shlomif** [comment]
Just for the record, I believe this was implemented in #463 which has been merged. As a result, this issue can be closed once a new PyPI version will be published.

**Comment by cool-RR** [comment]
Thanks for implementing this!

**Comment by shlomif** [comment]
@cool-RR : you're welcome. And - thanks to @bbayles and you (and others) for the suggestions and commentary.
