### ISSUE TITLE
Weird result when using `windowed` on empty tuple

### ISSUE THREAD

**Issue by cool-RR** [more-itertools/more-itertools#462]
```python
>>> tuple(more_itertools.windowed((1, 2, 3, 4), 2))
((1, 2), (2, 3), (3, 4))
>>> tuple(more_itertools.windowed((), 2))
((None, None),)
```

What's the logic here?

**Comment by bbayles** [comment]
See https://github.com/more-itertools/more-itertools/pull/63#issue-92493574 for the logic:

> I like the simplicity of the `tee` versions, but they have the disadvantage of emitting nothing when the window's width exceeds the length of the iterable.
> I think when you specify that you want a window of width `n` you expect back `n` items, so I pad with a `fillvalue` (default `None)`, a la `itertools.zip_longest`.

**Comment by cool-RR** [comment]
Hmm, the comparison with `itertools.zip_longest` seems to suggest an iterable that has not enough items but still has items. `itertools.zip_longest` doesn't produce `(None, None)` out of the blue. I understand why `windowed` produces `((1, 2, 3), (4, None, None))` because we might not want to lose that `4`, but producing `((None, None, None),)` doesn't make sense to me.

**Comment by bbayles** [comment]
I'm unlikely to change the behavior at this point, but if there's something about the docs that would make this less surprising I'm open to altering them.

**Comment by cool-RR** [comment]
Can you link to examples of code that uses `windowed`? I'm bewildered as to how they would handle this edge case. They could check whether the first item is None on each iteration, but that's not very elegant, especially considering that None could be a value in their original iterator, and then they'd have to use a custom fillvalue... Oof.

**Comment by bbayles** [comment]
If there are examples (StackOverflow, GitHub) of people doing gymnastics to work around the empty iterator case, I'd definitely be more willing to change the behavior.

**Comment by cool-RR** [comment]
I could find only a handful of `windowed` uses in the wild. Couldn't hack any of them. I still think this should be changed, possibly with a migration policy. But your position of waiting for examples of people having trouble with it is reasonable.

**Comment by cool-RR** [comment]
Oh, I actually hoped you'd completly remove the use of fill values there. Now I'm using `n=2` on a list with length 1 and I was really surprised why I got the value `(first, None)` rather than just getting nothing.

**Comment by bbayles** [comment]
This is fairly prominent in the docs, right?

> When the window is larger than the iterable, fillvalue is used in place of missing values:
> ```
> >>> list(windowed([1, 2, 3], 4))
> [(1, 2, 3, None)]
> ```

We also have the `sliding_window` recipe, which behaves as you describe:

> If iterable has fewer than n items, then nothing is yielded:
> ```
> >>> list(windowed([1, 2, 3], 4))
> [(1, 2, 3, None)]
> ```
