### ISSUE TITLE
[Feature] Idea for a new iterator

### ISSUE THREAD

**Issue by GeorgeFischhof** [more-itertools/more-itertools#465]
Hi there,

I would like to propose a new iterator (I do not know how to name it ;-) ) it should work this way
new_iter_tool([1, 2, 3, 4, 5], [10, 20, 30], [100, 200, 300, 400])
result:
(1, 10, 100)
(2, 10, 100)
(3, 10, 100)
(4, 10, 100)
(5, 10, 100)
(5, 20, 100)
(5, 30, 100)
(5, 30, 200)
(5, 30, 300)
(5, 30, 400)

so cycling over all lists on given position.
It is good for testing, because product can be expensive, and with this every value is tried  out once in every place

BR,
George

**Comment by GeorgeFischhof** [comment]
Hi,

in the meantime I realized, that the thing I want is zip_longest with  fill_last or fill_first,

BR,
George

**Comment by GeorgeFischhof** [comment]
Hi,
standard's zip_longest fills the gap with a value that is given at function call.

In my case this is not good, because I need an element form the given list.
So the gap should be filled with one element from the the list, practically a list has two special elements: the first and the last.
When we iterate over an iterable we have the last item in hand. So filling the gap with this is easy and "cheap", 
in my example that is the repeated 5 in the first column, the repeated 30 in second column.

It could be the first item of the iterable too, but in this we have to initialize again the iteration, and get the first  item again, and keep that for gap filling.  So it is a little bit more expensive, but maybe sometimes it can be needed for someone.

I thought the function could be called something: zip_longest_with_fill, and a keyword parameter parameter for example fill could control whether the first or the last (default) item is uese to fill the gap.

BR,
George

**Comment by bbayles** [comment]
I'm open to a PR for this, maybe with the title `partial_product`, and documentation indicating that it's for use in testing.

**Comment by GeorgeFischhof** [comment]
HI,

I created a PR a few weeks ago, but unfortunately it did not compile. And
unfortunately I have no time to solve that. I creates tests as well, could
youplease check it? (I thought that you got email notification about that,
but it seems you did not.)

data: #489 opened on Dec 17, 2020 by GeorgeFischhof
<https://github.com/more-itertools/more-itertools/issues?q=is%3Apr+is%3Aopen+author%3AGeorgeFischhof>

BR,
George

Bo Bayles ***@***.***> ezt írta (időpont: 2020. szept. 30.,
Sze, 18:20):

**Comment by lonnen** [comment]
I'm happy to write up a PR for this. One thing isn't clear to me, though: what should be done when one or more of the provided iterators is empty? Every result requires at least one value from each provided iterator. I'm thinking `ValueError` is appropriate. Any early feedback?

**Comment by GeorgeFischhof** [comment]
Hi @lonnen, 
I created a PR for this, there is the code, and the test as well, just there was some issue with putting them into the packaged
https://github.com/more-itertools/more-itertools/pull/489/
there is no ValueError required here, that is the main point. When a list is exhausted, the latest item is used from that list.
This way you can check all the values from all the lists, and the number of "combinations" is the length of the longest list, not Cartesian product.

**Comment by GeorgeFischhof** [comment]
Hi @lonnen,
could you please check why my PR did not compile?

**Comment by lonnen** [comment]
Hey George - I'm not sure what you mean by "compile", or what error you were seeing where. I'm not a maintainer so I don't see most CI runs or outputs. Sorry.

I've written up a PR that implements the original posting here: https://github.com/more-itertools/more-itertools/pull/686

The branch you linked differs in implementation and adds a `fill value` that I confess I don't understand. My PR has code that should provide what you've described without needing a fill variable.

**Comment by GeorgeFischhof** [comment]
Hi @lonnen thanks, I will check my PR / create again.
My goal was to use all values from all lists, but use the smallest set of combinations, that is the number /length of longest list

**Comment by lonnen** [comment]
Sure thing. The solution proposed in PR #686 should produce `m - (n - 1)` outputs, where m is the total number of items in all iterators and n is the number of iterators.

A different iterator could be made that advances each iterator, repeating the last value when the iterator is exhausted, outputting the same number of outputs as the maximum length of the longest input iterator.  This will be fewer outputs in most cases,  and still use each item at least once, but sequential outputs may differ by more than one variable. If you're thinking about this from a testing perspective, having only a single value change between inputs is a rather useful for isolating issues.

We're now talking about a completely different function than the one proposed in the original comment, though. @bbayles which of these two options, if any, would you consider for inclusion in the library?

**Comment by bbayles** [comment]
I think the version in https://github.com/more-itertools/more-itertools/pull/686 scratches this itch.

**Comment by GeorgeFischhof** [comment]
actually from testing point of view both are useful: during a test we do not want to execute tests on a Cartesian product, if it is not necessary, because it takes long time.
So we want to reduce the test case set; the choice from those two depends on several things: time consuming, the relation between the lists, other constraints.
In my case, when I created my stuff, the lower number of cases was a good thing, and the relation between the lists allowed me to step ahead in all lists at a time.

**Comment by lonnen** [comment]
Does that mean a PR is also welcome for the alternative proposal of smallest number of cases to guarantee every value appears at least once?

I'm game to write that up but I'm at a loss for a name

**Comment by GeorgeFischhof** [comment]
@lonnen crated a new PR 
https://github.com/more-itertools/more-itertools/pull/691

**Comment by lonnen** [comment]
cool. I see bbayles is already on it in that PR so it looks like theres nothing for me to do
