### ISSUE TITLE
Idea: `swap` to swap pairs/items

### ISSUE THREAD

**Issue by eumiro** [more-itertools/more-itertools#478]
Sometimes I need to swap items coming from `dict.items()` or `enumerate()` to create a new dictionary:

```
>>> src = ['a', 'b', 'c']
>>> {v: k for k, v in enumerate(src)}
{'a': 0, 'b': 1, 'c': 2}
```

The two variables `k` & `v`are repeated and force the reader to verify they are the same and swapped.

```
>>> from more_itertools import swap
>>> dict(swap(enumerate(src)))
```

Would this make sense in `more_itertools`?

**Comment by bbayles** [comment]
It's definitely something I do frequently, and if I had a function to do it I would probably use it. But I think using it would be less clear than a literal: `{v: k for k, v in my_dict.items()}` is totally transparent: somebody who doesn't know Python could probably figure out what it does.

**Comment by pylang** [comment]
Yeah, when I think "swap", I think

`a, b = b, a`
