### ISSUE TITLE
allow passing your own key function to sort_together

### ISSUE THREAD

**Issue by brianmaissy** [more-itertools/more-itertools#480]
I recently came across a situation in which I wanted to use `sort_together`, but I also wanted to sort by a custom key.
What do you think about exposing a `key` argument to `sort_together`?

I think it would also be nice for the user's key function to take only the parameters corresponding to the `key_list`, so the common case of sorting by the first is the easiest, and so the two features of `key` and `key_list` work together.

Something to this effect:

```python
def sort_together(iterables, key_list=(0,), key=lambda *x: x, reverse=False):
    return list(
        zip(
            *sorted(
                zip(*iterables), key=lambda x: key(*always_iterable(itemgetter(*key_list)(x))), reverse=reverse
            )
        )
    )


list_of_x = [1, 2, 3]
list_of_y = [4, 5, 6]

sort_together((list_of_x , list_of_y), key=lambda x: x*2)
sort_together((list_of_x , list_of_y), key_list=(1,), key=lambda y: y*2)
sort_together((list_of_x , list_of_y), key_list=(0, 1), key=lambda x, y: x*y)
```

Happy to open a PR if you like the idea.

**Comment by bbayles** [comment]
I like the feature and welcome a PR. Could you break down the change to the `key` parameter in the function body? The `always_iterable` aspect isn't clear to me.

**Comment by brianmaissy** [comment]
yeah I'll make it clearer in the PR.

basically `itemgetter` sometimes returns a single value and sometimes a tuple, but I want to always unpack the return value and pass it as `*args` to the `key` function.
