### ISSUE TITLE
str.join as an iterator

### ISSUE THREAD

**Issue by aure-olli** [more-itertools/more-itertools#482]
Hi

I often use string iterators to build long string without paying the cost of building intermediate strings. However, there is not easy way to have the behavior of `str.join`, but as an iterator.
```python
''.join(more_itertools.join(', ', 
    (str(i) for i in range(5))))
> '0, 1, 2, 3, 4'
```
It would also be good to have a version taking iterables instead of values, for the same purpose of iterating many string segments without paying the intermediate strings.
That function would be equivalent to 
`itertools.chain.from_iterables(more_itertools.join(sep, values))`
```python
''.join(more_itertools.join_iterables((', ',), 
    (('v', str(i), '=', str(i)) for i in range(5))))
> 'v0=0, v1=1, v2=2, v3=3, v4=4'
```

For an example usage:
```python
request = ''.join(itertools.chain(
    ('INSERT INTO ', table, '('),
    more_itertools.join(', ', columns),
    (') VALUES (',),
    more_itertools.join_iterables(('), (',), 
        (more_itertools.join(', ', '%s' for v in value) for value in values)),
    (')',)
))
args = list(itertools.chain.from_iterables(values))
cursor.execute(request, args)
```

The implementation is pretty straightforward
```python
def join(sep, values):
    notfirst = False
    for value in values:
        if notfirst:
            yield sep
        else:
            notfirst = True
        yield value

def join_iterables(sep, values):
    notfirst = False
    for value in values:
        if notfirst:
            yield from sep
        else:
            notfirst = True
        yield from value
```

**Comment by bbayles** [comment]
Hmm, isn't [intersperse](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.intersperse) the same as `join`?

**Comment by aure-olli** [comment]
Oh right :sweat_smile: I actually didn't even know this word, I didn't find it in the doc.

Thanks
