### ISSUE TITLE
Combining peekable with seekable

### ISSUE THREAD

**Issue by gsakkis** [more-itertools/more-itertools#485]
`peekable` and `seekable` are quite handy; unfortunately you have to choose one or the other:
```
# 1
In [55]: sp = seekable(peekable('ab'))

In [56]: list(sp)
Out[56]: ['a', 'b']

In [57]: list(sp)
Out[57]: []

# bool() is always true
In [58]: bool(sp)
Out[58]: True

# also cannot peek
In [59]: sp.peek()
---------------------------------------------------------------------------
AttributeError: 'seekable' object has no attribute 'peek'
```
```
# 2
In [64]: ps = peekable(seekable(range(2)))

In [65]: list(ps)
Out[65]: [0, 1]

In [66]: list(ps)
Out[66]: []

# bool() works fine now
In [67]: bool(ps)
Out[67]: False

# but there is no seek
In [68]: ps.seek(0)
---------------------------------------------------------------------------
AttributeError: 'peekable' object has no attribute 'seek'
```

It would be nice if these could be combined, or extend `seekable` to support the `peekable` API, or perhaps join these two into a single class.

**Comment by bbayles** [comment]
Good idea. I would accept a PR that adds `peak` and `bool` support to `seekable`.

**Comment by gsakkis** [comment]
Sounds good, I'm on it. 

How about `__getitem__`? I'd like to add this too but I'm not sure what the semantics should be. For `peekable.__getitem__` the returned value depends on the current state of the wrapped iterator:
```
In [1]: from more_itertools import peekable

In [2]: p = peekable("abc")

In [3]: p[0]
Out[3]: 'a'

In [4]: next(p)
Out[4]: 'a'

In [5]: p[0]
Out[5]: 'b'
``` 
Should `seekable.__getitem__` do the same or be stateless, i.e. `p[0]` be always `'a'` in the example above (at least for `maxlen=None`)? I'd find the latter more intuitive; the downside is that in this case `seekable` won't be a drop-in replacement of `peekable`.

**Comment by bbayles** [comment]
Hmm, I'd rather keep it simple. Give `seekable` the `bool` and `peek` support.

Ideally I would have made both wrappers simpler, so they could be stacked. But I'd rather not break them to rationalize them.

**Comment by gsakkis** [comment]
Thanks, I opened #486. 

Just to clarify, do you find specifically `seekable.__getitem__` complex? Or do you also regret adding it `__getitem__` in `peekable`?

**Comment by bbayles** [comment]
`__getitem__` in `peekable` was probably a little much, in retrospect.
