### ISSUE TITLE
Provide a way for time_limited() to indicate why it ended

### ISSUE THREAD

**Issue by roysmith** [more-itertools/more-itertools#487]
I have a perfect use for time_limited(), but I'd also like to be able to tell the end user, "Data stream truncated after N seconds, results are incomplete"  As far as I can tell, there's no way determine if the iteration ended because of a timeout or because the underlying iterator was exhausted.

Maybe add an attribute to the returned iterator?  I could envision something like:

```
iterator_2 = time_limited(n, iterator_1)
my_data = list(iterator_2)
if iterator_2.timed_out:
    print("Data stream truncated after N seconds, results are incomplete")
```
but I'm not actually sure that's implementable.

**Comment by bbayles** [comment]
I like it! I think it is implementable, if `time_limited` were turned into a class. I'll play with it. Great suggestion!
