### ISSUE TITLE
Inconsistent behavior of stagger()?

### ISSUE THREAD

**Issue by jenstroeger** [more-itertools/more-itertools#491]
Looking at the [stagger()](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.stagger) iterator I think there’s an inconsistency here. If I use stagger() to iterate over the elements only:
```python
>>> list(stagger([0,1,2,3], offsets=(0,)))
[(0,), (1,), (2,), (3,)]
```
which is what I’d expected. If I expand the context by the previous element:
```python
>>> list(stagger([0,1,2,3], offsets=(-1, 0,)))
[(None, 0), (0, 1), (1, 2), (2, 3)]
```
which, too, is what I’d expected. But if I expand the context by the next element then that behavior changes:
```python
>>> list(stagger([0,1,2,3], offsets=(0, 1)))
[(0, 1), (1, 2), (2, 3)]
```
I think the resulting iteration stops one element short: I had expected `(3, None)` here as well. Considering that stagger() is implemented using [zip_offset()](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.zip_offset) I think the problem may be that stagger isn’t really a simple macro for that function… 🤔

**Comment by bbayles** [comment]
Isn't this what the `longest` keyword argument is supposed to do?

**Comment by jenstroeger** [comment]
> Isn't this what the `longest` keyword argument is supposed to do?

That’s what I find confusing. From the doc string:

> To continue until the first element of a tuple is the last item in the iterable, set longest to `True`.

which seems to mean that stagger() auto-fills only look-ahead elements, not look-behinds. What I had expected is consistency on both ends of the sequence, i.e. that _all_ elements of the given iterable are visited and for each visited element _i_ others at offsets relative to _i_ are returned as tuple; if they don’t exist then use `fillvalue`. The `longest` feels like an inconsistent fudge at the end of the sequence only.

Take the default `offset=(-1, 0, 1)`, for example. The above example is then:
```python
>>> list(stagger([0, 1, 2, 3]))  # List with 4 elements.
[(None, 0, 1), (0, 1, 2), (1, 2, 3)]  # List with 3 elements, and (2, 3, None) is missing?
```
which fudges the first element but not the last. But if I add `longest=True` then I get
```python
>>> list(stagger([0, 1, 2, 3], longest=True))
[(None, 0, 1), (0, 1, 2), (1, 2, 3), (2, 3, None), (3, None, None)]  # Where is the initial (None, None, 0) tuple?
```
which produces an inconsistent result because it doesn’t fudge the first elements: a list of four elements and a max `offset` of ±1 should yield 6 result elements (equally fudged on both ends). To illustrated this further:
```python
>>> list(stagger([0, 1, 2, 3], offsets=(-2, +2)))  # List with 4 elements.
[(None, 2), (None, 3)]  # I expected 4 elements: [(None, 2), (None, 3), (0, None), (1, None)]
>>> list(stagger([0, 1, 2, 3], offsets=(-2, +2), longest=True))  # List with 4 elements.
[(None, 2), (None, 3), (0, None), (1, None), (2, None), (3, None)]  # Not sure if `longest` would have a sensible meaning here…
```

### My problem

Perhaps I misunderstand the intention of stagger().

What I’m looking for is an iterator which iterates over _all_ elements _i_ of a sequence, and for each _i_ returns a tuple (_i-1_, _i_, _i+1_) (happens to be the default `offsets` value) and fudge using None if an element doesn’t exist. The [windowed()](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.windowed) iterator didn’t work because it’s a sliding window over the sequence and so I thought stagger would cover my need. But it doesn’t quite… 🤔

**Comment by bbayles** [comment]
Can you use `padded` to accomplish what you want? Meaning, I think you can make sure your iterable always reaches the right length for you window size.

**Comment by jenstroeger** [comment]
Doesn’t look like it. For every element _i_ in an iterable, I want its previous (_i-1_) and next (_i+1_) element:
```python
def didum(seq, fillvalue=None):
    prev = curr = next_ = fillvalue
    p = more_itertools.peekable(seq)
    for curr in p:
        try:
            next_ = p.peek()
        except StopIteration:
            yield prev, curr, fillvalue
            break
        yield prev, curr, next_
        prev = curr
```
which gives me:
```python
>>> list(didum([1, 2, 3]))
[(None, 1, 2), (1, 2, 3), (2, 3, None)]
```
See how I have _N_ iterations for an input sequence of length _N_, and for every element _i_ the tuple contains its previous and next.

**Comment by MSeifert04** [comment]
I agree that stagger filling leading elements but not trailing elements seems somewhat counter-intuitive. Maybe there's a good reason for this inconsistency though (sometimes being practicable beats being consistent).

If you don't care about the empty case that much you could combine `windowed` and `flatten`:

```
>>> import more_itertools as mi
>>> list(mi.windowed(mi.flatten([[None], [], [None]]), 3))
[(None, None, None)]
>>> list(mi.windowed(mi.flatten([[None], [0], [None]]), 3))
[(None, 0, None)]
>>> list(mi.windowed(mi.flatten([[None], [0, 1], [None]]), 3))
[(None, 0, 1), (0, 1, None)]
>>> list(mi.windowed(mi.flatten([[None], [0, 1, 2], [None]]), 3))
[(None, 0, 1), (0, 1, 2), (1, 2, None)]
>>> list(mi.windowed(mi.flatten([[None], [0, 1, 2, 3], [None]]), 3))
[(None, 0, 1), (0, 1, 2), (1, 2, 3), (2, 3, None)]
```
