### ISSUE TITLE
Feature proposal: Rich iterator class

### ISSUE THREAD

**Issue by gsakkis** [more-itertools/more-itertools#493]
I have implemented a `rich_iter` class that exposes `itertools` functions (plus a few builtins like `map` and `filter`) as methods, allowing a method chaining / piping style of transforming an iterable. Toy example:
```
import operator as op

rich_iter \
    .count() \
    .map(lambda x: x*x) \
    .takewhile(lambda x: x < 1000) \
    .filter(lambda x: x%3 == 1) \
    .islice(1, None) \
    .reduce(op.add)

# Out: 6950
```
Is this something that could be part of `more-itertools`, at least in principle? If yes let me know and I'll open a PR.

**Comment by bbayles** [comment]
My answer [here](https://github.com/more-itertools/more-itertools/issues/250) was:
> I don't get the appeal of this - why are dots better than parens? However, I'll certainly entertain an addition that doesn't entail re-writing all the existing tools.

I think I'll modify that to: I'd rather not add this, unless there's some example of something that can't be expressed in the current paradigm.

**Comment by gsakkis** [comment]
I guess I'm two years late to the discussion, not to mention (at least) 2 other libraries that do this already :sweat_smile:

> unless there's some example of something that can't be expressed in the current paradigm.

I doubt this is possible, strictly speaking; the expressive power is the same, what differs is the API. It is used extensively in other libraries, [Pandas](https://towardsdatascience.com/the-unreasonable-effectiveness-of-method-chaining-in-pandas-15c2109e3c69) for example. In a nutshell the readability argument is, as mentioned [here](https://tomaugspurger.github.io/method-chaining):

>  both the code and the flow of execution are from top to bottom, and the function parameters are always near the function itself, unlike with heavily nested function calls.

Method chaining aside, I can think of two other benefits of a class-based paradigm:
1. Iterator state policy
The iterator returned by `itertools`/`more-itertools` functions shares state with the input iterator; forwarding the one forwards the other too. In my `rich_iter` implementation this is the default behavior but I added two more:
- copy: every method invocation creates a new independent iterator (using `itertools.tee` internally)
```
In [3]: it = rich_iter(range(10), StatePolicy.COPY).map(lambda x:-x)

In [4]: list(it.filter(lambda x: x%2==0).chain(it.filter(lambda x: x%2==1)))
Out[4]: [0, -2, -4, -6, -8, -1, -3, -5, -7, -9]
```

- transfer: every method invocation "transfers" the state ownership to the new returned iterator; attempting to forward the input iterator again raises an exception. This prevents subtle bugs caused by shared state. 
```
In [5]: it = rich_iter(range(10), StatePolicy.TRANSFER)

In [6]: it.filter(lambda x: x%2==0).chain(it.filter(lambda x: x%2==1))
...
RuntimeError: iterator can no longer be used
```
2. Operator overloading
We can overload operators to provide a more terse DSL-like API for frequently used functions. For example overloading `+` for `it.chain`, `|` for `map` and `&` for `filter`
```
In [3]: from operator import neg

In [4]: is_even = (lambda x: x%2==0)

In [5]: is_odd = (lambda x: x%2==1)

In [6]: it = rich_iter(range(10), StatePolicy.COPY) | op.neg

In [7]: list((it & is_even) + (it & is_odd))
Out[17]: [0, -2, -4, -6, -8, -1, -3, -5, -7, -9]
```
Arguably this is more controversial but it's an option.

**Comment by bladeoflight16** [comment]
@bbayles While I'm not a strong proponent of these fluent interfaces, the motivation here is stylistic rather than functional. Consider what the OP's example looks like as a single expression with current Python methods:

```
reduce(
    op.add,
    islice(
        filter(
            lambda x: x%3 == 1,
            takewhile(
                lambda x: x < 1000,
                map(
                    lambda x: x*x,
                    count(),
                )
            )
        )
        1,
        None,
    )
)
```

This is virtually impenetrable. It's hard to even find the starting point, much less follow the sequence of operations. I think we can all agree that this is so difficult to read that it's just bad code.

A temporary variable is a big improvement:

```
i = count()
i = map(lambda x: x*x, i)
i = takewhile(lambda x: x < 1000, i)
i = filter(lambda x: x%3 == 1, i)
i = islice(i, 1, None)
i = reduce(op.add, i)
```

But this is still pretty cluttered. The fluent interface definitely has the advantage in readability over the current options, although I would favor parentheses over the OP's line continuations:

```
i = (
    rich_iter(count())
    .map(lambda x: x*x)
    .takewhile(lambda x: x < 1000)
    .filter(lambda x: x%3 == 1)
    .islice(1, None)
    .reduce(op.add)
)
```

---

That said, I would favor a new *operator* rather than a fluent interface. Piping is a familiar and effective tool in command line interfaces like bash and PowerShell, and it's my opinion that Python would benefit from implementing such functionality itself:

```
i = (
    count()
    => map(lambda x: x*x)
    => takewhile(lambda x: x < 1000)
    => filter(lambda x: x%3 == 1)
    => islice(1, None)
    => reduce(op.add)
)
```

But I'm not sure that would be possible without a major effort to re-implement iterator operations or drastically affecting how the code is parsed.

**Comment by bbayles** [comment]
I think @bladeoflight16's comment sums things up nicely.

If there's a `rich-itertools` library that imports `more-itertools` and adds this functionality on it, I'll link it from the `README`. But I'm not inclined to maintain a parallel version of each function in this library.

Thanks!
