### ISSUE TITLE
Count items in iterator?

### ISSUE THREAD

**Issue by roysmith** [more-itertools/more-itertools#494]
Here's a suggestion:

`count(iter)
`

which consumes an iterator and returns the number of items it yielded.  This is basically

`len(list(iter))
`

but without having to waste memory building the intermediate list.  [This recipe on stackoverflow](https://stackoverflow.com/questions/3345785/getting-number-of-elements-in-an-iterator-in-python) looks reasonable.  Having it as a documented function would be handy and make code that uses it less obtuse.

This came up in some code I'm writing now.  I'm using [mwclient's ](https://mwclient.readthedocs.io/en/latest/index.html) site.search() function, which returns an iterator over the results.  All I care about is how many pages it found.

**Comment by MSeifert04** [comment]
This sounds a lot like the already present function [`more_itertools.ilen`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.ilen). Would that match your use-case?

**Comment by roysmith** [comment]
Doh.  Yeah, that's exactly what I was looking for, thanks.
