### ISSUE TITLE
Idea: An iterator wrapper that counts items yielded so far

### ISSUE THREAD

**Issue by krzysieq** [more-itertools/more-itertools#502]
Sometimes I find that I have an iterable that I want to consume, but as a side effect I want to count the number of items yielded:
```python
counting_iterator = CountingIterator(my_iterable)
consume(counting_iterator)
counting_iterator.counter  # -> number of `next` calls on the iterator
```

**Comment by roysmith** [comment]
Isn't that just len(my_iterable)?

**Comment by krzysieq** [comment]
Perhaps it's most useful to think about cases where iteration over `my_iterable` is expensive (so the `len` call is wasteful) or `my_iterable` is an iterator that can't be re-iterated over once exhausted (so code that wants to separately call `len` and `consume` would need to cache elements of the iterator in some auxiliary store).

**Comment by bbayles** [comment]
`ilen` does this, yes?

**Comment by bbayles** [comment]
Oh, I was missing the "so far" aspect. I get it now.

**Comment by krzysieq** [comment]
You're right, `len` doesn't work with an arbitrary iterable so the argument above really should have been about `ilen`.

**Comment by pylang** [comment]
I can imagine this working with `make_decorator` and using it to count yielded items, similar to a classic `@count_calls` decorator, which tallies how many times a function is called.

**Comment by bbayles** [comment]
I like this idea - check out https://github.com/more-itertools/more-itertools/pull/503 and let me know what you think?

**Comment by krzysieq** [comment]
Thanks, that looks great.
