### ISSUE TITLE
Update stable docs

### ISSUE THREAD

**Issue by impredicative** [more-itertools/more-itertools#506]
The [`latest`](https://more-itertools.readthedocs.io/en/latest/versions.html) doc shows the version history of v8.7.0, but the [`stable`](https://more-itertools.readthedocs.io/en/stable/versions.html) doc doesn't. The `stable` docs seem to have failed to update. Or is v8.7.0 not considered stable for some reason?

**Comment by bbayles** [comment]
RTD is supposed to update when there's a new release, but for some reason did not. I've kicked it, and the docs are now showing. Thanks!
