### ISSUE TITLE
denormalize

### ISSUE THREAD

**Issue by olirice** [more-itertools/more-itertools#521]
### Description
A function to de-normalize elements of a record against each other

So the input value would be a
```python 
from typing import Iterable, Any

Iterable[Iterable[Any]]]
```

### References

- Would be useful for flattening nested data e.g. prepping for CSV, or SQL inserts

### Examples

```python
from typing import Iterable, Tuple
from itertools import product


def denormalize(iterable: Iterable[Iterable[Any]], iter_strings: bool = False) -> Tuple:
    """Denormalize iterable components of each record"""
    
    for record in iterable:
        iter_elements = []
        for element in record:
            
            # Check for string and string iteration is allowed
            if isinstance(element, str) and iter_strings:
                iter_elements.append(element)
                
            # Check for string and string iteration is not allowed
            elif isinstance(element, str):
                iter_elements.append([element])
                
            # Check for iterable
            elif hasattr(element, '__iter__'):
                iter_elements.append(element)
                
            # Check for non-iterable
            else:
                iter_elements.append([element])

        for row in product(*iter_elements):
            yield row

values = [
    ("abc", [1, 3, 5], ('h', 'i')),
    ("xyz", [2, 4], None),
]

for row in denormalize(values):
    print(row)

# Output:
# --------------
# ('abc', 1, 'h')
# ('abc', 1, 'i')
# ('abc', 3, 'h')
# ('abc', 3, 'i')
# ('abc', 5, 'h')
# ('abc', 5, 'i')
# ('xyz', 2, None)
# ('xyz', 4, None)
```

The only non-obvious/potential gotcha I can see is that if one of the elements is iterable, but empty, no results would be returned for that row. That behavior seems correct, but worth pointing out.

```python
values = [
    ([1, 3, 5], []),
]

for row in denormalize(values):
    print(row)
    
# no output
```

---

I'm happy to open a PR if there is any interest. Thanks!

**Comment by pylang** [comment]
This looks a bit like `itertools.product`, given `[[`abc`], [1, 3, 5], ("h", "i")]`.  lmk if i'm missing something.  Can you explain the word denormalized used in this case?

**Comment by olirice** [comment]
The name de(normalize) came from relational algebra / database jargon

If you have 2 fully normalized tables (3NF) connected via a foreign key and join them together to flatten them out, you're reducing the degree of normalization => denormalize

For example, a users collection and an addresses collection where each user can have multiple addresses

Normalized would be 
`[User1, [Address1, Address2]]` 
and denormed would be 
`[[User1, Addres1], [User1, Address2]]`

Its a little tortured but was the best I could come up with.

---

Yeah I think you're right, its amounts to a `itertools.product` that treats non-iterable arguments as an iterable containing a single element & optionally does not iterate strings.

**Comment by bbayles** [comment]
Thanks for the writeup. I'm inclined to pass on this, given the similarity to `product`.
