### ISSUE TITLE
as_lists - a utility for converting iterables to lists - designed to be used in conjunction with other itertools

### ISSUE THREAD

**Issue by brianmaissy** [more-itertools/more-itertools#523]
I frequently find myself using functions from more-itertools for their basic functionality, but my iterables are tiny so I don't actually need them to be lazily evaluated, and I often find myself immediately converting the return values to lists.

For example:
```python
stuff, other_stuff = more_itertools.partition(predicate, all_the_stuff)
stuff = list(stuff)
other_stuff = list(stuff)
```
Obviously there's typing issues involved with that, but introducing two new names to the local scope isn't great, so I end up doing something like:
```python
stuff, other_stuff = map(list, more_itertools.partition(predicate, all_the_stuff))
```
The problem with this is that I end up with long one-liners which aren't so clear to read.

I propose adding a new itertool to the following effect (name and implementation open for suggestions):
```python
def as_lists(iterables: Collection[Iterable[T]]) -> List[List[T]]:
    return list(map(list, iterables))
```

I know it's so tiny as to be stupid, but it would allow me to do this, which seems like the best possible outcome.
```python
stuff, other_stuff = as_lists(more_itertools.partition(predicate, all_the_stuff))
```
I would probably feel silly implementing an `as_lists()` utility like this in my own code, but if it came with more_itertools it would feel more legitimate (and hopefully help other people).

I considered generalizing the solution to handling nested iterables, etc, but I think the principal use case is calling an itertool that returns more than one iterable, and then converting each one to a list. If (like me) most users would likely unpack the results directly into other variables, the final call to `list()` may be superfluous, but I feel like it should be there for good measure (and in the spirit of the function).

It would have the bonus benefit that in the future, when adding more itertools, debates about whether it should return iterables or lists could be resolved with less guilt in favor of returning iterables, since there's a clean and standard way to convert them to lists.

If there's a completely different solution to my use case I'd love to hear proposals. Or if there's already something like this somewhere and I just didn't find it that's great too.

**Comment by pylang** [comment]
I've debated whether adding casting-helpers would actually help me.  In general, I'm not convinced they do.

> introducing two new names to the local scope isn't great

I'm not sure why.  It's common to do in Python.   Example with `partition`, I may not remember what it returns.  Unpacking is a good reminder on the return type.  Assigning to explicit names gives a hint on its contents.

> The problem with this is that I end up with long one-liners which aren't so clear to read.

`map(list, ` is 10 chars (plus space).  `as_lists(` is 9 chars.  Is it that much longer? :)

As to debates on return types, with itertools, the default type is usually an iterator, with other types being exceptions to the rule.

**Comment by brianmaissy** [comment]
Ok, thanks!
