### ISSUE TITLE
Add transpose function

### ISSUE THREAD

**Issue by qalshidi** [more-itertools/more-itertools#527]
### Description
Transposes an iterable of iterables. I found myself needing a function like this a lot.

### References
https://stackoverflow.com/questions/6473679/transpose-list-of-lists

### Examples
```
>>> list(transpose([[1, 2, 3], [4, 5, 6]]))
[(1, 4), (2, 5), (3, 6)]
```

**Comment by pylang** [comment]
Is `transpose()` something other than as `more_itertools.interleave`?

https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.interleave

**Comment by qalshidi** [comment]
> Is `transpose()` something other than [`more_itertools.interleave_longest`](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.interleave_longest)?

Definitely. Transpose returns an exchange of rows and columns. Interleave returns a single row. They definitely have different uses and the implementations are different.
