### ISSUE TITLE
Question about first() and life cycle of provided iterable

### ISSUE THREAD

**Issue by CarstenLeue** [more-itertools/more-itertools#529]
This is a question rather than a bug:

Take the `first()` function as an example https://github.com/more-itertools/more-itertools/blob/master/more_itertools/more.py#L160. It accepts an iterable as its first parameter, which can also be an iterator or a generator. I would expect the functionality of the method to be the same no matter what kind of iterable I pass in.

Per design the function only extracts the first element of the provided iterable, but the behaviour for repeated invocation on the same iterable is different:
- if the iterable is a not an iterator or generator, then repeated invocation will yield the same result each time (each time the first element)
- if the iterable is an iterator (or generator) then repeated invocation will return one element after the other of the iterator, each time a different value. At least I would have expected that a second invocation yielded the first element on the first invocation and from there on the default value, because there is no more than one first element in an iterator. 

The other aspect is that of the handling of generators as an input. A generator has a [close](https://docs.python.org/3/reference/expressions.html#generator.close) method that finalizes the generator when not exhausted completely. Since the `first` operation is by design not exhausing a generator with more than one element, shouldn't the method close the input sequence in case it's a generator?

**Comment by bbayles** [comment]
Hmm, I think the answers are:
* If you're passing an iterator in, you should expect that `first()` will advance it - how could it not?
* If you're passing a list or tuple in, you should expect that `first()` won't advance it - how could it?
* I don't think `first()` ought to interfere with subsequent use of the generator

Hope that helps!

**Comment by CarstenLeue** [comment]
> If you're passing an iterator in, you should expect that first() will advance it - how could it not?
I think I would have expected `first` to exhaust the iterator instead of simply advancing it. In particular to close it if it is a generator.

> I don't think first() ought to interfere with subsequent use of the generator
I'd like to understand the reasoning behind this. Maybe a better example is the `interleave` function which takes multiple iterables and returns an iterator. Using the resulting iterator might leave the input iterators not fully exhausted and if they are not closed by the `interleave` operation is the expectation that the calling code is in charge of tracking the life cycle of all inputs, e.g. via a `with closing(...)` syntax?

**Comment by bbayles** [comment]
Recommendation: follow the call to `first()` with a call to `consume()` if you want everything consumed.

> is the expectation that the calling code is in charge of tracking the life cycle of all inputs

Yes indeed.

**Comment by CarstenLeue** [comment]
> Recommendation: follow the call to first() with a call to consume() if you want everything consumed.

I see a couple of problems with that approach:
- it does not work for infinite generators
- it is very tedious, because the requirement to keep track of all sources and to close/exhaust them

Googling I stumbled across https://www.python.org/dev/peps/pep-0533/ which looks like it would address my issues. Unfortunately it's deferred :-)

Thanks for the insights, though

**Comment by CarstenLeue** [comment]
As an example, how would you suggest to handle this case:

```python
class SomeAbstraction(ABC):

   @abstractmethod
   def produce_some_data(self) -> Iterable[str]:
      ...
```

```python
def handle_data_from_abstraction(delegate: SomeAbstraction):
   data = first(delegate.produce_some_data())
```
 
In such a scenario what code would be responsible for handling the life cycle of the iterable returned by `produce_some_data`? Assume that an implementation of `SomeAbstraction` returned an infinite generator (what matches the interface contract).

Would `handle_data_from_abstraction` have to check if the return value of `delegate.produce_some_data()` is closeable and then create a context, e.g. like so?

```python
def handle_data_from_abstraction(delegate: SomeAbstraction):
   iterable = delegate.produce_some_data()
   if hasattr(iterable, 'close'):
      with closing(iterable) as stream:
          data = first(stream)
   else:
      data = first(iterable)
```

This solution appears to carry a lot of boilerplate.
Or is there anything else wrong with the approach of returning an iterable from an abstract interface?

**Comment by bbayles** [comment]
I would give `SomeAbstraction` `__enter__` and `__exit__` methods, and then do:

```python
def handle_data_from_abstraction(delegate: SomeAbstraction):
    with delegate as d:
       data = first(d.produce_some_data())
```

**Comment by CarstenLeue** [comment]
But that has a different semantic, this manages the lifecycle of `SomeAbstraction` vs the lifecycle of the data. For just one abstract method you could argue that there is not much difference but with more methods there is:

```python
class SomeAbstraction(ABC):

   @abstractmethod
   def produce_some_data1(self) -> Iterable[str]:
      ...

   @abstractmethod
   def produce_some_data2(self) -> Iterable[str]:
      ...
```

Maybe my disconnect is that it is just not a valid pattern in Python to return an `Iterable` from an abstraction layer because of the ambiguities of life cycle. Is is best practice to return context managers instead, e.g. like so:

```python
class SomeAbstraction(ABC):

   @abstractmethod
   def produce_some_data(self) -> ContextManager[Iterable[str]]:
      ...
```

**Comment by bbayles** [comment]
My thought is that if you have some thing that yields data that needs special hand-holding to make sure it gets cleaned up, then the way to do that in Python is to make a context manager that handles that stuff.

e.g.

```python
def produce_some_data(self):
    with whatever_resource() as r:
        for item in r.frobuate():
            yield self.defrobulate(item)
```

Now you can call `first()` on the results of that method with confidence.

**Comment by CarstenLeue** [comment]
@bbayles your example illustrates exactly the point I am struggling with. In this case the resource will NOT be cleaned up deterministically. The return value of your `produce_some_data` is a generator. In case the resource `r.frobuate()` contains more than one item, using `first` will only consume the first item but leave the generator active. It will NOT cause the `with` block to close the resource unless eventually garbage collection comes in. But the whole point of using context managers - from my understanding - is to provide deterministic cleanup of a resource and not to rely on GC.

In effect your example is how I would expect as a valid implementation of `produce_some_data`. But I do not see how the cleanup works unless the user of the resulting generator explicitly closes the generator when done. In my mind this would be the `first` method (and other methods that consume iterables). And this led to my question in the first place. 

Am I missing a python feature that does lead to deterministic resource cleanup in your example?

**Comment by bbayles** [comment]
> But the whole point of using context managers - from my understanding - is to provide deterministic cleanup of a resource and not to rely on GC.

I don't think "not relying on the garbage collector" is the point of context managers.

Suppose you do `it = inst.produce_some_data(); item = first(it)`. When `it` goes out of scope (or when you `del` it) the `with` block will complete and your cleanup will happen.

<details><summary>Context manager going out of scope</summary>

```python
from more_itertools import first


class Demo:
    def __init__(self, iterable):
        self.iterable = iter(iterable)
    
    def __iter__(self):
        return self
    
    def __next__(self):
        return next(self.iterable)
    
    def __enter__(self):
        return self
    
    def __exit__(self, *args, **kwargs):
        print('Cleanup procedure started')


def process():
    inst = Demo([0, 1, 2, 3])
    with inst as it:
        item = first(it)
        print(item)
    print('Exiting process...')

process()
```

This prints:
```
0
Cleanup procedure started
Exiting process...
```

</details>

The generator isn't "closed" but the cleanup procedure still runs.

**Comment by CarstenLeue** [comment]
> The generator isn't "closed" but the cleanup procedure still runs.

That is only true if the system is not under load. The garbage collector will run "eventually", whenever there are free resources but not deterministically. It does not run when `it` falls out of scope, it is only eligible to run from that point on but it can do it at any future point in time, including "never".

That's - from my understanding - where context managers chime in. Their life cycle is guaranteed to be fulfilled when the context manager falls out of scope, deterministically.

If this were different, what's the point of a context manager from your perspective?

**Comment by bbayles** [comment]
The point of a context manager is to guarantee that the cleanup procedure always runs, similar to try/finally. That was the rationale in PEP 343. See also PEP 342.

**Comment by CarstenLeue** [comment]
So you do not seen an issue with the fact that in https://github.com/more-itertools/more-itertools/issues/529#issuecomment-871737032 the with block is not exited deterministically and probably only very late if the system is under load? Wouldn't this bear the potential to starve the `whatever_resource`?

**Comment by bbayles** [comment]
I think that if I have some resource that needs very particular hand holding and cleanup at a specific time, then I don't use it with a generator.

This was a nice discussion, but the issue tracker probably isn't the place for it to continue. Thanks!
