### ISSUE TITLE
repeat_each

### ISSUE THREAD

**Issue by FinalSh4re** [more-itertools/more-itertools#532]
I hope I didn't overlook any already existing itertool that might cover this.

### Description
The iterator repeats each element of the passed iterable _n_ times.

### References
[https://stackoverflow.com/questions/24225072/repeating-elements-of-a-list-n-times](https://stackoverflow.com/questions/24225072/repeating-elements-of-a-list-n-times)

### Examples
I usually implement it a little differently from the version in the SO thread:

    def repeat_each(iterable, n=2):
        # repeat_each('ABC', 3) -> A A A B B B C C C
        return chain(*map(repeat, iterable, repeat(n)))

#### Possible variation
A possible variation of the above iterator would be incrementally repeated elements. However since there are probably only niche applications for this I didn't want to open a separate dedicated issue.

    def repeat_incrementally(iterable, start=1, step=1):
        # repeat_incrementally('ABC', 1, 3) -> A B B B B C C C C C C C
        return chain(*map(repeat, iterable, count(start, step)))

**Comment by bbayles** [comment]
Feel free to open a PR with your implementation - looks good!
