### ISSUE TITLE
`chunked` with chunks as even as possible

### ISSUE THREAD

**Issue by valtron** [more-itertools/more-itertools#535]
### Description

Like `chunked`, but the yielded lists all have lengths within 1 of each other.

### References

I've had to implement this before at least twice, but I don't remember the details... probably for some machine learning thing when I had to read data from a large file and I wanted to split it up into some other files, but I didn't want one of them to end up significantly smaller than the other. It's not hard to implement, but it would be nice to have in more-itertools.

### Examples

API could be either a new function or a flag to `chunked`, I'll pick new function arbitrarily:

```python
>>> list(chunked_even([1, 2, 3, 4, 5, 6, 7, 8], n = 4))
[[1, 2, 3, 4], [5, 6, 7, 8]]
>>> list(chunked_even([1, 2, 3, 4, 5, 6, 7, 8, 9], 4))
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
>>> list(chunked_even([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 4))
[[1, 2, 3, 4], [5, 6, 7], [8, 9, 10]]
```

It's similar to `divide`, except the second argument gives the desired number of elements per list, not the number of lists.

It can be implemented using `n^2` of temporary storage (since the last `n` lists might be affected when a new element is read).

**Comment by bbayles** [comment]
Thanks for the writeup. Afew questions to help me think about this:
* Is there some obvious proof that this is always possible? Can impossible cases be detected?
* `distribute` does something similar, but doesn't preserve order. Is that key to this?

**Comment by valtron** [comment]
The proof was a fun little puzzle :) The one I came up with is for a method that knows the length, so the lists it would produce might be different than the "online" version, but at least it shows it's always possible to divide it so all lists' lengths are within 1 of each other.

1. Let `N` = total length of the sequence, `n` the desired length of each list.
2. `L = ceil(N / n)`. `n' = N / L`.
3. Form sequence `0 n', 1 n', 2 n', ..., k n', ..., L n'`. The outputted lists are slices `seq[ceil(k n'):ceil((k+1) n')]` for `k` in `{0, ..., L - 1}`.
4. The length of some outputted list is given by `ceil((k+1) n') - ceil(k n')`. Decompose `n'` into integer and fractional parts, `n' = i + f`, and after some rewriting that gives the length to be `i + ceil(k f + f) - ceil(k f)`.
5. Since `f in [0, 1)`, `ceil(X + f)` is at most 1 greater than `ceil(X)`, so the lengths of the lists are `i + { 0, 1 }`.

---

Yeah, `distribute` is similar to `divide`. Both of them take as input the _number_ of lists to output, though, not the length the lists should be (`L` instead of `n` using the notation above).

For my use cases, I don't think the order ever mattered. It's also possible to implement it that way (rough algorithm: keep a list of `n` lists, fill up them up in order of (emptiest, earliest), and when the first list is full, emit it, add a new list to the end, and re-distribute the elements; not very efficient, though), but at that point it's quite different from `chunked`, which preserves order.

**Comment by bbayles** [comment]
I'm curious to know what the "online" implementation looks like.

Off the cuff, I would do something like what's in your proof: compute a list of sequence lengths and then fill them up. That requires O(n) space, since we need to know the sequence length?

**Comment by valtron** [comment]
Yeah, `O(N)`, but a problem with that method is that it won't work for infinite lists.

Here's a quick stab at the implementation of the online version. It does O(n) work on average per item, with O(n^2) space:

```
import math
from more_itertools import divide

def chunked_even(iterable, n):
	buffer = []
	for x in iterable:
		buffer.append(x)
		if len(buffer) == n*n: # Happens every 1/n items
			yield buffer[:n]
			buffer = buffer[n:] # O(n^2) time
	L = len(buffer)
	for l in divide(math.ceil(L/math.ceil(L/n)), buffer):
		yield list(l)

n = 3
for L in range(1, 20):
	print(list(chunked_even(range(1, L + 1), n)))

# [[1]]
# [[1], [2]]
# [[1], [2], [3]]
# [[1, 2], [3, 4]]
# [[1, 2], [3, 4], [5]]
# [[1, 2], [3, 4], [5, 6]]
# [[1, 2, 3], [4, 5], [6, 7]]
# [[1, 2, 3], [4, 5, 6], [7, 8]]
# [[1, 2, 3], [4, 5], [6, 7], [8, 9]]
# [[1, 2, 3], [4, 5, 6], [7, 8], [9, 10]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11]]
# [[1, 2, 3], [4, 5, 6], [7, 8], [9, 10], [11, 12]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11], [12, 13]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11], [12, 13], [14, 15]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14], [15, 16]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14], [15, 16], [17, 18]]
# [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17], [18, 19]]
```

**Comment by bbayles** [comment]
Suppose we restricted this to "iterables with a length", or at least ones we could `list()`-ify and get a length for. Can we avoid O(n^2) space? If so I think it's a worthwhile tradeoff.

**Comment by valtron** [comment]
Yep, it's possible to take advantage of `__len__` if defined to only use O(n) space. The implementation could do different things based on if that's available vs. if it's just a plain iterable. Note that `list()`-ifying would take it to O(N) space which is much worse than O(n^2). (Technically the space of the online algorithm is O(min(N, n^2)).)

**Comment by bbayles** [comment]
Ah, got it.

Go ahead and make a PR for your implementation? I'm happy to include this function if we can come up with a good name for it. `chunked_uniform`? `even_grouper`? `uniform_grouper`? But you can go ahead and write tests and type stubs.

Thanks!
