### ISSUE TITLE
Typing `chunked` with optional chunk size

### ISSUE THREAD

**Issue by PhilMacKay** [more-itertools/more-itertools#538]
I have been using `chunked` in my code base for a while including situations where the argument `n` has the value `None`.

We recently went over a round of typing improvement, and I noticed that the function `chunked` is typed as such:
`def chunked(iterable: Iterable[_T], n: int, strict: bool = ...) -> Iterator[List[_T]]: ...`

Since `chunked` uses `take`, which in turn uses `islice`, it could easily supports the signature `n: Optional[int]`. The only situation that requires a definite value is in the size test when `strict = True`.

Would it be possible to update the typing of the argument `n` from `n: int` to `n: Optional[int]`?
It would probably require to also add a condition like `if strict and n is not None: raise ValueError("n must not be None when strict is True")`.

It doesn't seem like a huge change to me, would there be other negative consequences I'm not thinking of?
I may be available to create a PR myself if needed :)

**Comment by bbayles** [comment]
Good suggestion - feel free to make a PR for this.
