### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by maffoo** [more-itertools/more-itertools#546]
Would it be possible to cut a new release of more-itertools? We're waiting in particular on the typing fix from https://github.com/more-itertools/more-itertools/pull/526. Given this is a typing change only, I'd assume this could be a new patch version, but not sure how you typically handle those.

Thanks for all your work on more-itertools!

**Comment by bbayles** [comment]
I will make a new release this week.

**Comment by maffoo** [comment]
That's great to hear. Thanks, @bbayles!
