### ISSUE TITLE
Enhancing `one`: Have a non-destructive too_long action instead of raising an exception

### ISSUE THREAD

**Issue by hwalinga** [more-itertools/more-itertools#552]
Sometimes you want to pick one item from the iterator, raise error if empty, and perform an additional action on too much items, but not raise an exception on too much and then lose the first value.

Like so:

```py
try:
    el = next(it)
except StopIteration:
    raise ValueError("no items")

try:
    next(it)
    log("too much items, picked arbitrary")
except StopIteration:
    pass  # this was expected

return el
```

There is no succint way to do that with more-itertools at the moment. You can improve the last try-block a bit at least:

```py
...
if peekable(it):
    log("too much items, picked arbitrary")
...
```

---

But I propose a personally more preferred enhancement to `one` that excepts a function on `too_long` it performs and still returns the first item, so no exception on `too_long`, but just performing the function, and still returning.

```py
import more_itertools as mi

...

el = mi.one(
    it,
    too_short=ValueError("no items"),
    too_long=lambda: log("too much items, picked arbitrary"),
)

return el
```

---

You could even allow a function on `too_short` if you add a way to provide a default.

```py
import more_itertools as mi

...

el = mi.one(
    it,
    too_short=lambda: log("not enough items, picked default"),
    default="a",
    too_long=lambda: log('too much items, picked arbitrary')
)

return el
```

---

I would be willing to make a PR if you think this is useful.

**Comment by bbayles** [comment]
Here's what I should have done: made the signature `one(iterable, too_short=ValueError, too_long=ValueError)`, and if the user passes in `None` for `too_short` or `too_long`, return instead of raising. But I didn't, and I'm not inclined to change the meaning of the arguments now. Sorry!

I've been waiting for someone to say "Hey, you have `one` for when the iterable is supposed to have a single item, but what about a generalization for `n` items?" So maybe that's where we could do it the right way?

**Comment by hwalinga** [comment]
Yes, we could make a `nth_exactly(iterable, n=1, default=None, too_short=ValueError, too_long=ValueError)` with the None-behaviour you describe. But what do you think about also accepting a function instead of a ValueError?

**Comment by bbayles** [comment]
Accepting a function: I think it's either provide an exception or provide a function. Since functions can raise exceptions, that's the more flexible option.

**Comment by hwalinga** [comment]
Ah, yes that is true. So would you accept a PR with a `nth_exactly(iterable, n=1, default=None, too_short=lambda: raise ValueError, too_long=lambda: raise ValueError)`

**Comment by bbayles** [comment]
Yeah, thanks! (I don't think you can `raise` in a `lambda`, FWIW).

**Comment by hwalinga** [comment]
>I don't think you can raise in a lambda, FWIW

Dang, you are right! I didn't know that. That's a bit annoying. How are we going to solve that, with a `raise_` function perhaps?

```py
def raise_(exp: Exception) -> None:
    raise Exception

def nth_exactly(iterable: Iterable, n: int = 1, default=None, too_short: Callable = raise_(ValueError), too_long=raise_(ValueError))
```

Or maybe just except both Exception type as function type to the `too_short` and `too_long` argument?

**Comment by bbayles** [comment]
Your snippet looks right - just a function is fine.

**Comment by hwalinga** [comment]
Not too convinced myself yet, so I wrote both. See what you think and what you like best. 

Other question I have, I wanted to include the information on the size of iterator in case it was too_short, but that comes with some small overhead. Don't know if I want to keep that.

**Comment by bbayles** [comment]
FYI - I didn't forget this, just haven't had time to review. I'll get to it - thanks for the PRs.

**Comment by bbayles** [comment]
Merged as `strictly_n` in https://github.com/more-itertools/more-itertools/commit/a89d4143883f81ff0d7299057ffae855aa303e78 . Thanks!
