### ISSUE TITLE
type annotation for zip_equal()

### ISSUE THREAD

**Issue by brianmaissy** [more-itertools/more-itertools#556]
I was wondering if we could improve to type annotations for the `zip_equal()` itertool so it preserves the type of each argument.

For example, if I do:
```
for number, letter in zip_equal([1, 2, 3], ['a', 'b', 'c']):
    ...
```
type-checkers will treat both `number` and `letter` as `Union[int, str]` or something like that, because they are typed with the same generic TypeVar.

As far as I know there isn't a way to solve this fully ([explanation](https://stackoverflow.com/a/56567144)), but we could at least make it handle the common case of a small number of arguments with overloads, [like they did](https://github.com/python/typeshed/blob/e4c2c0f3021abac1078854da92a9ec14848b32f4/stdlib/builtins.pyi#L1307) with `zip()` itself.

If this sounds ok I'm happy to open a PR.

**Comment by bbayles** [comment]
I'll grudgingly welcome a PR, but I'm mystified why we in the Python world thought that polluting our source files with this stuff was a good idea.

**Comment by brianmaissy** [comment]
Hmm just noticed that it looks like it's already like that, I'm just on 8.8.0 still 🤦‍♂️
