### ISSUE TITLE
strictly_n should be lazy - return an iterator with a length hint

### ISSUE THREAD

**Issue by SnirBroshi** [more-itertools/more-itertools#571]
The new `more_itertools.strictly_n` was suggested in #552 and implemented in #558 which is awesome, but it always consumes the `n` elements right-away and returns a list.

Instead, I think it should be lazy - return an iterator (optimally with a length hint, #510), yielding elements as usual, but if the given iterator ends prematurely raise `too_short`, and if we got to the `n`th element and there are more, raise `too_long`.

### Example
```py
>>> items = 'abcdefg'
>>> for item in strictly_n(items, 5):
...     print('Item', item)
Item a
Item b
Item c
Item d
Item e
ValueError: too many items in iterable (got at least 6)
```

I'm not sure whether the error should be thrown before or after the nth element is yielded.

The current behavior can then be achieved by calling `list()` on the returned iterator.

### Real world use case

I used a REST API to query a long list of items. This API used pagination - each request gave me a few items and a token to pass in the next request to get the next few items, and so on. The API also told me the total number of items.

The pagination was pretty weird, it sometimes repeated items, so I wanted to make sure I got all the items correctly, but I didn't want to wait to get all the items to start processing them, as it would take a long time and also each item was pretty big so I didn't want them all in memory at the same time.

I wrote the following:

```py
class ExplicitLengthIterable:
    def __init__(self, iterable, length):
        self.iterable = iterable
        self.length = length
    def __len__(self):
        return self.length
    def __iter__(self):
        iterator = iter(self.iterable)
        for i, value in zip(itertools.count(0), iterator):
            if i >= self.length:
                raise Exception('Iterable was longer than promised')
            yield value
        if i + 1 != self.length:
            raise Exception('Iterable was shorter than promised')
```

(I needed an iterable with `__len__` rather than an iterator with `__length_hint__`, but iterator is more generic and can be wrapped later)

---

Tagging @hwalinga since they might be interested.

**Comment by NotWearingPants** [comment]
@bbayles What is the benefit of collecting the items to pass to these, why not just the amount of items?

So will a kwarg called `keep_items_for_callbacks=True` do it?

Note that both `more_itertools.one()` and `more_itertools.only()` do not pass any information to the `too_short` and `too_long` callbacks.
