### ISSUE TITLE
Docs are appearing without styling on readthedocs

### ISSUE THREAD

**Issue by spookylukey** [more-itertools/more-itertools#580]
See https://more-itertools.readthedocs.io/en/stable/

Some older versions of the docs still have styling e.g. https://more-itertools.readthedocs.io/en/v8.10.0/

The `stable` version seems to be missing `<link rel="stylesheet" href="_static/css/theme.css" type="text/css" />` and other bits in the HTML.

**Comment by norweeg** [comment]
hope this is fixed soon! Its really hard to read the docs like this....

**Comment by astrojuanlu** [comment]
I see that @bbayles added this https://github.com/more-itertools/more-itertools/blob/master/docs/requirements.txt 10 days ago, which got `sphinx-rtd-theme==1.0.0` installed. Perhaps `html_context` is handled differently in that version?

https://github.com/more-itertools/more-itertools/blob/1ede288d19c2d47ddae8a14a2dc8f314cb925f90/docs/conf.py#L152-L155

This override is related to https://github.com/readthedocs/sphinx_rtd_theme/issues/1179 by the way.

@nienn @agjohnson thoughts?

**Comment by bbayles** [comment]
I swear this was working when I added the requirements thing...

**Comment by bbayles** [comment]
I think c693e20c5a8dcd480e3beaaf6d0218a5b5a2218a fixes this. I had to force reload the RTD page.

**Comment by astrojuanlu** [comment]
Looks fixed to me too. Feel free to open an issue upstream, we can take a look.
