### ISSUE TITLE
Generating all subsets with sum at most S

### ISSUE THREAD

**Issue by erelsgl** [more-itertools/more-itertools#585]
### Description
Given a list L of integers and a constant S, generate all subsets of L in which the sum is at most S.

This can be done using powerset:

    for subset in powerset(L):
        if sum(subset) <= S:
            yield subset

But it might be very wasteful, since the number of subsets may be very large, and only a small number of them have a sum of at most S. 

### References
I am interested in variants of the [subset sum problem](https://en.wikipedia.org/wiki/Subset_sum_problem) and [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem). You can see in Wikipedia its various applications. 

### Examples

     >>> list(subsets_with_sum([1,2,3,4,5], 7)
     [ (), (1,), (2,), (3,), (4,), (5,), (1,2), (1,3), (1,4), (1,5), (2,3), (2,4), (2,5), (3,4), (1,2,3), (1,2,4) ]

**Comment by bbayles** [comment]
Thanks for the suggestion. This is probably better suited to a different library, however.

**Comment by erelsgl** [comment]
It can be generalized: generate all subsets of L which satisfy a given condition.
