### ISSUE TITLE
Add `mark_last` itertool

### ISSUE THREAD

**Issue by ktbarrett** [more-itertools/more-itertools#589]
### Description
`mark_last` would take an iterator, and return the iterator zipped with a boolean flag that is `True` only on the last element in the iterator.

### References
I have, at least twice in memory, needed such a tool. Once for generating a "last" flag for an AXI4-Full Transaction modeled in Python. Currently for preventing the production of a trailing comma in an collection serializer.

### Examples
```python
def mark_last(__iterable: Iterable[T]) -> Iterator[Tuple[T, bool]]:
    sentinel = object()
    it = iter(__iterable)
    prev_v = next(it, sentinel)
    if prev_v is sentinel:
        return
    while True:
        v = next(it, sentinel)
        if v is sentinel:
            yield prev_v, True
            return
        else:
            yield prev_v, False
            prev_v = v

@serialize.register
def _(value: list) -> None:
    s = ["["]
    for v, last in mark_list(value):
        s.append(serialize(v))
        if not last:
            s.append(",")
    s.append("]")
    return "".join(s)
```

**Comment by bbayles** [comment]
Does [mark_ends](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.mark_ends) scratch this itch?

**Comment by ktbarrett** [comment]
Gah, I'm blind. Thank you.
