### ISSUE TITLE
New option: extracting only iterables using more_itertools.collapse()

### ISSUE THREAD

**Issue by meh-wzdech** [more-itertools/more-itertools#592]
My two questions from StackOverflow ([1](https://codereview.stackexchange.com/questions/270323/counting-absolute-nesting-levels-of-an-iterable/), [2](https://codereview.stackexchange.com/questions/270386/getting-values-from-a-given-level-of-a-nested-collection/)) inspired me to add this pull request.

So far more_itertools.collapse() has returned flattened values from given level **without popping non-iterable values**. The feature to determine if one would like to get only iterables too could be helpful.

Example:
```
>>> iterable = [('a', ['b']), ('c', ['d'])]

>>> list(collapse(iterable, levels=2)) # Current result according to docs

['a', 'b', 'c', 'd']

>>> list(collapse(iterable, levels=2, only_iters=True) # Hypothetical option

['b', 'd']
```

**Comment by bbayles** [comment]
Apologies for the delay. I'm not inclined to add something like this, but as usual I could be persuaded if there were some in-the-wild examples of people solving this problem.
