### ISSUE TITLE
Please consider switching to flit_core

### ISSUE THREAD

**Issue by mgorny** [more-itertools/more-itertools#593]
I'm the @Gentoo maintainer for core Python packages. We're currently considering options for bootstrapping setuptools while unvendoring its dependencies in the PEP 517 world. One of the interesting options is to use [flit](https://flit.readthedocs.io/en/latest/) as it has much fewer dependencies than setuptools and we've got its bootstrap trivially covered.

Using flit as more-itertools' build system would mean that we can cleanly install it before building setuptools. Flit can also generate a backwards-compatible `setup.py` (or be used alongside `setup.py`, though for this to work for us `pyproject.toml` would have to specify flit_core as the `build-backend`). FWICS it is becoming increasingly popular these days.

Would you be interested in this? If yes, then I can prepare a PR either converting the project to flit entirely, or adding it alongside existing `setup.py`, as you prefer.

**Comment by bbayles** [comment]
I'm open to reviewing a PR that switches to `flit` with a generated `setup.py`. Thanks for the suggestion.

A consideration for me is: being able to use something like [`twine check`](https://github.com/more-itertools/more-itertools/blob/c57021716aecf0f8da2e452349fcaa269a203177/.github/workflows/python-app.yml#L53) on what would be uploaded to PyPI.

**Comment by mgorny** [comment]
I'm sorry, I haven't originally noticed that you're combining `README.rst` with data from `docs/versions.rst`. I don't think that's possible with flit, and I can't think of a satisfactory replacement for that.

I guess you don't want to give that up, so the only alternative I see is using `flit_core` as the "default" user-facing build system while keeping original `setup.py` for publishing purposes + users who prefer it.

Of course, I'm not going to insist on this. I understand that in the end a particular build system is your choice.

**Comment by bbayles** [comment]
I would settle for linking to the version history in the PyPI readme.
