### ISSUE TITLE
Confusing phrasing in documentation

### ISSUE THREAD

**Issue by plazer1** [more-itertools/more-itertools#601]
The [description for `distribute`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.distribute) says:

> This function uses `itertools.tee()` and may require significant storage. If you need the order items in the smaller iterables to match the original iterable, see [`divide()`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.divide).

(The phrasing is somewhat ambiguous, and a possible interpretation of this is that `divide` does not require significant storage.)

In the [description for `divide`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.divide), we have:

> This function will exhaust the iterable before returning and may require significant storage. If order is not important, see [`distribute()`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.distribute), which does not first pull the iterable into memory.

This seems to contradict the former statement that `distribute` may require significant storage.
(Also, instead of merely saying that it _exhausts_ the iterable and _may_ require significant memory, why not simply say it converts the entire iterable to a tuple up-front? That would be both simpler and more precise. But anyway, that is not the complaint I'm making here.)

I don't know much about the internals of `itertools.tee`, but I think -- correct me if I'm wrong -- that the current implementation of `distribute` can in the worst case consume at least as much space as `divide`. Namely, if you exhaust the last of the returned iterables completely and leave others untouched, then no possible optimization could avoid having all elements in memory at once in that case.

So, my suggestion is to make it clear in the docstring of each of the two mentioned functions, that the other function is _not_ significantly more memory-efficient. The current phrasing seems to imply that each is more (or also less) efficient than the other.

**Comment by bbayles** [comment]
If I put a linebreak between the two sentences in the description for `divide()`, would that be clearer to you? They are separate thoughts, but I can see how they look to be connected currently.

**Comment by plazer1** [comment]
That would be better, but there's still 
> If order is not important, see [distribute()](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.distribute), which does not first pull the iterable into memory.

This reads like "`distribute` has strictly better space complexity" which is not true. I'd say something along the lines of "`distribute` reads the iterable into memory right away, whereas `divide` only does so on-demand, but in the worst case could still keep the entire iterable in memory". Again, I don't know exactly how `tee` works -- whether it discards old values which were already consumed by all iterables. But as I said, in the worst case, it can keep the whole iterable in memory.
