### ISSUE TITLE
merge_sorted

### ISSUE THREAD

**Issue by tzot** [more-itertools/more-itertools#604]
### Description
`merge_sorted(*iterables, key=None)`

Assuming the iterables are already sorted (`key` functions exactly like in `itertools.groupby`), it outputs single ordered stream.

### References

I used it for tuples coming from several database cursors with different contents in general but the first tuple item was the sort key, and I needed to do a itertools.groupby without storing all the data in memory: `for item in merge_sorted(cursor1, cursor2, cursor3, key=operator.itemgetter(0)):`

### Examples

Sample functioning unoptimized implementation (I can make a branch and create a pull request if you think it's useful; unless there was already a combination of tools that I missed, of course :) )

```python
def identity(x):
    return x

def merge_sorted(*iterables, key=identity):
    buffer = []
    last = [Ellipsis] * len(iterables)
    iterables = [izip(itertools.repeat(i), iterable) for i, iterable in enumerate(iterables)]

    for i, item in more_itertools.roundrobin(*iterables):
        item_key = key(item)

        heapq.heappush(buffer, (item_key, item))
        last[i] = item_key

        while buffer[0][0] not in last:
            yield heapq.heappop(buffer)[1]

    # yield the remaining
    while buffer:
        yield heapq.heappop(buffer)[1]

```

**Comment by bbayles** [comment]
Hmm, could you tell me why `heapq.merge` wouldn't be preferable?

**Comment by tzot** [comment]
Because it was the tool that I missed! :slightly_frowning_face:
Sorry for the trouble; I had a vague recollection of sometime this functionality appearing in a python release, but it completely escaped me where to look (I was looking at itertools).
Thanks for your time!
