### ISSUE TITLE
A demultiplexor itertool

### ISSUE THREAD

**Issue by OhMajesticLama** [more-itertools/more-itertools#605]
### Description
A demultiplexer iterator, that is a generalization of the *partition* recipe to split an iterator between *n* output iterators - instead of being limited to 2.

### References
Use cases are similar to the *partition* itertool recipe: data flow coming from one iterator needs to be split so that values from the data flow can go through different pipelines depending on arbitrary criteria by user.
The original use case that triggered this proposal is coming from data loading from a CSV file that needed to be split and pushed through different workflows depending on criteria of each row.

The same result could be achieved through repetitive use of the *partition* recipe or duplication of inputs through the *tee* itertools and several *filter*.

### Examples

Example with numbers.
```python
>>> out0, out1, out2 = demux(lambda v: (v % 3), range(13), 3)
>>> print(list(out0))
[0, 3, 6, 9, 12]
>>> print(list(out1))
[1, 4, 7, 10]
>>> print(list(out2))
[2, 5, 8, 11]

# If *function* returns a value that's out of range (e.g. < 0 or >= n), value is filtered out.
>>> out0, out1 = demux(lambda v: -1, range(20))
>>> print(list(out0))
[]
>>> print(list(out1))
[]
```

Example implementation: https://github.com/OhMajesticLama/more-itertools/commit/53f8ac96a93838e47bdd06ecfec6fedad14d4e7c

Use case with rows
```python
>>> rows = [
... {'type': 'a', 'value': 45},
... {'type': 'b', 'value': 44},
... {'type': 'c': 'value': 43},
... ]
...
>>> out_a, out_b, out_c = demux(lambda r: {'a': 0, 'b': 1, 'c': 2}[r['type']], rows, 3)
>>> print(list(out_a))
[{'type': 'a', 'value': 45}]
>>> print(list(out_b))
[{'type': 'b', 'value': 44}]
>>> print(list(out_c))
[{'type': 'c', 'value': 43}]
```

**Comment by bbayles** [comment]
Does [bucket](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.bucket) scratch this itch?
