### ISSUE TITLE
[Question] Split a group of cards between N players

### ISSUE THREAD

**Issue by Vini-002** [more-itertools/more-itertools#611]
I want to generate all the possible ways a group of cards can be distributed between N players.

From the progress I've made so far, the function I want is similar to combinations, but doesn't return a single group and instead generates the combinations of the remaining cards for the second player, and the remaining cards from that to the third player and so on...

I imagine this function as a recursive generator using the combinations functions, but couldn't implement it.

Does this function already exists here?

**Comment by bbayles** [comment]
How about using `itertools.permutations` and splitting each permutation into N pieces?

Suppose there are 3 players and each one gets 5 cards. Use `r=15` for the call to `permutations`.

**Comment by Vini-002** [comment]
I did that, it's much simpler but much less efficient and my code wouldn't run on reasonable time.
In this example with 3 players and 15 cards, permutations will consider `(5!)^3` times more possibilities, as on my problem the order the players receive the card don't matter.

**Comment by Vini-002** [comment]
Thank you! It has the function I need!
