### ISSUE TITLE
Proposal for new itertool `max_zip`

### ISSUE THREAD

**Issue by effting** [more-itertools/more-itertools#613]
### Description
I had the need for a simple function to return both the maximum value of an expensive function and the argument for which this maximum was achieved.

Consider the following example where `func(x)` is evaluated twice:
```
iterable = range(10)
x = max(iterable, key=func)
y = func(x)
```

### Examples
Implementation would look like this:
```
import operator


def func(x):
    return (10 - x) * x


def max_zip(iterable, key):
    return max(((key(item), item) for item in iterable), key=operator.itemgetter(0))


iterable = range(10)
y, x = max_zip(iterable, func)   # returns `y = 25` and `x = 5`
```

**Comment by bbayles** [comment]
Apologies for the delay in responding. I think this is a good idea, though of course somebody will then want a `min` version.

I will accept a PR for a function that can do both. Thanks for the suggestion!

**Comment by rhettinger** [comment]
> Consider the following example where func(x) is evaluated twice:

Actually, it is evaluated eleven times.  So, the actual time savings for the expensive function in negligible.

FWIW, the usual one-way-to-do-it solution for a avoiding expensive function recomputation is to use `functools.cache` or `functools.lru_cache`.

**Comment by gliptak** [comment]
what might be a backward compatible update here?

https://github.com/more-itertools/more-itertools/blob/master/more_itertools/more.py#L4403

**Comment by james-wasson** [comment]
You can do this with a one liner using the `minmax` method:
```python
from operator import itemgetter
from more_itertools import minmax
values = [5, 30]
get_key = str

result = minmax(((get_key(v), v) for v in values), key=itemgetter(0))

print(result)
```
=>
```
(('30', 30), ('5', 5))
```

This outputs a tuple of `((min_key, min_value), (max_key, max_value))`

@bbayles  I can make a PR with a docstring change or make a new function. Thoughts here?
