### ISSUE TITLE
About citations

### ISSUE THREAD

**Issue by juanjq** [more-itertools/more-itertools#614]
Hi!,

I'm in a project and I'm using this tools, to be specific I'm using `set_partitions`, and is being very useful. I want to cite this work properly because is being helpful. 

What way of citing the work would you recommend me?  Because I didn't find any official reference, manual or anything like this.
Thanks!

**Comment by bbayles** [comment]
I would probably do something like this:

```
More Itertools Project (2011) more-itertools source code (Version 8.13.0) [Source code]. https://github.com/more-itertools/more-itertools
```
