### ISSUE TITLE
set_partitions ignoring duplicates

### ISSUE THREAD

**Issue by boomboomjassi** [more-itertools/more-itertools#616]
### Description
Configure set_partitions to ignore duplicates whenever there is a repeat element

### References
`set_partitions` works fine when all the element in the source list/iterator are distinct. But whenever there is a repeat it generates redundant sets.

### Examples
```
lst = [2, 2,  3, 5]
pp.pprint(list(mit.set_partitions(lst, 2)))
[[[2], [2, 3, 5]],
 [[2, 2], [3, 5]],
 [[2], [2, 3, 5]],
 [[2, 2, 3], [5]],
 [[2, 3], [2, 5]],
 [[2, 3], [2, 5]],
 [[3], [2, 2, 5]]]
```
As we can see row 0 and row 2(zero indexed) are identical  ie `[[2], [2, 3, 5]],`
`set_partitions` needs an argument to ignore duplicates. Don't you think so?

**Comment by bbayles** [comment]
This is in line with what `itertools.combinations` and `itertools.permutations` do. Is it a problem for some application?

**Comment by boomboomjassi** [comment]
I don't quite get how can I achieve the same using `itertools.combinations` and `itertools.permutations`.
Maybe if you can help me out with a code snippet using `itertols.combinations` and `itertools.permutations` it would be great.

Just to reiterate my problem again to avoid any confusion, basically all I need is 
```
[[[2], [2, 3, 5]],
 [[2, 2], [3, 5]],
 [[2, 2, 3], [5]],
 [[2, 3], [2, 5]],
 [[3], [2, 2, 5]]]
```
instead of 
```
[[[2], [2, 3, 5]],
 [[2, 2], [3, 5]],
 [[2], [2, 3, 5]],
 [[2, 2, 3], [5]],
 [[2, 3], [2, 5]],
 [[2, 3], [2, 5]],
 [[3], [2, 2, 5]]]
```
My original requirement was simple **Partition a given list of numbers into two or more unordered sets**. Which essentially means neither the order of sets matter nor is the order of elements within any set. Here is the original [stackoverflow question](https://stackoverflow.com/questions/72334282/partition-a-given-list-into-two-or-more-unordered-sets/72348893#72348893) where I do for all K=1 to len(lst).

**Comment by bbayles** [comment]
I meant that `itertools.permutations` and `itertools.combinations` treat duplicate elements the same way; they are represented in the output the same way as they are in `set_partitions`.

I would accept a PR that made treating duplicates differently with an option, but I don't have the bandwidth to write one myself at the moment.

**Comment by JamesParrott** [comment]
Hi everyone.  
I've been looking into this.  Something approaching the state of the art of multiset partitioning can rapidly get quite complicated.  But there is a version in sympy:

https://github.com/sympy/sympy/blob/26f7bdbe3f860e7b4492e102edec2d6b429b5aaf/sympy/utilities/iterables.py#L1447
https://github.com/sympy/sympy/blob/26f7bdbe3f860e7b4492e102edec2d6b429b5aaf/sympy/utilities/enumerative.py#L146

Sympy's helpful comments explain how one of Knuth's algorithms was adapted:

# 7.1.2.5M in Volume 4A, Combinatoral Algorithms, Part 1, of The Art
# of Computer Programming, by Donald Knuth.

**Comment by bbayles** [comment]
After #856, I'd rather not introduce more complexity to `set_partitions`.
