### ISSUE TITLE
repeat_each is missing in the front page table

### ISSUE THREAD

**Issue by pochmann** [more-itertools/more-itertools#617]
[`repeat_each`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.repeat_each) is missing in the [front page](https://more-itertools.readthedocs.io/en/stable/index.html) table.

**Comment by pochmann** [comment]
[`chunked_even`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.chunked_even) is missing, too. Didn't check further.

**Comment by bbayles** [comment]
Thanks!

**Comment by pochmann** [comment]
I think it was indeed fixed, but by now they're missing [there](https://more-itertools.readthedocs.io/en/stable/) again. Even though they are in the file [here](https://github.com/more-itertools/more-itertools/blob/master/README.rst) at GitHub.
