### ISSUE TITLE
Proposal of new incomplete mode for grouper

### ISSUE THREAD

**Issue by cbscsm** [more-itertools/more-itertools#619]
### Description

I think about fourth incomplete mode of `more-itertools.grouper`.
I call it `'allow'` mode, but I'm not sure about the name. So I will glad for suggestions.
Against 'ignore' or 'fill' mode, this mode allows the last group as incomplete.

### References

In some cases, I need just partitioning of flat iterables.
For example, printing sequence of data, 5 values for each line.
```python
data = list(range(12))

for i, value in enumerate(data):
    print(value, end=' ')
    if i % 5 == 4:
        print()
```
I think it is complicated with index over its simple purpose.
Also it is based on side effect of function `print`.
So if I need a pure function, I should make one.
But I think it is very similar with what `more_itertools.grouper` does.

### Examples

```python
from more_itertools import gouper

data = list(range(12))

print(
    '\n'.join(
        ', '.join(map(str, row))
        for row in grouper(data, 5, incomplete='allow')
    )
)
```
output:
```
0, 1, 2, 3, 4
5, 6, 7, 8, 9
10, 11
```

**Comment by bbayles** [comment]
Do we need this, given that we have `chunked`?

```
In [4]: from more_itertools import chunked
   ...:
   ...: data = list(range(12))
   ...:
   ...: print(
   ...:     '\n'.join(
   ...:         ', '.join(map(str, row))
   ...:         for row in chunked(data, 5)
   ...:     )
   ...: )
0, 1, 2, 3, 4
5, 6, 7, 8, 9
10, 11
```

**Comment by cbscsm** [comment]
Oh, I had not known about `chunked`. I'll close this issue.
