### ISSUE TITLE
lookahead

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [more-itertools/more-itertools#621]
### Description

It seems to me that [Ferdinand Beyer](https://stackoverflow.com/users/34855/ferdinand-beyer)'s [`lookahead`](https://stackoverflow.com/a/1630350/2531987) would make a good contribution to 'Lookahead and loopback' section:

```python
def lookahead(iterable):
    """Pass through all values from the given iterable, augmented by the
    information if there are more values to come after the current one
    (True), or if it is the last value (False).
    """
    # Get an iterator and pull the first value.
    it = iter(iterable)
    last = next(it)
    # Run the iterator to exhaustion (starting from the second value).
    for val in it:
        # Report the *previous* value (more to come).
        yield last, True
        last = val
    # Report the last value.
    yield last, False
```

I'm not sure the name `lookahead` would be the best candidate though. Maybe `has_more`. Also, maybe the order of the output should be changes to `for more, element in has_more(iterator): ...` to match `enumerate`?
### References
 - https://stackoverflow.com/questions/1630320/what-is-the-pythonic-way-to-detect-the-last-element-in-a-for-loop

### Examples

```python
def print_table(names, table, width=10):
    """ Print a small table of values """
    names = [name[:(width - 1)] for name in names] # trim names to width
    for name, more in lookahead(names):
        print(name.ljust(width), end='| ' if more else "\n")
    for name, more in lookahead(names):
        print("-"*width, end="--" if more else "\n")

    for row in table:
        for value, more in lookahead(row):
            print(f"{value:.3f}".ljust(width), end='| ' if more else "\n")

names = ["alpha", "beta", "gamma", "delta"]
table = [
    [0.0, 1.0, 0.8, 0.4],
    [1.0, 0.0, 0.3, 0.1],
    [0.8, 0.3, 0.0, 0.9],
    [0.4, 0.1, 0.9, 0.0],
]

print_table(names, table)
```

**Comment by MarcinKonowalczyk** [comment]
maybe a more extended functionality which encompasses this behaviour would be to have a `spyable()` iterator which yields elements normally, but in as opposed to a boolean flag it yields the next element? i guess then it's very similar (if not identical) to `windowed`...

**Comment by bbayles** [comment]
Does [mark_ends](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.mark_ends) scratch this itch?
