### ISSUE TITLE
Proposal: tri-partition

### ISSUE THREAD

**Issue by ckp95** [more-itertools/more-itertools#622]
### Description

(Couldn't think of a better name for this, alternatives welcome)

Takes an iterable of `T` and a predicate and returns a 3-tuple of `list[T], list[T], Iterator[T]`.

The first list is all items before the predicate is true. The second list is a single element for which the predicate is true, or an empty list if no such element is found. The iterator yields the remaining elements.

### Rationale

This is supposed to be analogous to the `str.partition` method. That method takes a string to be partitioned, and a separator, and returns a 3-tuple of strings. The first element is everything before the separator, the second element is the first occurrence of the separator, and the third element is everything after the separator (possibly including more occurrences of the separator). It's basically like `str.split` but only for the first occurrence.

If the separator is not found, the first element is the entire string, and the remaining two elements are empty strings.

If the separator is found right at the start, the first element is the empty string, the second element is the separator, and the third element is the remainder.

The `str.partition` method satisfies the property that `foo == "".join(foo.partition(bar))` for any value of `foo` or `bar`. The `more-itertools` version should obey the equivalent invariant: iterating over `foo` should yield the same values as iterating over `itertools.chain(*tri_partition(foo, lambda x: ...))`.

### Examples

```
numbers = range(10)
a, b, c = tri_partition(numbers, lambda x: x == 4)
print(a) # [0, 1, 2, 3]
print(b) # [4]
print(list(c)) # [5, 6, 7, 8, 9]
```

```
numbers = range(10)
a, b, c = tri_partition(numbers, lambda x: x > 12)
print(a) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(b) # []
print(list(c)) # []
```

```
numbers = range(10)
a, b, c = tri_partition(numbers, lambda x: x == 0)
print(a) # []
print(b) # [0]
print(list(c)) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

### Use cases

This would be useful for general iterables in the same situations as `str.partition` is useful for strings. An example could be: a newline-separated text file containing a small amount of header information, some kind of separator to delimit the two sections of the file, and a larger amount of lines of data, like this:

```
HEADER GOES HERE
MORE HEADER STUFF
---
MAIN DATA GOES HERE
MORE DATA
EVEN MORE DATA ...
etc
```

With `tri_partition` we can do this:

```
with open(filename, "r") as f:
    header, _, data = tri_partition(f, lambda x: x == "---\n")
    ... # processing goes here
```

### Implementation

```
def tri_partition(it: Iterable[T], pred: Callable[[T], bool]) -> tuple[list[T], list[T], Iterator[T]]:
    it = iter(it)
    head_list = []
    sep_list = []

    for x in it:
        if not pred(x):
            head_list.append(x)
        else:
            sep_list.append(x)
            break

    return head_list, sep_list, it
```

### Remarks

This could also be implemented so that the first two elements are iterators too, rather than lists. But that would be a little more complicated.

**Comment by bbayles** [comment]
Thanks for the suggestion.

I actually had something like this in mind with `split_at`. Maybe you can use that?

```python
>>> list(split_at('mississippi', lambda x: x == 's', maxsplit=1, keep_separator=True))
1: [['m', 'i'], ['s'], ['s', 'i', 's', 's', 'i', 'p', 'p', 'i']]

>>> 'mississippi'.partition('s')
2: ('mi', 's', 'sissippi')
```

**Comment by ckp95** [comment]
Oh, I didn't know you could do that. It isn't quite the same though; `split_at` is eager, whereas the remainder in mine is lazy.

**Comment by bbayles** [comment]
I think your proposal overlaps enough that I'd consider it a duplicate, but let me know if there's some use case that won't work (a StackOverflow or GitHub reference of people trying to work around this problem is usually a good sign)

**Comment by ckp95** [comment]
Sure. Maybe your code snippet could just be added as a note to the docs for `split_at`? I originally ctrl-f'd for "partition" to see if there was anything that behaved like `str.partition` and concluded there wasn't.

**Comment by bbayles** [comment]
I think `before_and_after` might be most appropriate for your "read until the header is done, then lazily iterate across the rest of the items" task?
