### ISSUE TITLE
`iter_join` = a function for iterables which is `join` for strings

### ISSUE THREAD

**Issue by sassbalint** [more-itertools/more-itertools#625]
### Description
`iter_join` = a function for iterables which is `join` for strings.

### References
Does `more-itertools` have such a functionality? I think it would be useful. A very general pattern.

For example when reading a file line by line and generating a valid JSON from it, there should be a comma _between_ JSON-snippets generated from lines but _not after_ teh last one.

### Examples
Code could be something like:
```python
def iter_join(iterable, separator):
    """Join iterable's elements like str join() does."""
    yield next(iterable)
    for item in iterable:
      yield separator
      yield item
```

**Comment by fsabre** [comment]
There is ! https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.intersperse

**Comment by sassbalint** [comment]
> There is ! https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.intersperse

Thanks! Sorry, I was not aware.

I close this issue.
