### ISSUE TITLE
Proposal: `iequals` function

### ISSUE THREAD

**Issue by nanouasyn** [more-itertools/more-itertools#628]
### Description

New function `iequals` that checks whether two iterables consist of the same elements. This is useful when comparing sequences of different data types or iterators, because we can't use the `==` operator. In such cases, it is necessary to convert sequences to the same data type, which requires extra memory and performance costs. We can use this function, for example, in tests, so as not to convert the iterator into a list for comparison with the expected result.

### References

https://stackoverflow.com/questions/900420/elegant-way-to-compare-sequences

### Examples

```python
>>> iequals(map(abs, [-1, 2, -3, 4]), [1, 2, 3, 4])
True

>>> iequals(longest_common_prefix(['ab', 'abc', 'abd']), 'ab')
True

>>> string = 'step on no pets'
>>> iequals(string, reversed(string))
True
```

### Name
The letter "i" in the function name emphasizes that this function handles the given iterables as iterables, ignoring type differences. Perhaps we should use the `ieq` name so that the function name refers to `operator.eq`, but I'm not sure that a three-letter name based on two abbreviations would be understandable. Maybe, we can use the the name `elementwise_equals`, which may be more understandable, but my knowledge of English is not enough to determine whether this is a good name. Вesides, this name seems too long.

**Comment by bbayles** [comment]
Is this different from [all_equal](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.all_equal)?

**Comment by nanouasyn** [comment]
`all_equal` checks whether all elements of the sequence are equal to each other, `iequals` will check whether two iterables are equal element by element.

**Comment by bbayles** [comment]
Oh, thanks - apologies; I should have read more carefully.

I will accept a PR that does something like:

```python
return all(a == b for a, b in izip_longest(iterable_1, iterable_2))
```

Or for bonus points:
```python
return all(all(x == t[0] for x in t) for t in zip_longest(*iterables))
```
