### ISSUE TITLE
`__getitem__` into nested collections, à la Ruby's dig()

### ISSUE THREAD

**Issue by Kache** [more-itertools/more-itertools#638]
### Description

A Python version of Ruby's `dig()` methods for [Array](https://ruby-doc.org/core-3.1.1/Array.html#method-i-dig) and [Hash](https://ruby-doc.org/core-3.1.1/Hash.html#method-i-dig), which is useful for navigating unstructured JSON.

### References

Would be pretty easy to find messy code handling for keys etc around parsing JSON.

### Examples

```py
def dig(collection, *keys):
    """Dig into nested subscriptable objects, e.g. dict and list, i.e JSON.

    Examples:

    >>> nested_dict = {'a': {'b': 1}, 'c': [2, 3]}
    >>> dig(nested_dict, 'a', 'b')
    1
    >>> dig(nested_dict, 'a', 'x', 'y') is None
    True

    >>> nested_list = [{'a': 3}, {'a': 4, 'b': 5}]
    >>> dig(nested_list, 0, 'a')
    3
    >>> dig(nested_list, 0, 'b') is None
    True
    """
    curr = collection
    for k in keys:
        if curr is None:
            break

        if not hasattr(curr, '__getitem__') or isinstance(curr, str):
            raise TypeError(f'cannot dig into {type(curr)}')

        try:
            curr = curr[k]
        except (KeyError, IndexError):
            curr = None

    return curr
```

**Comment by nanouasyn** [comment]
This is similar to the `get_in` function from toolz library, and this is a useful function. But more-itertools is designed to operate with iterators, not with sequences and mappings. And all other functions of this library do not require iterable to be anything other than iterable. Therefore, I think in the spirit of this library there would be something like this:

```python
def dig(iterable, *indexes):
    for index in indexes:
        iterable = nth(iterable, index)
    return iterable
```

But it looks significantly less useful. Let's see what @bbayles has to say, but, in my humble opinion, this function does not fit into more-itertools.

**Comment by bbayles** [comment]
I would point anybody look for this sort of thing to `jmespath`.
