### ISSUE TITLE
more_itertools.batched is obsolete in Python 3.12

### ISSUE THREAD

**Issue by neutrinoceros** [more-itertools/more-itertools#652]
Python 3.12 just gained a new function, `itertools.batched`, which I think makes `more_itertools.sliced` obsolete, see
https://github.com/python/cpython/issues/98363

I wanted to give you guys a headsup, since there is a precedent in `more_itertools.zip_equal` being made obsolete in Python 3.10 and deprecated since then.
I'd be happy to contribute a patch too if you'd like.

**Comment by bbayles** [comment]
It definitely obsoletes `more_itertools.batched`, but I think it's closer to `more_itertools.chunked` than `more_itertools.sliced`.

I'll accept a PR that deprecates `more_itertools.batched` for 3.12+. `more_itertools.chunked` has additional features.

**Comment by neutrinoceros** [comment]
(I edited the title for future reference, but left the original description)

**Comment by gsakkis** [comment]
> I'll accept a PR that deprecates more_itertools.batched for 3.12+. more_itertools.chunked has additional features.

Just landed in this issue while trying to figure out the difference between `batched` and `chunked`. @bbayles what are the additional features of `chunked`? AFAICT the only difference is one returns chunks as lists and other as tuples. What am I missing?

**Comment by JamesParrott** [comment]
Chunked doesn't require `strict` to be a kwarg; batch does.  

Did [batched](https://docs.python.org/3/library/itertools.html#itertools.batched)  become otherwise equivalent to [chunked](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.chunked) in Python 3.13?

**Comment by bbayles** [comment]
Yeah, the `strict` option makes them more or less the same.

`chunked` is used widely, so at least the function name isn't going anywhere - after everything prior to 3.13 is EOL, I may alias it to that.
