### ISSUE TITLE
Add `iter_with` as mirror/companion utility to `with_iter`

### ISSUE THREAD

**Issue by the-wondersmith** [more-itertools/more-itertools#660]
### Description
Utility adds the "flip side" of the existing `with_iter`, namely `iter_with`, allowing any `Iterator` to be used in a `with` statement.

### References
I've used the *actual* code below in multiple situations to help streamline / clean up sections of code that otherwise would be unnecessarily allocation heavy or just... uglier 😅.

### Implementation
```python
from contextlib import contextmanager
from typing import TypeVar, Iterable, Generator

T = TypeVar("T")

@contextmanager
def iter_with(obj: Iterable[T]) -> Generator[Iterator[T], None, None]:
    """Use Python's built-in `iter` function as a context manager."""
    yield iter(obj)

```

**Comment by bbayles** [comment]
Could you give an example of how this makes things cleaner?
