### ISSUE TITLE
dzip (zip but for dictionaries)

### ISSUE THREAD

**Issue by khoda81** [more-itertools/more-itertools#664]
### Description
Zips multiple mappings to an iterable of (k, (v1, v2, ..., vn)).

### References
My use case:
DictEncoder is a torch module that stores a dict of modules and encodes data sample of dict[str, Tensor] by applying every module on the corresponding value in the given dict. Basically, every method was a dzip on (self, sample) so I wanted to abstract this away.

### Examples
Here is an example implementation:
```python

import functools

def dzip(*mappings):
    keys = functools.reduce(
        lambda a, b: a & b,
        (mapping.keys() for mapping in mappings),
    )

    for k in keys:
        yield k, tuple(mapping[k] for mapping in mappings)
```

**Comment by bbayles** [comment]
Thanks for the suggestion. I'm probably not going to add this one, since it's pretty close to the existing `map_reduce` function.

```python
from collections import ChainMap
from more_itertools import defaultdict

dzip_results = map_reduce(ChainMap(*mappings).items(), keyfunc=lambda x: x[0])
```

**Comment by khoda81** [comment]
@bbayles Thanks for the reply, ChainMap returns one of the values, dzip is supposed to return a tuple of all:

```python
from collections import ChainMap
from more_itertools import map_reduce

a = { "a": 1, "b": 3 }
b = { "a": 2, "b": 2 }

map_reduce(ChainMap(a, b).items(), keyfunc=lambda x: x[0])
# defaultdict(None, {'a': [('a', 1)], 'b': [('b', 3)]})

dict(ChainMap(a, b).items())
# {'a': 1, 'b': 3}

dict(dzip(a, b))
# {'a': (1, 2), 'b': (3, 2)}
```

**Comment by khoda81** [comment]
@bbayles Thanks for the reply, Your implementation does not produce the expected result, dzip is supposed to return all values in a tuple, but ChainMap only returns the first one:

```python

from collections import ChainMap
from more_itertools import map_reduce

a = { "a": 1, "b": 3 }
b = { "a": 2, "b": 2 }

map_reduce(ChainMap(a, b).items(), keyfunc=lambda x: x[0])
# defaultdict(None, {'a': [('a', 1)], 'b': [('b', 3)]})

dict(ChainMap(a, b).items())
# {'a': 1, 'b': 3}

dict(dzip(a, b))
# {'a': (1, 2), 'b': (3, 2)}
```

It would be possible to implement dzip with map_reduce, but probably look bad and allocate all the map which actually was my reason for writing dzip as a generator.
