### ISSUE TITLE
`sliced` should preferably return `Iterator[T]` over `Iterator[Sequence[T]]`

### ISSUE THREAD

**Issue by ad-chaos** [more-itertools/more-itertools#666]
https://github.com/more-itertools/more-itertools/blob/401a2c11a3cdbf88b06e8ccda89f78f61505fe94/more_itertools/more.pyi#L150-L152

**Comment by bbayles** [comment]
Is this right? If you give `sliced` a `tuple` of `int`s, then you get an iterator over `tuple`s of `int`s, not an iterator over `int`s. What am I missing?

**Comment by ad-chaos** [comment]
I am sorry, I should've been more thorough, I made that conclusion from the following code
```py
from more_itertools import sliced
reveal_type(sliced(str(1),1)) # Iterator[Sequence[str]]
```
But my reasoning was not entirely accurate.


Maybe we could define a `SupportsSlicing` Protocol that looks like
```py
@type_check_only
class SupportsSlicing(Protocol[_T_co]):
    def __getitem__(self, __k: slice) -> _T_co: ...
```
and change the typing to
```py
def sliced(
    seq: SupportsSlicing[_T], n: int, strict: bool = ...
) -> Iterator[_T]: ...
```

**Comment by bbayles** [comment]
What do they do for standard library types that can be sliced?

**Comment by ad-chaos** [comment]
Looking at typeshed,

Here's array
https://github.com/python/typeshed/blob/a7cf6144deeb3f99570f8b97fb5f5ecf16f20c01/stdlib/array.pyi#L65-L66
Sequences
https://github.com/python/typeshed/blob/fa204f6bd451c0ba118455365cc73ed97fb14bdf/stdlib/typing.pyi#L466

There are more in ctypes and from other libraries, and all of them define a `__getitem__` that accepts a slice object and returns the same collection that is generic over the initial type.
I have copied the same typings, except since we are defining a protocol, we don't need to return a collection, we can just return the generic type.

I don't recall another function that accept only slice-able objects and grepping over typeshed using `rg ": slice"` don't show typings that follow this pattern.

**Comment by bbayles** [comment]
Doesn't my using `Sequence` accomplish this? That's there because we need the input to accept a `Sequence` type.

**Comment by ad-chaos** [comment]
Would adding that protocol be fine?

**Comment by bbayles** [comment]
Yes, unless you can think of a simpler way?

**Comment by ad-chaos** [comment]
I honestly have no other idea in mind.
