### ISSUE TITLE
`set_partitons`: Specify number of elements in partitions

### ISSUE THREAD

**Issue by krono-i2** [more-itertools/more-itertools#668]
Hello!
I'm trying to get all the possible partitions of a set containing `S` elements, so that each partition contains exactly the same number of elements `N` (out of one partition that contain `S%N` elements).
It would be very interesting also that the user can specify the number of elements of each partition as a tuple (or list).
Could `set_partitions` be upgraded with the functionalities above?
Thanks for help.

Ivan

**Comment by bbayles** [comment]
If this can be further specified, I would consider accepting a PR.

**Comment by bbayles** [comment]
After #856, I'd rather not complicate this function anymore.
