### ISSUE TITLE
seekable: allow rewinding by number of elements

### ISSUE THREAD

**Issue by karlb** [more-itertools/more-itertools#670]
Is there a good way to rewind a `seekable` by a number of elements? This is useful if I only now the relative position in the source. A possible implementation could be
```python
def rewind(self, count):
    index = len(self._cache)
    self.seek(max(index - count, 0))
```

It is easy enough to do that I would not suggest an additional method, if it were not for the necessity to access private attributes.

**Comment by bbayles** [comment]
I'm open to a generalized `relative_seek` PR, that can go backward and forward (negative for backward). Thanks for the suggestion!
