### ISSUE TITLE
Introduce sequence versions of `itertools.permutations`, `itertools.combinations` and `itertools.product`

### ISSUE THREAD

**Issue by anivegesana** [more-itertools/more-itertools#671]
### Description
The proposed `more_itertools.Permutations`, `more_itertools.Combinations`, and `more_itertools.Product`  will be subclasses of `collections.abc.Sequence`. The methods of these classes will call (potentially optimized versions of) existing "Combinatorics" functions in more_itertools. If these classes are instantiated on an iterable that is not a sequence, the iterator is saved as a list in the constructor, so that it can be used multiple times in the classes.

### References
`tqdm` is able to detect if the object it is iterating over can be sized. If it is iterating over a sized object, it is able to use `__len__` to calculate how long it will take to finish iterating over the entire sequence. Because `itertools.permutations` doesn't have a `__len__` function, using the `tqdm` status bar with it requires precomputing the length manually and passing it in as another argument.

```python
import time, math, itertools
from tqdm import tqdm

seq = [1, 'a', 2.0]
for i in tqdm(
    itertools.permutations(seq),
    total=math.factorial(len(seq))
):
    time.sleep(1)
```

And unlike the iterator versions of these classes,`more_itertools.Product` objects can be iterated over multiple times, so they can be used to lazily represent `list(itertools.product(...))`. The following StackOverflow post asks how to use the result of `itertools.product` multiple times and both answers suggest to convert it to a list: https://stackoverflow.com/q/58359037 . Other answers to similar questions do the same thing: https://stackoverflow.com/a/71320220 , or use `itertools.tee`: https://stackoverflow.com/a/52724532 . In the answer to the first post, `list(it.product(a, b, c))` would be replaced with `more_itertools.Product(a, b, c))` to give a lazy version that avoids bringing the entire Cartesian product into memory at the same time, which would be useful if `a`, `b`, and `c` were relatively big.

### Examples

The above code segment would be able to be rewritten as follows:

```python
import time
import more_itertools
from tqdm import tqdm

seq = [1, 'a', 2.0]
for i in tqdm(more_itertools.Permutations(seq)):
    time.sleep(1)
```

The following function calls will be equivalent:
```python
Permutations(seq, r).index(p)       = permutation_index(p, seq)               # only if len(p) == r
random.choice(Permutations(seq, r)) = random_permutation(seq, r)
Permutations(seq, r)[i]             = nth_permutation(seq, r, i)
iter(Permutations(seq, r))          = itertools.permutations(seq, r)
reversed(Permutations(seq, r))      = itertools.permutations(reversed(seq), r)

len(Permutations(seq, r))           = math.perm(len(seq), r)
len(Combinations(seq, r))           = math.comb(len(seq), r)
len(Product(*seqs, repeat=r))       = math.prod(len(seq) for seq in seqs * r)
```

### Miscellany

Slicing and counting can be implemented for these classes to make them compliant with the [Python common sequence operations](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range), but it is not clear to me whether they should be implemented at all for any reason other than completeness. `more_itertools.circular_shifts` and other functions could be added, but I didn't believe that they would see much use or attention compared to the three suggested. A `Repeat` sequence might also be useful for implementing the `*` for these three classes, but I haven't come across a time that I would have needed to use it, so I left it out of the proposal.

An alternative naming scheme I have for these sequences is `more_itertools.SequenceView.permutations`. It has the benefit of being explicit about what the object is and doesn't create confusion among beginners relating to capitalization, but it is pretty verbose. Suggestions on naming would be appreciated.

**Comment by bbayles** [comment]
> Because itertools.permutations doesn't have a __len__ function, using the tqdm status bar with it requires precomputing the length manually and passing it in as another argument.

Given that this exists, I think I'll pass on this enhancement request.

Are there `tqdm` docs that can be augmented with examples? It might be a good idea to do that.

**Comment by anivegesana** [comment]
Hmm. There seems to be a `tqdm` version of `product`, but it is not well-documented. https://tqdm.github.io/docs/contrib.itertools/

Creating versions for `permutations` and `combinations` within `tqdm` and improving the documentation there might be a better solution to the first use case I listed. The use case of iterating over a `product` multiple times can be solved with recreating the iterator multiple times. Sequence forms of each would allow for syntactic sugar or for situations that an API is called that requires a sequence instead of an iterator, but I cannot find a necessary purpose for the addition of these classes.

I agree that this issue isn't high priority and can also be solved elsewhere. I will try to see if I can find more use cases and examples that I can list, but if not, I will closing this issue.

**Comment by rhettinger** [comment]
I would suggest that a sequence-version of any of these tools is out of scope for a package that is defined to be primarily about creating and consuming iterators.

FWIW, the issue of "computing the size manually" is mostly solved by `math.factorial`, `math.perm`, and `math.comb`.  They were specifically designed to match the corresponding `itertools`.

**Comment by anivegesana** [comment]
Agreed. And I didn't really find any other uses for it other than the `tqdm` one, so I will close this issue.
