### ISSUE TITLE
Itertool proposal: Common lisp like iterator selector: `first`, `second`, ..., `tenth`.

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [more-itertools/more-itertools#683]
### Description
These are simple indexed selectors that use English names. Following a lot of the functional-inspired programming that arises from `more_itertools` with all of the mapping and zipping.

### References

Well, I have found myself in the past longing for some predefined function to get the `first` or `second` element of an iterable. This is especially useful as an argument to map. I see that `first` is already defined. I believe that continuing the selectors up to `tenth` just like in clisp may be beneficial.  

### Examples
`ages = map(second, [("Damian", 24), ("Bill", 49)]`

**Comment by Skeen** [comment]
How do you imagine `ninth` to work, like `partial(nth, n=8)` or `partial(nth_or_last, n=8)`?

**Comment by DamianB-BitFlipper** [comment]
I envisioned no safety nets and fail fast, ie: `partial(nth, n=8)`

**Comment by bbayles** [comment]
I'd rather not do this, I'm afraid. There are one-line alternatives, and I don't think the implementations would be educational for readers.
