### ISSUE TITLE
[Feature Request] nth_combination_with_replacement

### ISSUE THREAD

**Issue by lukemarris** [more-itertools/more-itertools#684]
### Description

Similar to nth_combination and nth_permutation, which are already implemented in the library.

It would have signature: `nth_combination_with_replacement(iterable, r, index)`
and would return `list(combinations_with_replacement(iterable, r))[index]`
without enumerating all combinations before.

**Comment by lukemarris** [comment]
Here is my attempt:

```python
def n_choose_r(n, r):
  c = 1
  k = min(r, n - r)
  for i in range(1, k + 1):
    c = c * (n - k + i) // i
  return c


def nth_combination_with_replacement(iterable, r, index):
  """Equivalent to ``list(combinations_with_replacement(iterable, r))[index]``.
  """
  pool = tuple(iterable)
  n = len(pool)
  if (r < 0) or (r > n):
    raise ValueError

  c = n_choose_r(n + r - 1, r)
  if index < 0:
    index += c

  if (index < 0) or (index >= c):
    raise IndexError

  result = []
  i = 0
  while r:
    r -= 1
    while n >= 0:
      num_combs = n_choose_r(n + r - 1, r)
      if index < num_combs:
        break
      n -= 1
      i += 1
      index -= num_combs
    result.append(pool[i])

  return tuple(result)
```

**Comment by bbayles** [comment]
Yes, thanks - I'll accept a PR for this.

**Comment by lukemarris** [comment]
I will not have the bandwidth to make a pull request for this for the foreseeable future.

I am happy for someone else to cannibalize my code above into a full PR.
