### ISSUE TITLE
[Feature Request] inverse_nth_*

### ISSUE THREAD

**Issue by lukemarris** [more-itertools/more-itertools#685]
### Description

The inverse of `nth_combination`, `nth_permutation`, etc ... functions.

For example, it would have a signature `inverse_nth_combination(iterable, r, comb)`
and would return `list(combinations(iterable, r)).index(sorted(comb))`
without enumerating all combinations.

**Comment by bbayles** [comment]
Do you have any examples of this being useful from StackOverflow or GitHub? I can't think of when I would have needed such a thing.

**Comment by lukemarris** [comment]
I would argue that if nth_combination is useful enough to be in the library, an inverse_nth_combination would be a useful compliment.

For example, imagine you want to store the values of a symmetric matrix M_ij = M_ji, with n rows and columns, efficiently you would only need to store each an element for each combination of indices. The values could be stored in a flat_array. It would be advantageous to be able to index from this flat_array with both the flat `index` and the original `comb`.

```python
flat_array[index] == matrix[nth_combination(iterable=range(n), r=2, index)]
matrix[comb] == flat_array[inverse_nth_combination(iterable=range(n), r=2, comb)]
```

**Comment by Schoyen** [comment]
Sorry to break in, but is this not what `combination_index` does?

```python
r = 2
n = 5

counter = 0
for i in range(n):
    for j in range(i + 1, n):
        index = combination_index((i, j), range(n))
        comb = nth_combination(range(n), r, index)
        assert comb == (i, j)
        assert counter == index
        counter += 1
```

Also, a `combination_with_replacement_index`-function to complement your suggested `nth_combination_with_replacement` from #684 would allow for the same type of indexing for symmetric matrices.

**Comment by lukemarris** [comment]
You are completely right - thank you for pointing this out. As you said, let us refocus with feature request on `combination_with_replacement_index`.

**Comment by Schoyen** [comment]
I'm glad I could help!
