### ISSUE TITLE
Changelog's latest entry has an incorrect version

### ISSUE THREAD

**Issue by stevejalim** [more-itertools/more-itertools#688]
Just noticed there are two entries for 8.14.0 -- I suspect the topmost one should be the 9.1.0 release, yep? 

<img width="1120" alt="Screenshot 2023-03-02 at 11 11 49" src="https://user-images.githubusercontent.com/101457/222412779-dfe9f773-fa6e-413d-aa17-337a7a90485a.png">

Source: https://more-itertools.readthedocs.io/en/stable/versions.html

**Comment by stevejalim** [comment]
Ah looks like this was fixed in https://github.com/more-itertools/more-itertools/commit/320b0b976fe367c7c91abcc1c185e22396618f08 -- might just need a refresh on RTD

**Comment by bbayles** [comment]
Thanks - this was fixed by creating the docs-only release 9.1.1.
