### ISSUE TITLE
Should raise error when transposing an empty collection with `transpose`

### ISSUE THREAD

**Issue by XuehaiPan** [more-itertools/more-itertools#697]
[`more_itertools.transpose`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.transpose) is a shortcut for `zip(*nested)`:

https://github.com/more-itertools/more-itertools/blob/4bdd12f7b33da265eac1c417772f5b24631e8055/more_itertools/recipes.py#L894-L903

We should check whether the nested collection is a zero-sized matrix. For example, transposing a $0 \times n$ matrix is undefined.

```python
>>> from more_itertools import transpose
>>> list(transpose([[1, 2, 3], [4, 5, 6]]))  # m x n -> n x m
[(1, 4), (2, 5), (3, 6)]
>>> list(transpose([]))
[]  # 0 x m -> 0
>>> list(transpose([(), ()]))
[]  # m x 0 -> 0
```

Example use case:

```python
>>> keys, values = transpose({'a': 1, 'b': 2, 'c': 3}.items())
>>> list(transpose({'a': 1, 'b': 2, 'c': 3}.items()))
[('a', 'b', 'c'), (1, 2, 3)]
>>> keys, values = transpose({}.items())  # should raise a more informative error (e.g., transposing an empty collection is invalid)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by bbayles** [comment]
Given that we usually take the `recipes.py` functions straight from the `itertools` documentation, I'm not really inclined to change this.

If you want to add a note to the docs saying that callers should beware passing in empty values, then I'll take that PR.

**Comment by rhettinger** [comment]
In general, we try to let functions degrade naturally into edge cases.  That is why `sum([]) == 0` for example.  Also note that NumPy and Octave define the transpose of an empty matrix as an empty matrix:

```
>>> import numpy as np
>>> np.array([]).transpose()
array([], dtype=float64)

octave:1> A = []
A = [](0x0)
octave:2> A'
ans = [](0x0)
```
