### ISSUE TITLE
function passed to `iterate()` cannot control iterations by raising `StopIteration`. Is it expected?

### ISSUE THREAD

**Issue by jrebiffe** [more-itertools/more-itertools#707]
The `iterate()` function doesnot accept the function to raise `StopIteration`, because `iterate()` is generator function.
Behavior of `StopIteration` in generator seems to be changed in [Python version 3.7](https://docs.python.org/3/library/exceptions.html#StopIteration) and [PEP479](https://peps.python.org/pep-0479/).

This behavior prevents the function passed as *func* argument to control when iterate stops.

Is that the expected behavior of `iterate()` function?

## Example
Here is the simplest example: At reach round, a dice is rolled. Game is over as soon as dice is 6, otherwise dice value is added to the score, then a new round is played.
The only state kept between round is the score (It will be more for a real game). I want to use a generator to keep track of game's state (so the score only here).
```python3
from random import randrange
from typing import Iterator

from more_itertools import iterate


def play_round(score: int) -> int:
    dice = randrange(1, 7)
    game_over = dice == 6
    if game_over:
        raise StopIteration
    return score + dice


def play_game() -> Iterator[int]:
    """How many dices can you roll before having a 6?"""
    # iterate() raises RuntimeError, 'for' loop expects StopIteration.
    return iterate(play_round, start=0)
```

```python3
>>> from dice_game import play_game
>>> for round_score in play_game():
...     print(round_score)
...
0
5
9
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.8/site-packages/more_itertools/more.py", line 475, in iterate
    start = func(start)
  File "/home/jean/python/dice_game.py", line 11, in play_round
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: generator raised StopIteration
```

# Comparison with `accumulate()`
The *func* in `accumulate()` of itertools module can raise the `StopIteration` exception and provide the expected behavior.
That enables the function passed as *func* argument to control when iterate stops.

## Example
That example is borrowed from Joel Grus' [Stupid Itertools Tricks For Data Science](https://github.com/joelgrus/stupid-itertools-tricks-pydata/blob/ab5a552c9d5cbfddf79d77d73ca86d56ead3278d/src/stupid_tricks.py#L19).

Information are available on the talk: [Joel Grus: Learning Data Science Using Functional Python](https://youtu.be/ThS4juptJjQ?t=1421), PyData Seattle 2015, *Fibonacci numbers example* (23:44) and [slide number 65](https://docs.google.com/presentation/d/1eI60SL3UxtWfr9ktrv48-pcIkk4S7JiDmeXGCyyGhCs/edit#slide=id.g5bd0df450_0_473).

```python3
from itertools import accumulate
from typing import Iterable, Iterator, TypeVar

T = TypeVar("T")


def no_repeat(previous: T, current: T) -> T:
    if previous == current:
        raise StopIteration
    return current


def until_convergence(iterable: Iterable[T]) -> Iterator[T]:
    # accumulate() works fine with func which raise StopIteration
    return accumulate(iterable, no_repeat)
```
```python3
>>> from itertools import chain, repeat
>>> from until_convergence import until_convergence
>>> some_infinite_iterable = chain(range(0, 100, 10), repeat(100))
>>> list(until_convergence(some_infinite_iterable))
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
```
`no_repeat()` controls when the iterations stops, while the iterable is infinite.

# Alternative `iterate()` function
On the same Python module, [Joel Grus also proposes an alternative version of `iterate()`](https://github.com/joelgrus/stupid-itertools-tricks-pydata/blob/ab5a552c9d5cbfddf79d77d73ca86d56ead3278d/src/stupid_tricks.py#L15) based on `accumulate()` and `repeat()`, rather than a generator function.

Joel Grus' alternative results the behavior that I expected.
```python3
>>> from dice_game import play_game
>>> for score in play_game():
...     print(score)
...
0
3
4
```

## script with alternative `iterate()` function
```python3
"""Alternative `iterate()` implementation which support `StopIteration`.

Enables the function passed in *func* argument to control when the iteration
stops by raising `StopIteration`.
"""
from itertools import accumulate, repeat
from typing import Callable, Iterator, TypeVar

T = TypeVar("T")


def iterate(func: Callable[[T], T], start: T) -> Iterator[T]:
    """Return ``start``, ``func(start)``, ``func(func(start))``, ...

    >>> from itertools import islice
    >>> list(islice(iterate(lambda x: 2*x, 1), 10))
    [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
    """
    # borrowed from Joel Grus' stupid_tricks.py and signature adjusted
    return accumulate(repeat(start), lambda fx, _: func(fx))
```
Then I just changed `from more_itertools import iterate` to `from alternative_iterate import iterate` in the game file.
[iterate.zip](https://github.com/more-itertools/more-itertools/files/11264530/iterate.zip)

**Comment by bbayles** [comment]
What if we changed `iterate` to catch `StopIteration` and break?

```python
def iterate(func, start):
    while True:
        yield start
        try:
            start = func(start)
        except StopIteration:
            break
```

I will accept a PR that does this.

**Comment by bbayles** [comment]
I'd rather not import all of `contextlib` if all we're doing is a try/catch. I've never seen `throw(StopIteration)` in production code.

**Comment by bbayles** [comment]
Thanks for the PR; this change will go out with the next release.

**Comment by jrebiffe** [comment]
Thanks you.
