### ISSUE TITLE
`partial_product` is wrong for zero/one input iterables and for empty iterables

### ISSUE THREAD

**Issue by pochmann** [more-itertools/more-itertools#713]
- The doc says: *"Yields tuples"*. 
- And: *"This may be useful, for example, when testing an expensive function."* (This was also the [original proposal](https://github.com/more-itertools/more-itertools/issues/465#issue-704492388)'s use case.)
- And from its name you'd expect it to yield a subset of what `itertools.product` yields, which it indeed does when given two or more input iterables.
- And @lonnen (who implemented it) [said](https://github.com/more-itertools/more-itertools/issues/465#issuecomment-1447791590) it *"should produce m - (n - 1) outputs, where m is the total number of items in all iterators and n is the number of iterators"*.

For zero input iterables, it yields nothing. It should yield the empty tuple, as you'd generally expect and as `itertools.product` does and as the documented use case of testing a (in this case nullary) function would require and as the m - (n - 1) = 0 - (0 - 1) = 1 formula says.

```python
list(partial_product()) = []
list(product()) = [()]
```

For one input iterable, it doesn't yield tuples as documented and as `itertools.product` does, but just the raw elements:

```python
list(partial_product('abc')) = ['a', 'b', 'c']
list(product('abc')) = [('a',), ('b',), ('c',)]
```

**Comment by pochmann** [comment]
It's also wrong when an input iterable is empty. Then the product is simply empty, i.e., nothing should be yielded. Currently it instead raises an error.

**Comment by bbayles** [comment]
Thanks - I'll take a PR to correct these items.

**Comment by lonnen** [comment]
Thanks @pochmann! Good catch

**Comment by pochmann** [comment]
I also successfully tested it on all 781 cases with 0 to 4 iterables of lengths 0 to 4. Where I compute the expected result by filtering `itertools.product`. See below. I could add that to the tests later (it only takes ~0.03 seconds). For now I just mention it for extra reassurance about my PR. (I also have a simpler/faster `partial_product` implementation, but first I just want to fix the bugs).

```python
from itertools import product

for n in range(5):
    for lengths in product(range(5), repeat=n):

        iterables = [
            [object() for _ in range(length)]
            for length in lengths
        ]

        expect = [
            items
            for items in product(*iterables)
            for check in [zip(items, iterables)]
            if all(item is iterable[-1] for item, iterable in check)
            or all(item is iterable[0] for item, iterable in check)
        ]

        result = list(partial_product(*iterables))

        assert result == expect
```
