### ISSUE TITLE
A proposal to skip first and/or last elements in an iterator

### ISSUE THREAD

**Issue by lokeshkalamalla** [more-itertools/more-itertools#724]
### Description
I used to jump back to use range(m,len(some_list)-n), to skip first m elements and last n elements, which is too lengthy and non-pythonic. A tool to do the same would be helpful and much deserves a place in more-itertools

### References

https://stackoverflow.com/a/10079869/21074016

### Examples

>>> list(skip(range(10), at_start=2, at_end=2))
[2, 3, 4, 5, 6, 7]

**Comment by nanouasyn** [comment]
What are the differences from `islice_extended` (https://stackoverflow.com/a/44532860)?

```python
>>> list(islice_extended(range(10), 2, -2))
[2, 3, 4, 5, 6, 7]
```
