### ISSUE TITLE
Proposal for `full_outer_join`

### ISSUE THREAD

**Issue by dgilmanAIDENTIFIED** [more-itertools/more-itertools#726]
### Description
Do a full outer join on N iterables, yielding up the sets of rows that have matching join keys. See [Sort-merge join](https://en.wikipedia.org/wiki/Sort-merge_join)

The underlying merge runs in O(n) time and only buffers enough in memory to detect when it needs to start the next join key, so that's typically one extra peeked value per iterator + the total values for the current join key of memory usage. Sorting is O(n log n) but this code does not do sorts, instead assuming that inputs are already sorted.

### References
- It seems like a useful thing to have in general. Relational joins are a fundamentally useful technique.
- Once you have full outer join you can get inner/left/right/Nth join by simply ignoring the join keys that didn't satisfy your join condition.
- People whose brains have been poisoned by the relational model (me, many DBAs and devs who have spent too much time writing SQL) like expressing computation in this way.
- The alternative would be to do the join in the ugly O(n**2) nested for loop way or do a hash join with Python dictionaries (which  is algorithmically efficient but is not lazy). It's a code complexity win to sweep up that logic behind an iterator only a simple function call away.
- It's lazy / doesn't do its own sorting. It is not at all unreasonable to imagine using this over streaming sets of data (from a file, from a database, from logging systems) where data was already sorted or has a monotonically increasing join key (e.g. timestamps).

I've personally used this code for new code in production to join up and update arrays of objects. It resulted in straightforward iterative code that was easy to read, easy to reason about and had useful code coverage statistics. I also used it to fix up some O(n**2) looping left by a junior developer where it can drop in as-is to improve algorithmic complexity without needing any invasive refactors of the merge logic.

### Examples
(whitespace for clarity)
```
>>> list(more_itertools.full_outer_join(
    [{"id": 1, "val": "foo"}                         ],
    [{"id": 1, "val": "bar"}, {"id": 2, "val": "baz"}],
    key=lambda x: x["id"]
))
[
    (1, ([{'id': 1, 'val': 'foo'}], [{'id': 1, 'val': 'bar'}])),
    (2, ([                       ], [{'id': 2, 'val': 'baz'}]))
]
```

**Comment by pochmann** [comment]
> O(n)

What is n?

**Comment by dgilmanAIDENTIFIED** [comment]
n is the length of the iterables, the function runs in linear time with respect to the length of the iterables.

If I am understanding the `map_reduce` solution, it's like this:

```
rel1 = [{"id": 1, "val": "foo"}, {"id": 3, "val": "xyz"}]
rel2 = [{"id": 1, "val": "bar"}, {"id": 2, "val": "baz"}]

keyfunc = lambda x: x["id"]
identity = lambda x: x

flattened = flatten([rel1, rel2])
joined = map_reduce(flattened, keyfunc=keyfunc, valuefunc=identity, reducefunc=identity)
```

map_reduce is doing a hash join. It is not lazy, it has to consume all the iterables. You might use this `full_outer_join` it if you want immediate output, need to cancel everything partway through, or need to cut down on memory use.

But, there is also something to be said for documentation/discovery. Even if you decide against this implementation maybe it is worth packaging up the map_reduce implementation as one of the recipes.

**Comment by bbayles** [comment]
I decided against this one. Thanks for the contribution; I do appreciate the effort and will be open to other ideas!

**Comment by dgilmanAIDENTIFIED** [comment]
If anyone else is finding this later and wanted to use it I packaged the full outer join along with inner, left and right join recipes in the stand-alone package [full_outer_join](https://pypi.org/project/full-outer-join/) on pypi.
