### ISSUE TITLE
Generalized outer product

### ISSUE THREAD

**Issue by OlegAlexander** [more-itertools/more-itertools#729]
### Description

Hello and thank you for creating `more-itertools`! It's great.

I'd like to propose adding a generalized outer product function. It's similar to the `itertools.product` function, except that it preserves the nested structure of the 2D matrix and allow you to apply a function to every pair of items. This function is surprisingly versatile!

### References

This function exists mainly in array languages. It also exists in Numpy but it's cumbersome to use because you need to create a ufunc. Ufuncs also don't play well with mypy. 

- [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.outer.html)
- [APL](https://aplwiki.com/wiki/Outer_Product)
- [Wolfram](https://reference.wolfram.com/language/ref/Outer.html)
- [BQN](https://mlochbaum.github.io/BQN/help/table.html)

### Examples

```python
from typing import TypeVar, Iterable, Callable

T = TypeVar('T')
U = TypeVar('U')
V = TypeVar('V')


def outer_product(func: Callable[[T, U], V], xs: Iterable[T], ys: Iterable[U]) -> Iterable[list[V]]:
    ys = list(ys)  # Consume ys once 
    return ([func(x, y) for y in ys] for x in xs)


if __name__ == '__main__':
    from operator import mul
    from more_itertools import dotproduct, matmul, transpose
    from itertools import compress

    # Multiplication table
    assert list(outer_product(mul, [1, 2, 3], [1, 2, 3])) == [[1, 2, 3], 
                                                              [2, 4, 6], 
                                                              [3, 6, 9]]

    # Matrix multiplication
    # Source: https://futhark-lang.org/examples/outer-product.html
    # You have to admit that outer_product(dotproduct, A, transpose(B)) is a pretty neat way to write matmul!
    A = [[1, 2], [3, 4], [5, 6]]
    B = [[7, 8, 9], [10, 11, 12]]

    assert list(outer_product(dotproduct, A, transpose(B))) == list(matmul(A, B)) 
    # [[27, 30, 33], 
    #  [61, 68, 75], 
    #  [95, 106, 117]]

    # Greetings
    greetings = ['Hello', 'Goodbye']
    names = ['Alice', 'Bob']
    assert list(outer_product(lambda g, n: f'{g}, {n}!', greetings, names)) == [['Hello, Alice!', 'Hello, Bob!'], 
                                                                                ['Goodbye, Alice!', 'Goodbye, Bob!']]

    # Distance matrix 
    coords = [[0.68446066, 0.09628254],
              [0.05818767, 0.26179779],
              [0.76983281, 0.65376925],
              [0.6214879 , 0.7856759 ]]

    distance = lambda p1, p2: round(((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)**0.5, 2)

    assert list(outer_product(distance, coords, coords)) == [[0.0, 0.65, 0.56, 0.69], 
                                                             [0.65, 0.0, 0.81, 0.77], 
                                                             [0.56, 0.81, 0.0, 0.2], 
                                                             [0.69, 0.77, 0.2, 0.0]]

    # Filter out sentences that contain certain words
    # I've actually used something like this in production code!
    sentences = ["The quick brown fox jumps over the lazy dog.",
                 "The truth will set you free.",
                 "The only thing we have to fear is fear itself."]
    words = ['quick', 'fear']
    mask = outer_product(lambda s, w: s.find(w) == -1, sentences, words)
    filtered_sentences = list(compress(sentences, map(all, mask)))
    assert filtered_sentences == ['The truth will set you free.']
```

This function can also be defined for higher dimensions. 

Thank you for your consideration!

**Comment by bbayles** [comment]
Thanks for the writeup. I'll be out for a bit (new baby at home!), and will look at your proposal in detail soon.

**Comment by OlegAlexander** [comment]
Congratulations on your new baby!!

**Comment by rhettinger** [comment]
Possible alternative implementation:

```
def outer_product(func, xs, ys):
    ys = tuple(ys)
    return batched(starmap(func, product(xs, ys)), n=len(ys))
```

Possibly add `*args` and `**kwargs` as [operator.methodcaller()](https://docs.python.org/3/library/operator.html#operator.methodcaller) does:

```
def outer_product(func, xs, ys, *args, **kwargs):
    ys = list(ys)
    return ([func(x, y, *args, **kwargs) for y in ys] for x in xs)
```

The extended signature would allow calls with extra fixed arguments such as:

`outer_product(pow, range(4), range(6), mod=5)`

Also, consider producing an iterator of tuples instead of an iterator of lists.  This would be consistent with `zip`, `batched`, `enumerate`, `product`, `combinations`, and `permutations` as well as with tools like `csv.reader` and `sqlite3.fetchall`.

Overall, this seems like a neat idea although the applications may be a bit limited (cross-tabulation tables, etc).

**Comment by bbayles** [comment]
I'm marking this as `pr-welcome`; I'll accept a PR that adds this. I like the suggestions Raymond mentioned above, and it would be great if we could provide an example like a crosstab in the docstring. Thanks!

**Comment by OlegAlexander** [comment]
Hello @rhettinger and @bbayles. I'm working on this PR and I wanted to run my cross tabulation example by you:

```python
    # Cross tabulation
    genders = ['F', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'F', 'M']
    ratings = [1, 2, 2, 2, 3, 1, 3, 1, 2, 2, 2, 1]
    rows = list(zip(genders, ratings))
    crosstab = list(
        outer_product(
            lambda g, u: rows.count((g, u)),
            sorted(set(genders)),
            sorted(set(ratings)),
        )
    )
    assert crosstab == [(1, 2, 1), (3, 4, 1)]

```

This mirrors how the [`crosstab`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.contingency.crosstab.html) function works in Scipy.

Is the example ok? I plan to include at least the multiplication table example and the crosstab example in the doc string, so I hope it's not too long.

**Comment by bbayles** [comment]
The code is good, but could you pick a different pair of variables?
