### ISSUE TITLE
takewhile_inclusive

### ISSUE THREAD

**Issue by OlegAlexander** [more-itertools/more-itertools#730]
### Description

Hello again. I'd like to propose `takewhile_inclusive`, a version of `takewhile` which yields one additional element.

### References

- [C do...while loop](https://www.tutorialspoint.com/cprogramming/c_do_while_loop.htm) -- This is probably the most convincing argument for why this function should be included, historically speaking.
- [Python discussion](https://stackoverflow.com/questions/30615659/how-not-to-miss-the-next-element-after-itertools-takewhile)
- [RxJS takeWhile](https://www.learnrxjs.io/learn-rxjs/operators/filtering/takewhile) -- This version of takeWhile takes an `inclusive` boolean argument. [Related discussion](https://stackoverflow.com/questions/44641246/rxjs-takewhile-but-include-the-last-value) before the inclusive argument was added to RxJS.
- [Haskell discussion](https://stackoverflow.com/questions/41741681/haskell-takewhile-1)
- [C# LINQ discussion](https://stackoverflow.com/questions/3098649/custom-inclusive-takewhile-is-there-a-better-way) and [MoreLinq.TakeUntil](https://morelinq.github.io/3.4/ref/api/html/M_MoreLinq_MoreEnumerable_TakeUntil__1.htm).
- [Rust discussion](https://github.com/rust-lang/rust/issues/62208) -- This function was [eventually added](https://github.com/rust-itertools/itertools/issues/597) to [Rust's itertools](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.take_while_inclusive).

### Examples

```python
"""Collatz Conjecture / 3n+1 Problem"""

from itertools import takewhile
from more_itertools import iterate, before_and_after, take
from typing import Callable, TypeVar, Iterable


T = TypeVar('T')


def takewhile_inclusive(predicate: Callable[[T], bool], it: Iterable[T]) -> Iterable[T]:
    """Source: https://stackoverflow.com/a/70762559"""
    for x in it:
        if predicate(x):
            yield x
        else:
            yield x
            break


def is_even(n: int) -> bool:
    return n % 2 == 0


def collatz_takewhile(n: int) -> list[int]:
    """First attempt. I really hate having to cheat with the + [1] at the end."""
    assert n > 0, "n must be a positive integer."
    return list(takewhile(
        lambda n: n != 1, 
        iterate(lambda n: n // 2 if is_even(n) else 3 * n + 1, n))) + [1]


def collatz_before_and_after(n: int) -> list[int]:
    """Second attempt. This is much better, but too verbose."""
    assert n > 0, "n must be a positive integer."
    before, after = before_and_after(
        lambda n: n != 1,
        iterate(lambda n: n // 2 if is_even(n) else 3 * n + 1, n))
    return list(before) + list(take(1, after))


def collatz_takewhile_inclusive(n: int) -> list[int]:
    """Third attempt. This is what needs to happen!"""
    assert n > 0, "n must be a positive integer."
    return list(takewhile_inclusive(
        lambda n: n != 1, 
        iterate(lambda n: n // 2 if is_even(n) else 3 * n + 1, n)))


n = 11
assert (collatz_takewhile(n) == 
        collatz_before_and_after(n) == 
        collatz_takewhile_inclusive(n) == 
        [11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1])

```

For symmetry, we can also consider adding `dropwhile_inclusive`. Thank you.

**Comment by pochmann** [comment]
How about instead of
```python
    return list(takewhile_inclusive(
        lambda n: n != 1,
```
do
```python
    return list(takeuntil(
        lambda n: n == 1,
```
That would focus on the ending value, which seems more natural to me. Or is the negated predicate more natural in most cases?

**Comment by OlegAlexander** [comment]
I like that, too. That's exactly what the [MoreLink.TakeUntil](https://morelinq.github.io/3.4/ref/api/html/M_MoreLinq_MoreEnumerable_TakeUntil__1.htm) method does.

**Comment by KennedyRichard** [comment]
In the body of the for-loop, I'd suggest replacing the if/else combo by a single if statement. Like this:

```
for x in it:

    yield x

    if predicate(x):
        break
```

I think it would be even more simple and readable this way. It is inspired by a [Python do-while emulation](https://realpython.com/python-do-while/), but slightly changed for this case.

Alternatively, the `break` statement could be replaced by `return`, which I'm not fond of (in this particular instance, that is) but [seems to be acceptable anyway](https://twitter.com/raymondh/status/1127261588455452672).

I also think the name `takeuntil` **seems** more appropriate.
