### ISSUE TITLE
Trap exceptions in an existing iterable

### ISSUE THREAD

**Issue by jaraco** [more-itertools/more-itertools#735]
### Description

Consider the case where one has an iterable but wishes to handle an Exception that occurs during iteration, but to declare that trapping when the iterator is created, such as when invoking `pathlib.Path.iterdir()`. A common example is where a user wishes to trap the FileNotFoundError while listing a directory (taken from https://github.com/python/cpython/issues/78722):

```python
try:
    children = path_that_doesnt_exist.iterdir()
except FileNotFoundError:
    print("directory doesn't exist")
for path in children:
    print(path.stat().st_size)
```

I'd like to be able to write a wrapper for `iterdir()` that will suppress a FileNotFound error and in that condition return an empty iterable.

`iter_except` almost works:

```
>>> list(iter_except(pathlib.Path('does-not-exist').iterdir().__next__, FileNotFoundError))
[]
```

Unless the directory does exist, then the iterator fails when it reaches the end:

```
>>> list(iter_except(pathlib.Path().iterdir().__next__, FileNotFoundError))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/more_itertools/recipes.py", line 543, in iter_except
    yield func()
          ^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: generator raised StopIteration
```

It is possible to additionally trap the `StopIteration`:

```
>>> list(iter_except(pathlib.Path().iterdir().__next__, (FileNotFoundError, StopIteration)))
[...]
```

But now the user is forced to entangle their primary concern (`FileNotFoundError`) with an implementation detail of the exception handler (`StopIteration`). It's also unnatural that the caller must pass `__next__`.

What if instead, `iter_except` would implicitly handle both conditions, such that one could simply call:

```
iter_except(pathlib.Path().iterdir(), FileNotFoundError)
```

Either that or have a new itertool with that interface.

Such a tool would allow users to catch arbitrary exceptions encountered when processing an iterable (or iterator) without having to eagerly consume and store the contents of the iterable (the current best recommendation for callers of iterdir).

**Comment by jaraco** [comment]
An alternate approach could be to supply a tool called `check()`. It would act like `peek`, except it would return just the iterable. Then someone could write:

```
try:
    children = check(path_that_doesnt_exist.iterdir())
except FileNotFoundError:
    print("directory doesn't exist")
for path in children:
    print(path.stat().st_size)
```

The implementation of `check` could be fairly straightforward:

```
def check(iterable):
    return spy(iterable)[1]
    # or
    head, replacement = spy(iterable)
    return replacement
```

**Comment by bbayles** [comment]
I was thinking that `filter_except` or `map_except` might work here, but they fail the same way.

What if I changed their implementation to look like:

```python
def map_except(function, iterable, *exceptions):
    it = iter(iterable)
    while True:
        try:
            yield function(next(it))
        except exceptions:
            pass
        except StopIteration:
            break
```

This seems to fix the `pathlib` issue with `iterdir`, and doesn't disturb existing tests.

**Comment by jaraco** [comment]
I was thinking something along those lines. Should we also consider adapting `function` so that the user can pass `function_or_iterable`. Or, thinking about it another way, what is a user expected to pass when all they have is an iterable and a list of exceptions to trap?

**Comment by bbayles** [comment]
I suppose `filter_except` can be called with something that always returns `True` and `map_except` can be called with an identity function. Is adding a third function that doesn't take a function slicing things too thin?

If not, what to call it? `map_except`, `filter_except`, and...? `iter_except` is already taken. `iter_suppress`, perhaps?

**Comment by rhettinger** [comment]
I vote for `iter_suppress`.

**Comment by bbayles** [comment]
@rhettinger , many thanks as always for your comments.

I opened https://github.com/more-itertools/more-itertools/pull/756, which I think implements your idea.
