### ISSUE TITLE
Drop

### ISSUE THREAD

**Issue by OlegAlexander** [more-itertools/more-itertools#751]
### Description

We have `take`, but we don't seem to have `drop`. Unless it's under a different name?

### References

[Haskell drop](http://zvon.org/other/haskell/Outputprelude/drop_f.html)
[Scala drop](https://www.geeksforgeeks.org/scala-list-drop-method-with-example/)
[C# LINQ skip](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.skip?view=net-7.0)
[F# List.skip](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#skip)

### Examples

```python
from typing import TypeVar, Iterable
from itertools import islice

_T = TypeVar('_T')

def drop(n: int, iterable: Iterable[_T]) -> list[_T]:
    return list(islice(iterable, n, None))

if __name__ == "__main__":
    assert drop(5, range(1, 11)) == [6, 7, 8, 9, 10]
    assert drop(12, range(1, 11)) == []
```

Do you think it's worth adding `drop` for symmetry with `take`?

**Comment by bbayles** [comment]
Given that it doesn't really even save a line, I probably wouldn't include it here unless it was already a recipe in the docs.

**Comment by OlegAlexander** [comment]
I'm really surprised to hear you say that because I was sure you'd say Yes. 😅

My counterargument is: you're right that the implementation is very short, but `drop` indicates intent better than `islice(iterable, n, None)`.

And... we already have `take`! Sorry, I'm a little OCD about this kind of stuff.

I hope you change your mind, but if not, no biggie.

**Comment by bbayles** [comment]
I wouldn't have included `take` if it weren't a recipe either, ha.
