### ISSUE TITLE
Proposal for new itertool `postpend`

### ISSUE THREAD

**Issue by bjrtx** [more-itertools/more-itertools#780]
### Description
Would introduce
```python
def postpend(iterator, value):
    """Yield the elements in *iterator* followed by value.
    """
    return chain(iterator, [value])
```

`append` is also a possible name, but clashes with `list.append`.

### References

- Natural counterpart to `prepend`, which already exists
- Elementary operation on iterables, cf. `list.append`

### Examples
```python
>>> value = '0'
>>> iterator = ['1', '2', '3']
>>> list(postpend(iterator, value))
[''1', '2', '3', '0']
```

**Comment by bbayles** [comment]
Thanks for the suggestion. I'm not inclined to add this, because I think the existing `value_chain()` function is more flexible:

Here's an example from the tests:
```
    def test_more(self):
        actual = list(mi.value_chain(b'bar', [1, 2, 3], 4, {'key': 1}))
        expected = [b'bar', 1, 2, 3, 4, 'key']
        self.assertEqual(actual, expected)
```

I would accept a PR that added explicit "prepend" and "postpend" examples to the docstring for that function.
