### ISSUE TITLE
add `bucket.as_dict`

### ISSUE THREAD

**Issue by ScDor** [more-itertools/more-itertools#800]
Many times when I use `bucket`, I convert it to a dictionary. 
It could come up handy if it had a `as_dict` method

```python
    def as_dict(self):
        return {key: self[key] for key in self}
```
This would return a dictionary of the form `key: generator`, allowing further iteration over items.

Wdyt?

**Comment by JamesParrott** [comment]
Using a dict comprehension would consume a base iterator on calling `as_dict`.  It would open a huge can of worms that goes against the ethos of more-itertools, and only saves the caller from writing a one liner.

Bucket already implements `__getitem__`.  There's only any point to implementing those other dict dunder methods, that don't require consuming the entire iterator, and don't require some underlying state to record mutations (i.e. not pop ).  I can't think of any others. 

If you know all the possible key values in advance, that dict can be made externally without consuming the iterator, using the same one liner as in your code (with the selfs replaced by the instance name, and the keys).

Also, as well as the contents of more-itertools being composable into wrappers, despite the lower case naming convention, lots of them are classes too, so they can even be subclassed.

**Comment by bbayles** [comment]
Hmm, I think I'd rather point people toward `map_reduce`?

```python
>>> from more_itertools import map_reduce
>>> iterable = [10, 20, 30, 11, 21, 31, 12, 22, 23, 33]
>>> map_reduce(iterable, lambda x: 10 * (x // 10))
defaultdict(None, {10: [10, 11, 12], 20: [20, 21, 22, 23], 30: [30, 31, 33]})
```

**Comment by ScDor** [comment]
@bbayles this is exactly what I was looking for, thank you.
