### ISSUE TITLE
Add powerset_of_sets()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#820]
The existing `powerset()` recipe yields tuples.  If actual sets are needed, the obvious extension `map(set, powerset(iterable))`, does not perform well because the `__hash__()` method is called `n * 2**(n-1)` times.

A better approach is to create sets of size 1 and them merge them as needed with `set.union` which reuses the hash values cached in the input sets.

```
def powerset_of_sets(iterable):
    "Return sets of a powerset calling hash() only once per element."
    # powerset_of_sets([1,2,3]) --> set() {1} {2} {3} {1,2} {1,3} {2,3} {1,2,3}
    sets = list(map(set, zip(iterable)))
    for r in range(len(sets) + 1):
        yield from starmap(set().union, combinations(sets, r))
```

Demonstration:

```
from fractions import Fraction

class F(Fraction):
    def __hash__(self):
        "Print a dot every time hash is called"
        print('.', end='')
        return super().__hash__()

>>> _ = list(map(set, powerset(map(F, range(5)))))
................................................................................
>>> _ = list(map(set, powerset_of_sets(map(F, range(5)))))
.....
```

**Comment by pochmann3** [comment]
What should `powerset_of_sets([1,2,2])` yield? Your code yields `set() {1} {2} {2} {1, 2} {1, 2} {2} {1, 2}`. Would it be better to apply `set()` to the input so it yields `set() {1} {2} {1, 2}`?

**Comment by rhettinger** [comment]
> Would it be better to apply set() to the input so it yields set() {1} {2} {1, 2}?

That makes sense because the mathematical powerset operation is only defined on sets. However it does double the number of hash calls and it generates the sets in a non-deterministic order.

This variant handles all those issues:

```
from itertools import starmap, combinations

def powerset_of_sets(iterable):
    sets = tuple(map(set, dict.fromkeys(map(frozenset, zip(iterable)))))
    for r in range(len(sets) + 1):
        yield from starmap(set().union, combinations(sets, r))
```

Tech notes: 

* The `map(frozenset, zip(iterable))` step makes the sole call to `hash()`.
*  The `frozenset()` type caches its hash value so that its component elements never get rehashed.
*  The `dict.fromkeys(...)` step eliminates duplicates but maintains input order.
*  The `map(set, ...)` step converts the frozensets to the final output type.

Test code:

```
import sys

class Str(str):
    def __hash__(self):
        print('.', end='', file=sys.stderr)
        return str.__hash__(self)

for s in powerset_of_sets(map(Str, 'ABBBCDD')):
    print(s)
```

Output:

```
.......
set()
{'A'}
{'B'}
{'C'}
{'D'}
{'A', 'B'}
{'A', 'C'}
{'A', 'D'}
{'B', 'C'}
{'B', 'D'}
{'C', 'D'}
{'A', 'B', 'C'}
{'A', 'B', 'D'}
{'A', 'C', 'D'}
{'B', 'C', 'D'}
{'A', 'B', 'C', 'D'}
```

**Comment by Wolf-SO** [comment]
> What should `powerset_of_sets([1,2,2])` yield? Your code yields `set() {1} {2} {2} {1, 2} {1, 2} {2} {1, 2}`. Would it be better to apply `set()` to the input so it yields `set() {1} {2} {1, 2}`?

I'd pled for the latter. On the other hand, isn't the [power set](https://en.wikipedia.org/wiki/Power_set) by definition a deduced from a set? So it might be better to restrict the input to a `set`.
