### ISSUE TITLE
distinct_permutations with incomparable items

### ISSUE THREAD

**Issue by hgustafsson** [more-itertools/more-itertools#832]
Because `distinct_permutations` uses `sorted` and `<` it is not possible to input incomparable items.

This is unexpected since the documentation claims that `distinct_permutations` is equivalent to `set(permutations(iterable)`.

Example:
```
>>> set(itertools.permutations(["+","+",0,1]))

{('+', '+', 0, 1),
 ('+', '+', 1, 0),
 ('+', 0, '+', 1),
 ('+', 0, 1, '+'),
 ('+', 1, '+', 0),
 ('+', 1, 0, '+'),
 (0, '+', '+', 1),
 (0, '+', 1, '+'),
 (0, 1, '+', '+'),
 (1, '+', '+', 0),
 (1, '+', 0, '+'),
 (1, 0, '+', '+')}

>>> more_itertools.distinct_permutations(["+","+",0,1])

... more_itertools/more.py:742, in distinct_permutations(iterable, r)
--> 742 items = sorted(iterable)

TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by JamesParrott** [comment]
The ordering is heavily used by the implementation and perhaps the docs should mention that.

Is the order of the permutations themselves important to anyone?:

```
>>> list(more_itertools.distinct_permutations([-1,-1,0]))
[(-1, -1, 0), (-1, 0, -1), (0, -1, -1)]
>>> list(more_itertools.distinct_permutations([2,2,0]))
[(0, 2, 2), (2, 0, 2), (2, 2, 0)]
```

Otherwise a list of unique unsortable symbols could be formed, and distinct_permutations called on the index in that list, of each symbol in the list containing duplicates.

**Comment by bbayles** [comment]
I'll accept a patch that makes it work for non-comparable items. We can add a note about the order not being guaranteed. Thanks!

**Comment by JamesParrott** [comment]
Awesome.  How does this look to you?

https://github.com/more-itertools/more-itertools/pull/834/files

**Comment by JamesParrott** [comment]
I've added some tests.  There are a few issues so please bear with me while I sort them.

**Comment by JamesParrott** [comment]
The tests are all passing now :)

**Comment by pochmann3** [comment]
`distinct_permutations([1, True, 'love'])` yields `(1, 1, 'love')`, `(1, 'love', 1)` and `('love', 1, 1)`. Doesn't look good. I think all elements should appear.

**Comment by JamesParrott** [comment]
Quite right.  It sneaks past assertEqual too, as `True == 1`, so the test I just added is a false positive.  It's midnight here now, I'll look at how itertools.permutations handles this tomorrow.

**Comment by pochmann3** [comment]
That was just a toy example, in reality I'd rather expect people to use objects of the same type, so that wouldn't suffice. One idea I have is to not use `int` values representing indexes but directly attaching the elements to those `int` values:

```python
class Node(int):
    pass

a, a.value = Node(3), 'foo'
b, b.value = Node(4), 'bar'

print(a < b, b < a, a.value, b.value)
```

Output ([Attempt This Online!](https://ato.pxeger.com/run?1=m72soLIkIz9vwYKlpSVpuhY3K5NzEouLFfzyU1I1MvNKNK24FICgACjGxZWoo5CoV5aYU5qqYAtRYaypo6Celp-vzpWko5CEKmcCkktKLFLn4iooAhqlkahgowBSBqQQJsG1aUIcAHUHzD0A)):
```
True False foo bar
```

Then permute those `Node` objects and build the output tuples like this:

```python
            return (
                tuple(node.value for node in permutation)
                for permutation in algorithm(nodes)
            )
```

**Comment by JamesParrott** [comment]
@pochmann3 
`1==True` is literally required by the Python language spec.  Perhaps more_itertools users must be ever vigilant of naively comparing ints to bools, just the same as all Python users must.

Nonetheless, I can fix it within the scope of the patch for incomparable items, but this `1==True` issue is a different one in its own right to incomparable items, it also affects the existing implementation of distinct_permutations, and CPython's core itertools too:

```
>>> set(itertools.permutations([1,2,3]))
{(1, 3, 2), (1, 2, 3), (2, 1, 3), (3, 2, 1), (3, 1, 2), (2, 3, 1)}
>>> set(itertools.permutations([1,2,True]))
{(1, 2, True), (2, 1, True), (1, True, 2)}
>>> set(more_itertools.distinct_permutations([1,2,True]))
{(1, 2, True), (2, True, 1), (1, True, 2)}
>>> set(more_itertools.distinct_permutations([1,2,'a']))
Traceback (most recent call last):  ...  '<' not supported between instances of 'str' and 'int'
```
(the last two lines show I had not imported the branch I'm working on that alters this behaviour)

I'm not sure why itertools yields `(2, 1, True)` and distinct_permutations yields `(2, True, 1)`, but the underlying cause behind both is assuming two permutations `x` and `y` are the same if `x.__eq__(y)` is True.

**Comment by pochmann3** [comment]
Yes, and `(2, 1, True)` and `(2, True, 1)` are both alright. But yielding `(2, 1, 1)` or `(2, True, True)` instead would be wrong, as those aren't permutations of `[1,2,True]`.

**Comment by JamesParrott** [comment]
What about the other three permutations that are missing?

**Comment by JamesParrott** [comment]
I've been assuming the requirement is to distinguish between `1` and `True` (even though the `set` in `set(itertools.permutations(...))` does not).  Perhaps this assumption was incorrect?

I suspect I need to come back to this after I've had chance to think over the requirement.  But I've added support for distinguishing between `1` and `True` in nested containers, in this branch:

https://github.com/JamesParrott/more-itertools/tree/Fix_Nested_1%3D%3DTrue

**Comment by JamesParrott** [comment]
I've got rid of the `type`-tagging using a default dict to let `__eq__`ual items share an index, but retain their different values, so I think I've sorted this finally.
https://github.com/JamesParrott/more-itertools/commit/ed201a263eef095bccae03f148c0e43f22e5f615

Let me know if there are any other edge cases.

**Comment by pochmann3** [comment]
Maybe this example helps. Imagine you're a supermarket manager and you want to arrange 12 products in a line: 3 brands of toothpastes, 5 brands of soap, and 4 brands of creme. You want to try all possible arrangements, but you don't care about the order within the toothpastes, within the soaps, and within the cremes, meaning all toothpastes are equal, and the same for the soaps and cremes. Now with your index solution you'd get arrangements of 3 times a certain toothpaste, 5 times a certain soap, and 4 times a certain creme. But that's not what you want. You want all 12 products there. (And to be clear, the type is `Product`.)

**Comment by JamesParrott** [comment]
That's a great analogy - thanks.  I think I've got it sorted now with the latest commit, (as long as the particular sub arrangement of toothpastes, soaps and creme brands is unimportant)

**Comment by pochmann3** [comment]
Yes, with those iterators that looks right (haven't tested it, maybe later). That's another idea I had as well. A variation of that would be to create a dict of `cycle` iterators beforehand, then you wouldn't need to build a new dict for every permutation.

**Comment by JamesParrott** [comment]
I've made a branch to investigate using `cycle` iterators.  They behave the same when r=n, but when r=2, a different equivalent  from a cycle may be yielded, returning different permutations to `set(itertools.permutations(..., r=2)`.  

```
>>> s1 = set(itertools.permutations([1, True, "Love"], 2))
>>> s1
{(1, True), (1, 'Love'), ('Love', 1)}
>>> s2 = set(more_itertools.distinct_permutations([1, True, "Love"], 2))
>>> s2
{(1, True), (1, 'Love'), ('Love', True)}
```
https://github.com/JamesParrott/more-itertools/tree/cycles_not_dict

When `r` isn't specified (or is n) this should never be a problem of course, as the sum of the lengths of all the input iterables into the `cycle`s (n) equals the length of the yielded permutations, so there would be precisely `n` calls to `next` on the `cycle`s.

**Comment by pochmann3** [comment]
I consider it a feature :-). Makes the equal elements occur equally often (as much as that's possible). As the supermarket manager, I prefer that. Better than always having the first soap and rarely having the last soap. Or if it's not emotionless products but *people*, like members of sports teams, then it's nicer if each team's members get to play equally often.

If it's desired (I'm not sure it is) to truly get the same tuples as `set(itertools.permutations(...))` with consideration to the order/selection of the elements, then the current algorithms are broken already, as they don't do that.

<details><summary>A comparison with `set(permutations(...))`</summary>

```python
from itertools import permutations
from more_itertools import distinct_permutations

iterable = [0, 0.0, False, 1, 1.0, True]
r = 4

expect = {p: p for p in set(permutations(iterable, r))}

for p in distinct_permutations(iterable, r):
    print(expect[p])
    print(p)
    print()
```

Output comparing pairs of what itertools and more-itertools yield:

```
(0, 0.0, False, 1)
(0, 0.0, False, 1)

(0, 0.0, 1, False)
(0, 0.0, 1.0, False)

(0, 0.0, 1, 1.0)
(0, 0.0, 1.0, True)

(0, 1, 0.0, False)
(0, 1, False, 0.0)

(0, 1, 0.0, 1.0)
(0, 1, False, True)

(0, 1, 1.0, 0.0)
(0, 1, 1.0, 0.0)

(0, 1, 1.0, True)
(0, 1, 1.0, True)

(1, 0, 0.0, False)
(True, False, 0.0, 0)

(1, 0, 0.0, 1.0)
(True, False, 0.0, 1.0)

(1, 0, 1.0, 0.0)
(True, False, 1, 0)

(1, 0, 1.0, True)
(True, False, 1, 1.0)

(1, 1.0, 0, 0.0)
(True, 1.0, 0.0, 0)

(1, 1.0, 0, True)
(True, 1.0, 0.0, 1)

(1, 1.0, True, 0)
(True, 1.0, 1, False)
```

</details>

**Comment by bbayles** [comment]
Thanks for the contribution - this will be in the next release!
