### ISSUE TITLE
is filter_map needed?

### ISSUE THREAD

**Issue by dgrigonis** [more-itertools/more-itertools#838]
```python
import more_itertools as mitl
a = range(100_000)
l = lambda x: x if x % 2 else None
%timeit list(mitl.filter_map(l, a))     # 12.6 ms
%timeit list(filter(None, map(l, a)))   #  9.3 ms
```

**Comment by pochmann3** [comment]
In general, your alternative removes more than just `None`.

And have you read [why `filter_map` was added](https://github.com/more-itertools/more-itertools/issues/763)?

**Comment by dgrigonis** [comment]
> In general, your alternative removes more than just `None`.
> 
> And have you read [why `filter_map` was added](https://github.com/more-itertools/more-itertools/issues/763)?

Yes, I see now. Thank you for the reference and apologies for disturbance.
