### ISSUE TITLE
Enhance repeat_each to allow different number of repeats for each element

### ISSUE THREAD

**Issue by Azureuse** [more-itertools/more-itertools#844]
### Description
[`repeat_each`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.repeat_each) currently repeats each elements in the iterable `n` times:
```python
list(repeat_each('ABC', 3))
['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C']
```

I propose a slight modification to allow both ints and Sequences of ints to be passed as the `n` arguement, thus allowing each element to be repeated a different number of times. 
```python
list(repeat_each('ABC', [3, 1, 2]))
['A', 'A', 'A', 'B', 'C', 'C']
```

This would also allow the original proposer's variation to be composed where each element is repeated an increasing number of times (see https://github.com/more-itertools/more-itertools/issues/532).
```python
list(repeat_each('ABC', count(1, 2)))
['A', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C']
```

Thus I propose replacing 
```python
def repeat_each(iterable, n=2):
    return chain.from_iterable(map(repeat, iterable, repeat(n)))
```
with something like
```python
def repeat_each(iterable, n=2):
    if isinstance(n, int):
        n = [n]
    return chain.from_iterable(map(repeat, iterable, cycle(n)))
```

Which would result in behaviours like
```python
list(repeat_each('ABC', [3, 1]))
['A', 'A', 'A', 'B', 'C', 'C', 'C']
```

### References
Original proposal for `repeat_each`: https://github.com/more-itertools/more-itertools/issues/532

### Examples
Copied from above
```python
list(repeat_each('ABC', 3))
['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C']

list(repeat_each('ABC', [3, 1, 2]))
['A', 'A', 'A', 'B', 'C', 'C']

list(repeat_each('ABC', count(1, 2)))
['A', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C']

list(repeat_each('ABC', [3, 1]))
['A', 'A', 'A', 'B', 'C', 'C', 'C']
```

**Comment by bbayles** [comment]
Thanks for the suggestion. I think this might be slicing things too thin. If we can come up with examples of people on StackOverflow or GitHub writing similar code to solve this problem I'll reconsider.

Thanks again!
