### ISSUE TITLE
Speed up `consume` and `ilen` with deque prepared once?

### ISSUE THREAD

**Issue by pochmann3** [more-itertools/more-itertools#848]
What do you think about preparing one `deque(maxlen=0).extend` when more-itertools loads and using that in `consume` / `ilen` instead of always creating a new deque? Here's a direct comparison with an empty iterable. Creating a new deque takes about 300 ns longer:

```
339 ns  deque(iterator, maxlen=0)
26 ns  extend(iterator)
```

<details><summary>Benchmark script</summary>

```python
from timeit import repeat 

setup = '''
from collections import deque
extend = deque(maxlen=0).extend
iterator = iter([])
'''

for code in [
    'deque(iterator, maxlen=0)',
    'extend(iterator)',
] * 3:
    print(round(min(repeat(code, setup, number=10**3, repeat=100)) * 10**6), code)
```

[Attempt This Online!](https://ato.pxeger.com/run?1=PZBNjsIwDIXFNpfAuyRVBhUhIYTUkyAWndYVkZofgiPBWdiwmTnUnGbyQ8kqtr88573nr3_QxdnX6yfS9HX4W62n4AyQNqgJtPEuEAT02BMwdkOKHjrgnLPCDW6ecSDt7G2BR7xGZHgntGNCSylMf5_Rdq3c1AHThKEnFxKRr-J0liyrsin1BjciaAsnBunwKrG8UPAR46oCVfND5P4ZGtgdy9gHbUkEFxNitBXVjchLFBRHCmw03xi6bds0O_X2m6pWyqSTu3upyrdkzekd1xLbPw)

</details>

**Comment by rhettinger** [comment]
Something like this?

```
# Micro-optimization to save deque instantiaton time
# at the expense of slower start-up time and unrecoverable memory use.
# Does not change the inner-loop speed.
_consume_all = deque(maxlen=0).extend

def consume(iterator, n=None):
   "Advance the iterator n-steps ahead. If n is None, consume entirely."
   # Use functions that consume iterators at C speed.
   if n is None:
       _consume_all(iterator)
   else:
       next(islice(iterator, n, n), None)
```

**Comment by Naresh1jadhav** [comment]
🥂

**Comment by bbayles** [comment]
I'm changing my mind on this after PR #894 - there's no more `deque` in `ilen`.
