### ISSUE TITLE
Issues with sample()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#854]
I've only just started looking at this and have a few thoughts.

The comparison to the standard library should mention:

* The `counts` parameter in the `random.sample()` is not comparable to `weights` in `more_itertools.sample()`
The former allows an element to be selected multiple times to model classic "urn problems".  The latter just affects the likelihood of an element being selected at all.

* The standard library `random.sample()` raises an exception if *k* is larger than the population.  However `more_itertools.sample()` just returns the population unchanged and in order:

```
>>> import more_itertools
>>> more_itertools.sample(range(10), k=15)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

>>> import random
>>> random.sample(range(10), k=15)
Traceback (most recent call last):
   ...
ValueError: Sample larger than population or is negative
```
* The standard library `random.sample()` guarantees the results to be fully shuffled.  In contrast, the `more_itertools.sample()` initial reservoir fill is not shuffled at all:

```
>>> import more_itertools
>>> import random

>>> random.seed(8675309)
>>> more_itertools.sample(range(2000), k=1990)[:15]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

>>> random.seed(8675309)
>>> random.sample(range(2000), k=1990)[:15]
[823, 438, 1044, 1923, 1359, 1032, 1762, 1838, 575, 1764, 1313, 1674, 1325, 1386, 465]
```

It would be great if a `random.shuffle()` step were added at the end. If not, then a `sorted()` step would be an improvement over having a result that is neither randomized or sorted.

**Comment by bbayles** [comment]
Thanks for the suggestions. Here is a PR with some improvements: https://github.com/more-itertools/more-itertools/pull/855
