### ISSUE TITLE
Extend set_partitions with max_size, min_size parameters

### ISSUE THREAD

**Issue by JPBotelho** [more-itertools/more-itertools#856]
### Description
Allow an optional parameter to be passed onto set_partitions that sets the maximum size per block in the partition. 
Allow a similar parameter for the minimum size of the blocks.

If there is interest I can have a look at implementing this. There might be more efficient algorithms than the recursive one used now ( see https://link.springer.com/chapter/10.1007/3-540-52921-7_57 ). It might even be possible to use an algorithm that allows for parallelization (split generation space into K, execute iterative algorithm starting at each split).

### References
These correspond to restricted and associated Stirling numbers of the second kind: 
https://setpartitions.org/associatedStirling.html
https://setpartitions.org/restrictedStirling.html

### Examples

Current usage (still valid):
```
iterable = 'abc'
for part in set_partitions(iterable):
    print([''.join(p) for p in part])

['abc']
['a', 'bc']
['ab', 'c']
['b', 'ac']
['a', 'b', 'c']
```
Proposed:
```
iterable = 'abc'
for part in set_partitions(iterable, max_size=2):
    print([''.join(p) for p in part])

['a', 'bc']
['ab', 'c']
['b', 'ac']
['a', 'b', 'c']
```

```
iterable = 'abc'
for part in set_partitions(iterable, min_size=2):
    print([''.join(p) for p in part])

['abc']
```

**Comment by bbayles** [comment]
I'll definitely accept a PR that changes the `set_partitions` implementation from recursive. If you're willing to do that, go for it!
