### ISSUE TITLE
seekable relative_seek() behaviour is confusing

### ISSUE THREAD

**Issue by dkrikun** [more-itertools/more-itertools#862]
Based on the example from the docs:
```
>>> it = seekable((str(n) for n in range(20)))
>>> it.seek(10)
>>> next(it)
'10'
>>> it.relative_seek(-2)  # Seeking relative to the current position
>>> next(it)
'9'
```

At this point, I would expect the following:
```
>>> it.relative_seek(-2)
>>> next(it)
'8'
```
However, the actual return value is '`9`'.
The reason for that is that, as far as I understand, the method is not actually seeking relative to the current position, but to the end of internal buffer.

**Comment by pochmann3** [comment]
So `next(it)` gives you `'9'` instead of `'11'`. That's -2, as requested.

**Comment by bbayles** [comment]
Thanks for the discussion. I think the current behavior is what is intended, so if there is a documentation update that can help potential users understand what will happen, I am open to suggestions.

**Comment by m9810223** [comment]
Hi @dkrikun, please look for `*` in the code below.

```python
it = seekable((str(n) for n in range(20)))

it.seek(10)

# ...   9 * 10   11 ...

next(it) # => '10'

# ...   9   10 * 11 ...

it.relative_seek(-2)

# ... * 9   10   11 ...

next(it)  # => '9'

# ...   9 * 10   11 ...

```

**Comment by dkrikun** [comment]
I think there have been a misunderstanding (in fact I am sure there is one, but I think I had not explained the case properly).

The example code calls `relative_seek(-2)` **twice**:
```
>>> it = seekable((str(n) for n in range(20)))
>>> it.seek(10)
>>> next(it)
'10'
>>> it.relative_seek(-2)  # Seeking relative to the current position
>>> next(it)
'9'
>>> it.relative_seek(-2)
>>> next(it)
'9'
```
The second seek should be relative to the position after the first one, but it isn't

**Comment by bbayles** [comment]
https://github.com/more-itertools/more-itertools/pull/863 has a documentation change that clarifies that the "relative" is relative to the position in the source iterator.

Does that help explain what's going on?
![image](https://github.com/more-itertools/more-itertools/assets/1922815/5da287a8-d1be-4c06-a60f-7a931438648a)

**Comment by dkrikun** [comment]
Yes, thank you, it does

**Comment by dkrikun** [comment]
I still do not understand however why that behavior is desired.
From the user point of view, why would one want to track where one is within the cache? Either you seek forward and you get the newer items or you seek backwards and you get the older ones (as long as the cache size so permits).
However, with the current behaviour, when one seeks forward the underlying iterator will be advanced, new items will be pulled into the cache and the user will receive them. When the user seeks backward *once* he will get older items, relative to the current position. But when the user seeks backwards once again -- he will get the items he will probably did not expect -- because the seek has been performed relative to the cache head.

**Comment by bbayles** [comment]
I'll accept a PR that makes the relative seek "stick," since it doesn't look like a ton of people are relying on the existing behavior.

**Comment by dkrikun** [comment]
Will do
