### ISSUE TITLE
Simplify and speed-up _sample_unweighted()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#864]
Edits:
* Move the redundant set-up code inside the loop.
* Replace `enumerate` and the `next_index` test with a much faster `islice` operation.
* Inline the `take()` call so that the core logic is solely expressed in terms of `islice`.
* Remove the confusing comments, and let the paper speak for itself.

This new code is faster, shorter, more readable, and produces exactly the same selections as the existing code:

```
def _sample_unweighted()(iterator, k):
    # Algorithm L in the 1994 paper by Kim-Hung Li:
    # "Reservoir-Sampling Algorithms of Time Complexity O(n(1+log(N/n)))".

    reservoir = list(islice(iterator, k))
    W = 1.0

    with suppress(StopIteration):
        while True:
            W *= exp(log(random()) / k)
            skip = floor(log(random()) / log(1.0 - W))
            element = next(islice(iterator, skip, None))
            reservoir[randrange(k)] = element

    shuffle(reservoir)
    return reservoir
```

The existing comments were challenging to read. I wasn't able to connect the Wikipedia OrderStatistics article to the `W` multiplicative update. For me, here were the keys to understanding the code:

* Conceptually  each selection in the reservoir is associated with a `random()` value.
* `W` is the largest of those random values.
* The `exp(log(random()) / k)` means the same as `betavariate(k, 1)`.
* "Geometric distribution" has two possible interpretations. The`floor(log(random()) / log(1.0 - p))` formula corresponds to, "expected number of failures before the first success" where `p` is the probability of a successful Bernoulli trial.

**Comment by bbayles** [comment]
Thanks, this looks great. I added back in the `strict` checks for PR #865.

**Comment by tommyod** [comment]
@rhettinger I wrote this code around 5 years ago, and I am happy to see that you of all people have reviewed it. Around 10 years ago when I was learning to program, I distinctly remember finding your talks on YouTube and learning so much from them. Seeing that you of all people touched my code and improved it really made my day. Keep up the good work!
