### ISSUE TITLE
`is_sorted`: don't double-negate

### ISSUE THREAD

**Issue by pochmann3** [more-itertools/more-itertools#876]
The comparisons are all the opposite of what you'd expect from the flags. It's confusing/irritating:

```python
def is_sorted(iterable, key=None, reverse=False, strict=False):
    compare = (le if reverse else ge) if strict else (lt if reverse else gt)
```

And results are fed to `not any`:

```python
    it = iterable if key is None else map(key, iterable)
    return not any(starmap(compare, pairwise(it)))
```

Better use the straightforward comparison and simply `all`. Or if there's a good reason for the current way (I couldn't find one), there should be a comment explaining it.

Proposal:

```python
def is_sorted(iterable, key=None, reverse=False, strict=False):
    compare = (gt if reverse else lt) if strict else (ge if reverse else le)
    it = iterable if key is None else map(key, iterable)
    return all(starmap(compare, pairwise(it)))
```

I suspect the current way is like it is because it previously did the following, to avoid a `not` operation for every element (although I think at least CPython would optimize that away anyway):

```python
    for a, b in pairwise(it):
        if compare(a, b):
            return False

    return True
```

**Comment by pochmann3** [comment]
Another advantage: currently `is_sorted([3, float('nan'), 1, 2])` returns `True`. My proposal returns `False`.

**Comment by bbayles** [comment]
I think the output should be `True` if `x == sorted(x)`.

```
In [2]: A = [3, float('nan'), 1, 2]

In [3]: A.sort()

In [4]: A
Out[4]: [3, nan, 1, 2]
```

**Comment by pochmann3** [comment]
Does that really look sorted to you? The 3 comes before the 1. Are they "in sorted order"? I think that case is neither sorted nor sortable (and `sort()`/`sorted()` don't actually successfully sort it but fail to sort it).

**Comment by bbayles** [comment]
I'll accept a PR that clarifies that the intention is to match sorted.

**Comment by pochmann3** [comment]
That's not even what it does, though. For example:

```python
from more_itertools import is_sorted

class X:
    def __lt__(a, b):
        return False
    def __gt__(a, b):
        return True

x = [X(), X()]
print(f'{x == sorted(x)   = }')
print(f'{is_sorted(x)     = }')
```

Output:
```
x == sorted(x)   = True
is_sorted(x)     = False
```

Should we fix it?

**Comment by bbayles** [comment]
Yes, if it does not match what `sorted` does, I'll take a PR to fix it.

**Comment by pochmann3** [comment]
Actually it's pretty much impossible to guarantee it matches `sorted`, since that depends on implementation details. But we can match current CPython's `sorted`:

```python
def is_sorted(iterable, key=None, reverse=False, strict=False):
    compare = le if strict else lt
    it = iterable if key is None else map(key, iterable)
    it1, it2 = tee(it)
    next(it2 if reverse else it1, None)
    return not any(map(compare, it1, it2))
```

Since `sorted` doesn't have a `strict` parameter, there is no reference behaviour for it. I chose to use `le` instead of `lt` then.

It passed my testing with all sequences up to length 7 and values from `1, 2, 3, float('nan'), X()`. The current code failed a lot.

Testing script:

```python
from operator import *
from itertools import *


def is_sorted(iterable, key=None, reverse=False, strict=False):
    compare = le if strict else lt
    it = iterable if key is None else map(key, iterable)
    it1, it2 = tee(it)
    next(it2 if reverse else it1, None)
    return not any(map(compare, it1, it2))


class X:
    def __lt__(a, b):
        return False
    def __gt__(a, b):
        return True
    def __repr__(_):
        return 'X'

pool = 1, 2, 3, float('nan'), X()
for n in range(8):
    for x in map(list, product(pool, repeat=n)):
        for reverse in False, True:
            expect = x == sorted(x, reverse=reverse)
            result = is_sorted(x, reverse=reverse)
            if result is not expect:
                print(reverse, x, expect, result)
print('done')
```

[Attempt This Online!](https://ato.pxeger.com/run?1=hZO9btwwDMeHbn6AztwsBeqQdAkKeM2YKcNthuKjU6E6SaDowPcsXbK0D5WnKWXpPoKiqBZZ9I9_kiL183c68vcY3t5-LTx_uX__9HmmeICYkCxHAndIkRhuus3sGIlj9Pli77o9zuDymOWMe1UQ--zRwA88Do8xyBfhK1LG4cH6LMfM5CauJ_2tA1lTPCRLCAN4BDc3BFAI8LwhjuXvSb0woi9xoYSo4MEmJUZzpnRzvC2mO3FnREmwmgOurIpZpFqCVWbji2rlCHmhACEy2HBUJUjL1pyltZZ7mLzNGXa1oHIp4-h5HJU18NzKvNLbqr9CX_6NPtFyTRImEnb8G-x3fdcl6Y-UKondGfhqYPbRsuqDDb02sFO6m6WvAVwAsuEF1X0TKua1mEuJ3mU2kCjul4lV0SxtTGh5CPoqcnE63Z5rVZkt4wtTFq4Jp9LBFYYB2qysl9Fou_7gRJgXv7X9PF7_c9mauXnJaJSe1cAfkykrkQusmoYB0a2kaf66q0S_l0nodX0e7ZWcXssf)

**Comment by pochmann3** [comment]
> But we can match current CPython's `sorted`:

Actually we can't even do *that*, if we only compare neighbor elements.

Consider `ys = list(range(200))`, but with a special 100 that *lies* the first time it is asked, saying it's smaller than 99. So `is_sorted` sees that as proof that the list isn't sorted and immediately reports `False`. While `sorted` also sees that proof, it merely splits the list into two sorted runs, and when it merges them, the 100 doesn't lie again and so `sorted` doesn't actually change the list.

Maybe this is possible with "normal" but still inappropriate elements as well, like sets. I can imagine there's a list of sets where `sorted` at first finds unordered pairs but then the comparisons that happen during merging actually leave all sets where they are. Whereas `is_sorted` right away reports `False`.

All that said, I'd say my "lying 100" case is absurd and malicious and I don't think we need to care about it. Neither about potential cases inappropriate for sorting  like with such sets (if that indeed exists). Maybe also not about inappropriate cases like with nans or my earlier X.

But we can still get *closer*, and my above suggestion has the advantage of only using `<`, like `sorted` (unless using `strict=True`). And it seems to be faster, except for the tiniest iterables.

<details><summary>lying 100</summary>

```python
from itertools import pairwise

class Y:
    def __init__(self, value):
        self.value = value
        self.lie = value == 100
    def __lt__(self, other):
        result = self.value < other.value
        if not self.lie:
            return result
        self.lie = False
        return not result

def data():
    return list(map(Y, range(200)))

ys = data()
print(sorted(ys) == ys)

ys = data()
print(not any(b < a for a, b in pairwise(ys)))
```

Output ([Attempt This Online!](https://ato.pxeger.com/run?1=bZHBTsMwDIbFNU_hYyKVqXBCiF73DjtVHk2YpTSpEhfUZ9lll_EevAZPQ0JK16H5Esn-_f2OffwcJj54dzqdRzb3T993Xyb4Hoh1YO9tBOoHHxgGpPBBUQvxajFG2D0LSNFpA21LjrhtZdTWVPCOdtSqlHPk7OY3CU0pXpcsLQVoGnio6xXZXrieDzqsuEHH0XJqXRm8FNXm2oYMOM-L2wVRMDwGN9NuTbZFG7X4J8-8uUXkSTtklPNws8RSZNnjIHcVBHRvWj7WtVJKiCkmbOkQQyDHMqYV605OUeUVpOeWKHuim-Q-fRPB-ABYwR7ILcfJAKXKJeeD_h32Bw)):

```
True
False
```

</details>

**Comment by bbayles** [comment]
[PR 867](https://github.com/more-itertools/more-itertools/pull/877) adopts the implementation [here](https://github.com/more-itertools/more-itertools/issues/876#issuecomment-2216000809).

**Comment by pochmann3** [comment]
Some test results:

```none
current failed 865 tests
proposal failed 0 tests

1 elements
421.8 ± 1.8 ns  current
629.9 ± 2.1 ns  proposal

10 elements
  1.0 ± 0.0 μs  current
  1.0 ± 0.0 μs  proposal

100 elements
  6.3 ± 0.1 μs  current
  4.6 ± 0.0 μs  proposal

1000 elements
 59.3 ± 0.4 μs  current
 40.8 ± 0.1 μs  proposal

10000 elements
583.9 ± 3.3 μs  current
405.0 ± 1.4 μs  proposal

100000 elements
  5.8 ± 0.0 ms  current
  4.0 ± 0.0 ms  proposal

Python: 3.12.2 (main, Jun 12 2024, 09:13:57) [GCC 14.1.1 20240522]
```

<details><summary>script</summary>

```python
from operator import *
from itertools import *
from timeit import timeit
from statistics import mean, stdev
import sys
import random


def current(iterable, key=None, reverse=False, strict=False):
    compare = (le if reverse else ge) if strict else (lt if reverse else gt)
    it = iterable if key is None else map(key, iterable)
    return not any(starmap(compare, pairwise(it)))


def proposal(iterable, key=None, reverse=False, strict=False):
    compare = le if strict else lt
    it = iterable if key is None else map(key, iterable)
    it1, it2 = tee(it)
    next(it2 if reverse else it1, None)
    return not any(map(compare, it1, it2))


funcs = [current, proposal]

class X:
    def __lt__(a, b):
        return False
    def __gt__(a, b):
        return True
    def __repr__(_):
        return 'X'

pool = 1, 2, 3, float('nan'), X()
fails = {f: 0 for f in funcs}
for n in range(8):
    for x in map(list, product(pool, repeat=n)):
        for reverse in False, True:
            expect = x == sorted(x, reverse=reverse)
            for f in funcs:
                result = f(x, reverse=reverse)
                if result is not expect:
                    # print(reverse, x, expect, result)
                    fails[f] += 1
for f in funcs:
    print(f'{f.__name__} failed {fails[f]} tests')

def benchmark(x, number, unit, scale):
    print(f'\n{len(x)} elements')
    fs = funcs[:]
    times = {f: [] for f in funcs}
    def stats(f):
        ts = [t * scale for t in sorted(times[f])[:5]]
        return f'{mean(ts):5.1f} ± {stdev(ts):3.1f} {unit} '
    for _ in range(25):
        random.shuffle(fs)
        for f in fs:
            t = timeit(lambda: f(x), number=number) / number
            times[f].append(t)
    for f in funcs:
        print(stats(f), f.__name__)

benchmark((0,) * 10**0, 100000, 'ns', 1e9)
benchmark((0,) * 10**1, 10000, 'μs', 1e6)
benchmark((0,) * 10**2, 1000, 'μs', 1e6)
benchmark((0,) * 10**3, 100, 'μs', 1e6)
benchmark((0,) * 10**4, 10, 'μs', 1e6)
benchmark((0,) * 10**5, 1, 'ms', 1e3)

print('\nPython:', sys.version)
```

[Attempt This Online!](https://ato.pxeger.com/run?1=pVbBjts2EL0WuvYHBshB5FZ1d73ZIjGga49FDz0s4BgCLQ93iUiUQFKpF4a_pJdc2nvuOfUD-gH9ms6Qktdeb5AFoovE0ZvhvJk3lP78u38I9539-PGvIegf3_z33ffadS10PToVOgem7TsX4CKLZhPQha5r_BN7MC2aMBnTKr3xQQXjg6kPLi0qW5B9gx-y0eQf_PTolN10bZZlG9RQD86hDYK3VesGC3iPD-WvnaUnhx_QeSx_UY1HjudMHdJKLjKgq-7aXjmEEkSDYPTkAkgYuEPJtuSXTKIJ57AgYzBiV8KUB6MoEzAeOJmEbFUvyFgcUMnRYRicBdsFUPZBUD0cI8fkCuiVcX8Yj0RSSjkS713Xd14138w85XpMsgnfxseEKzbNyT1gzDqaLW65T_OzAkY8R322HCelmELHMujBkmZKWI4iKA5FWWVZ3Sjv4Tax5YJVVROqSqgC1mMNjjaLpTmC3n0Z-rsbjpEOe0fY6hyY3-ZZ1tMoUIqU9byA6wJ006kgcqtsLgu4FTLTyjTMYqcXcAmaBkqDsRDJ7TNeW16T6u9QvBm3YfOWzVydhqYnct8MdRC8IyugRxVKK4_yYqep8GbkXEQ-jxi-cNtjzc3fQlmCp5nDjdg-qmq8yxOn08RPA6ai-KHhoPqroaKG9ORBimMppKTO4_L1isgbOgTGaAXQDglfjFHON4g5c-mXegU_UIey5xikuDrf6VlVWdViVe2jG26oYaP7nmTug89lmsw12vq-Ve49E7VDu0ZXwGANJeNr1UwTOIV-Z3cNWrGVe5oGbEnHHCmmx7KIySwXq2jhY3PSynJ1JpZJlXyieqGPWh_inNBhnFKInoE9x-7GwERFLhc3q9VTJRN_PpJF8HJxM7vSe_jnE-zi-Rxt19G2Y457yA8CrR51O785no94gM_8_aB1g0J7eSLRxOiJhFg56aMhGtWuN2rBQpJTgct0k_DTaDh1HtnNVN-jJbYyO93sVLKpM1MRaWYPvacOP3ZXXBaSCnp1eXFxWdCNrwJy63Na4Vv5PPRqhBLy388J-vMXoPMEfQHyOiJfAHzNwBfgbgo-svI2oa6JdyoKqfW3-DewoBf0TZ7xwJnOyvRvMP4iTL8K_wM)

</details>
