### ISSUE TITLE
Improve error message for sliding_window() and add more specializations

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#879]
The current error message for non-positive values of *n* isn't specialized for `sliding_window()`:

> ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.

Two more fast paths can be added:

- When `n==1`, then `sliding_window` is equivalent to `zip()`.
- When `n==2`, then `sliding_window` is equivalent to `pairwise()`.

Here is some suggested dispatch code:

```
def sliding_window(iterable, n):

    if n > 20:
        return _sliding_window_deque(iterable, n)
    elif n > 2:
        return _sliding_window_islice(iterable, n)
    elif n == 2:
        return pairwise(iterable)
    elif n == 1:
        return zip(iterable)
    else:
        raise ValueError(f'n should be at least one, not {n}')
```

**Comment by bbayles** [comment]
Fixed in https://github.com/more-itertools/more-itertools/commit/fc5773f42805fa315e7f7500623f8765a847ccb8 - thanks.
