### ISSUE TITLE
Type hint for collapse base_type should accept a tuple of types

### ISSUE THREAD

**Issue by jbosboom** [more-itertools/more-itertools#885]
`collapse`'s `base_type` argument is currently hinted as `type | None`.  It should accept `tuple[type, ...]`.

`isinstance` also accepts `types.UnionType`.  Passing a union is (was?) slower than a tuple of types, so maybe it's fine to leave unions out as a nudge.

Compare `always_iterable`'s `base_type` argument, which is hinted as `type | tuple[type | tuple[Any, ...], ...] | None`.  I'm surprised by the `Any`, so I haven't gone straight to a pull request.

**Comment by bbayles** [comment]
I'll accept a PR that improves the situation -t hanks.
