### ISSUE TITLE
Add a strict option to sort_together()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#890]
A *strict* option would detect data size mismatches. This would avoid silently dropping data:

```
>>> iterables = [(4, 3, 2, 1), ('a', 'b', 'c')]
>>> sort_together(iterables)
[(2, 3, 4), ('c', 'b', 'a')]
```

**Comment by bbayles** [comment]
Good suggestion! I'll accept a PR that does this, or do it myself if there are no volunteers.
