### ISSUE TITLE
Improve ilen() clarity and speed.

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#894]
Stefan Pochmann came up with this new way to write `ilen()`:

```
from itertools import compress, repeat

def ilen(iterable):
    return sum(compress(repeat(1), zip(iterable)))
```

Besides being shorter and faster, it is more readable with a point-free functional style that doesn't rely on side-effects. The only "trick" is using `zip()` to wrap the input with 1-tuples which `compress()` reads as true values. It is rather creative, yet each function call is being used in a canonical way.  

Over a dozen other ideas were kicked around (some even a little faster), but none of the fastest were as clear and straight-forward as this one. Also, this variant is likely to be the most stable across different builds on Python (everything that makes it fast has long been stable and is unlikely to change during the current flurry of interpreter evolution).  Code like this really shows off what can be done with an "iterator algebra" that composes existing fast, memory friendly tools to make something new.

**Comment by bbayles** [comment]
Thanks for the writeup. Here are the implementations that have been in this library:

```python
sum(1 for _ in iterable)
```

```python
d = deque(enumerate(iterable, 1), maxlen=1)
return d[0][0] if d else 0
```

```python
length = 0
for length, _ in enumerate(iterable, 1):
    pass
return length
```

```python
counter = count()
deque(zip(iterable, counter), maxlen=0)
return next(counter)
```

There were performance tests done in [this issue](https://github.com/more-itertools/more-itertools/pull/236#issuecomment-437671525), back in 2018.

I think the implementation should either be the first one, or the one that's the fastest despite being very ugly. Do you think there's an argument for something in between?

**Comment by rhettinger** [comment]
> Do you think there's an argument for something in between?

Yes. I recommend picking the most beautiful of the fast variants. In particular, really like Pochmann's version.  Besides being faster than any of the other variants listed above, it is a quintessential functional-style iterator chain (it was a goal of the *itertools* module to make something like this possible).

To me, the other variants, except for `sum(1 for _ in iterable)`, look like they are fighting the language.  I also like that what makes Pochmann's version fast is stable across versions and builds of Python.  Unlike some of the other variants I've seen, it is not chasing a particular build and version combination into a local minimum.

**Comment by bbayles** [comment]
This change will go in [release 10.4.0](https://github.com/more-itertools/more-itertools/pull/893).

Future proposals for `ilen` improvements should be at least 10x faster and 10x more beautiful.

**Comment by pochmann3** [comment]
The post/thread where this came from, with the many solutions and benchmarks:

https://discuss.python.org/t/challenge-quest-for-counting-iterator-length-at-c-speed/60042/9
