### ISSUE TITLE
all_equal() improvement

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#896]
The `all_equal()` recipe in the main itertools docs was chosen because it is a one liner, it is reasonably clear, and it nicely shows off how various tools can be chained together in a functional style.  

For the production version in `more-itertools`, we can do better (faster startup overhead and fewer dependencies):

```python
def all_equal(iterable, key=None):
    "Returns True if all the elements are equal to each other."
    # all_equal('4٤௪౪໔', key=int) → True

    iterator = groupby(iterable, key=key)
    try:
        next(iterator)
        next(iterator)
    except StopIteration:
        return True
    return False
```

Here are some timings that demonstrate reduced overhead for each of the cases (zero groups, one group, two or more groups):

```
% python3.13 -m timeit -s 'from itertools import islice, groupby' -s 'key=None' -s 'iterable=""' 'len(list(islice(groupby(iterable, key), 2))) <= 1' 
1000000 loops, best of 5: 233 nsec per loop
% python3.13 -m timeit -s 'from itertools import islice, groupby' -s 'key=None' -s 'iterable="a"' 'len(list(islice(groupby(iterable, key), 2))) <= 1'
1000000 loops, best of 5: 256 nsec per loop
% python3.13 -m timeit -s 'from itertools import islice, groupby' -s 'key=None' -s 'iterable="ab"' 'len(list(islice(groupby(iterable, key), 2))) <= 1'
1000000 loops, best of 5: 289 nsec per loop

% python3.13 -m timeit -s 'from itertools import islice, groupby' -s 'key=None' -s 'iterable=""' 'it=groupby(iterable)' 'try:' ' next(it)' ' next(it)' 'except StopIteration:' ' True' 'else:' ' False'
2000000 loops, best of 5: 150 nsec per loop
% python3.13 -m timeit -s 'from itertools import islice, groupby' -s 'key=None' -s 'iterable="a"' 'it=groupby(iterable)' 'try:' ' next(it)' ' next(it)' 'except StopIteration:' ' True' 'else:' ' False' 
2000000 loops, best of 5: 198 nsec per loop
% python3.13 -m timeit -s 'from itertools import islice, groupby' -s 'key=None' -s 'iterable="ab"' 'it=groupby(iterable)' 'try:' ' next(it)' ' next(it)' 'except StopIteration:' ' True' 'else:' ' False'
2000000 loops, best of 5: 174 nsec per loop
```

Downstream code such as `iequals()` will benefit most because it uses `all_equal()` in a loop.

**Comment by pochmann3** [comment]
That's pretty slow. I added it to [my previous benchmark](https://github.com/python/cpython/issues/92628#issuecomment-1961759730):

```
iterable = ()
True  242 ± 0.2 ns  for_for_False_True_True
True  244 ± 4.9 ns  for_for_False_True
True  264 ± 0.3 ns  not_any_or_not_any
True  266 ± 0.2 ns  not_next_or_not_next
True  267 ± 2.3 ns  not__next_and_next
True  267 ± 5.0 ns  not__any_and_any
True  295 ± 0.2 ns  next__not_next
True  301 ± 0.4 ns  original
True  619 ± 13.1 ns  Raymond

iterable = (1,)
True  355 ± 14.4 ns  for_for_False_True_True
True  359 ± 0.3 ns  for_for_False_True
True  376 ± 0.3 ns  next__not_next
True  385 ± 4.7 ns  not__any_and_any
True  388 ± 2.7 ns  not__next_and_next
True  389 ± 4.1 ns  not_any_or_not_any
True  390 ± 5.9 ns  original
True  404 ± 11.7 ns  not_next_or_not_next
True  738 ± 15.5 ns  Raymond

iterable = (1, 2)
False  458 ± 0.5 ns  for_for_False_True_True
False  459 ± 1.5 ns  for_for_False_True
False  485 ± 1.0 ns  next__not_next
False  494 ± 0.4 ns  original
False  496 ± 0.4 ns  not__next_and_next
False  500 ± 1.0 ns  not_next_or_not_next
False  501 ± 0.8 ns  not_any_or_not_any
False  504 ± 1.3 ns  not__any_and_any
False  595 ± 1.0 ns  Raymond

Python: 3.12.2 (main, Jun 12 2024, 09:13:57) [GCC 14.1.1 20240522]
```

**Comment by pochmann3** [comment]
Oh and I had an [even faster one](https://github.com/python/cpython/issues/92628#issuecomment-1961759730).

**Comment by pochmann3** [comment]
Taking that one step further, saving another 4 ns in all cases:

```python
def all_equal(iterable):
    for _ in groupby(iterable):
        if iterable is None:
            return False
        iterable = None
    return True
```

**Comment by pochmann3** [comment]
Benchmark with just the current more-itertools version and our two alternatives. Could you share it's times from your machine with 3.13?

```
iterable = ()
True  241 ± 0.5 ns  Stefan
True  552 ± 1.0 ns  current
True  601 ± 9.6 ns  Raymond

iterable = (1,)
True  347 ± 0.5 ns  Stefan
True  651 ± 0.7 ns  current
True  722 ± 9.8 ns  Raymond

iterable = (1, 2)
False  435 ± 0.8 ns  Stefan
False  594 ± 0.5 ns  Raymond
False  749 ± 0.8 ns  current

Python: 3.12.2 (main, Jun 12 2024, 09:13:57) [GCC 14.1.1 20240522]
```

<details><summary>Code</summary>

```python
def current(iterable, key=None):
    return len(list(islice(groupby(iterable, key), 2))) <= 1

def Raymond(iterable, key=None):
    iterator = groupby(iterable, key=key)
    try:
        next(iterator)
        next(iterator)
    except StopIteration:
        return True
    return False

def Stefan(iterable, key=None):
    for _ in groupby(iterable):
        if iterable is None:
            return False
        iterable = None
    return True

funcs = [current, Raymond, Stefan]

iterables = (), (1,), (1, 2)

from timeit import timeit
from statistics import mean, stdev
import sys
import random
from itertools import *

for iterable in iterables:
    print(f'{iterable = }')
    times = {f: [] for f in funcs}
    def stats(f):
        ts = [t * 1e9 for t in sorted(times[f])[:10]]
        return f' {mean(ts):3.0f} ± {stdev(ts):3.1f} ns '
    for _ in range(100):
        random.shuffle(funcs)
        for f in funcs:
            t = timeit(lambda: f(iterable), number=1000) / 1000
            times[f].append(t)
    for f in sorted(funcs, key=stats):
        print(f(iterable), stats(f), f.__name__)
    print()

print('Python:', sys.version)
```

[Attempt This Online!](https://ato.pxeger.com/run?1=fVSxjtQwEG2o8hXTJUZh2UADEWmRaBDi6FarKLsZ31kkdmQ7p4tWy4_QXAM9v8Bn8DWMHWeT3HGk2HXGfjPvvZn4-89usDdK3t__6C1_8ebPs281cjj2WqO0ibCoq0ODKXzFofioJLI8Ano02l5LaFAmjTB00DTiiMm1Vn13GNY4lsIrxhi8KyCLIpf-czW0StZPp_cbVmko4J8pC5fWn7R6GCHukXgXOBOW_S-Md0fsLFxZ1X3wG0LJOU9Q90X3uFT7vmoMjgquLPJKPi2AE_cShHxEn81VBIcpCsKAQ8-bj8peUBOk8IjoId-I9_JoaHcXmphOdqeB9T6KpiTuXEL9SbJ0_KVOUQatWrCiRWFBtJ3SNryNO8aSXcYKqhJ2W6xkSvEab6MQMoOZlrqStWpHrCtslWou0OdUjryajZCXtRnd6LSgSeTxaaH8HIfuEy2n4cRz2O2969yl8B6c_RHXLcfYJHzhvfUOUXnI8K3HWYczRAnrxKfd8T3b5dl2v384FzyGk5OcWMPy15stP8PvX3Dy-kMso5g0EK-HgZy4xiTbbhdMRnc25qbnvMHEM59Hd61oPR6WJIx9SZqqPdRVDnyesxRk3x5QF1Ruy-AluP81PqjcVF2H9DVaFq1KBjN85XHAvY8L7qE1y6KT1SnwTVnKqsWyZIs-0niNi_iTv3jyOHWzsrlFbegbZOM1FG6j6Vb6Cw)

</details>

**Comment by rhettinger** [comment]
That looks a little gross to me.  I would rather have something slower that makes fundamental logic clear.  Aim for the fastest variant of something that a humans would like to read and write.  We don't want the result to be like assembly language that has to be deciphered.  The fundamental logic needs to be clear.

Aspire for something readable and that will likely remain pretty fast as the interpreter goes through changes. We don't want to chase a particular version/build combination into a local minimum.  Also, think in terms of type flow -- reassigning `iterable` to `None` isn't great.

Personally, I like the `try/next/next` version because it expresses exactly what we want the algorithm to do, advance the iterator up to two times. If both steps succeed, then we have too many groups to be all equal.  Whatever you come up with, the code needs to express that understanding.

**Comment by pochmann3** [comment]
What about the other ones? I like the `for_for_False_True` one:

```python
def all_equal(iterable, key=None):
    groups = groupby(iterable, key)
    for first in groups:
        for second in groups:
            return False
    return True
```

And I'd still appreciate it if you could tell the results of my script on your machine with 3.13. I'm surprised your version was faster for you than the current implementation when there's exactly one group, as it is **slower** in my testing (making it **not** an optimization) and I see nothing in *"What’s New In Python 3.13"* about catching exceptions suddenly not being expensive anymore.

**Comment by pochmann3** [comment]
And I just tested with 3.13 as well, on GitHub codespaces, built with `./configure --enable-optimizations` and `make -s -j`. Again your version was **slower** for zero and one groups than the current implementation:

```
iterable = ()
True  134 Â± 0.3 ns  Stefan
True  311 Â± 0.5 ns  current
True  351 Â± 0.6 ns  Raymond

iterable = (1,)
True  202 Â± 0.1 ns  Stefan
True  356 Â± 0.6 ns  current
True  437 Â± 0.7 ns  Raymond

iterable = (1, 2)
False  254 Â± 0.4 ns  Stefan
False  333 Â± 0.8 ns  Raymond
False  397 Â± 0.9 ns  current

Python: 3.13.0rc1+ (heads/3.13:009f9efe658, Aug 15 2024, 14:30:32) [Clang 18.1.6 (Fedora 18.1.6-3.fc40)]
```

**Comment by rhettinger** [comment]
The `for/for` version is much better. It relies only on core python for-loops which is faster and more stable than relying on `try/except` performance. The code is still a little weird but not overly so.  

I would change the variable name from `groups` to `iterator`. To understand the code, it is critical to understand that each for-loop is reusing the same iterator and not getting a fresh one (if for example `groups` was a list instead of an iterator, the code would be incorrect).

P.S. Historically, your posted timings tend to be much slower than mine. Is there possibly something wrong with your build (perhaps a debug or non-pgo build) or environment (sandboxes or in a VM)?  I'm running on a four year-old 2020 MacBook Air. Also Python3.13 is mostly slower than Python3.12.

**Comment by pochmann3** [comment]
Hmm, on the same machine I get **faster** times with yours if I measure your way with the `-m timeit` command lines:

```
1000000 loops, best of 5: 269 nsec per loop
1000000 loops, best of 5: 309 nsec per loop
1000000 loops, best of 5: 356 nsec per loop

2000000 loops, best of 5: 196 nsec per loop
1000000 loops, best of 5: 261 nsec per loop
1000000 loops, best of 5: 209 nsec per loop
```

So there's something fishy going on. I don't see what. But I trust the normal code testing more than that command line testing.
