### ISSUE TITLE
One more nit on all_equal()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#902]
I missed something during the code review.  There is an extra unnecessary `next` call in the first for-loop.  This is easily solved by adding another `return True`.

```
def all_equal(iterable, key=None):
    iterator = groupby(iterable, key)
    for first in iterator:
        for second in iterator:
            return False
        return True                          # <== This was missed
    return True
```

For example, `all_equal('a')` calls the `groupby.__next__` three times.

This is can be made visible by replacing `groupby` with `verbose_groupby`:

```
class verbose_groupby(itertools.groupby):

    def __next__(self):
        print('N')
        return super().__next__()
```

**Comment by pochmann3** [comment]
Yeah that's my `for_for_False_True_True`. I preferred `for_for_False_True`, given how small the speed difference was. (I'll get back to the other topics, just been busy.)
