### ISSUE TITLE
Undefined symbol `UnionType` in more_itertools/more.pyi.

### ISSUE THREAD

**Issue by eberts-google** [more-itertools/more-itertools#904]
`UnionType` is defined in [types](https://docs.python.org/3/library/types.html), but the dependency was removed, which now leads to an undefined symbol.

Already flagged by a user [here](https://github.com/more-itertools/more-itertools/commit/12b6e23038f5f7346a6be881aa174b8911cca730?diff=split&w=0), but not fixed yet.

**Comment by bbayles** [comment]
Thanks, I understand the issue now - I was confused because CI tests were passing, but the issue is CPython version-dependent.
