### ISSUE TITLE
Make polynomial_from_roots() non-recursive

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#912]
This edit breaks up the chain of recursive calls by fully consuming the convolution on each iteration.

```
def polynomial_from_roots(roots):
    poly = [1]
    for factor in zip(repeat(1), map(operator.neg, roots)):
        poly = list(convolve(poly, factor))
    return poly
```

The new non-recursive version can handle a large number of roots without encountering `RecursionError: maximum recursion depth exceeded`.  For example, the following test does not currently succeed:

```
assert sum(polynomial_from_roots([-1] * 5_000)) == 2 ** 5000
```

**Comment by pochmann3** [comment]
Do you then still prefer building the factors like that? Instead of:

```py
def polynomial_from_roots(roots):
    poly = [1]
    for root in roots:
        poly = list(convolve(poly, (1, -root)))
    return poly
```

**Comment by rhettinger** [comment]
I like yours better.

**Comment by bbayles** [comment]
@pochmann3, thanks for the implementation. If you'll make a PR for this, I'll merge it in.

**Comment by rhettinger** [comment]
Also, please add a stronger test:

```
n = 5_000
assert polynomial_from_roots([-1] * n) == [math.comb(n, k) for k in range(n+1)]
```

**Comment by pochmann3** [comment]
That test takes me (not on GitHub) about 20 seconds for the `polynomial_from_roots` call and 5 seconds for the list comprehension. Is that acceptable? With `n = 1_100` it's about 0.6 and 0.1 seconds (and the current version fails that already).

**Comment by bbayles** [comment]
Could you do 1000? Less than a second is okay.

**Comment by rhettinger** [comment]
How about 1,500.  We need *n* large enough to where the current recursive version fails.   The point of the test is to show that we are not going to encounter a `RecursionError`.

**Comment by JamesParrott** [comment]
These aren't simple, but can the test be run in CO only, using `pytest.mark.skipif`.  Alternatively, can the recursion limit be lowered as a one off, just for that test?

**Comment by rhettinger** [comment]
On my machine (2021 M1 Max run Py3.13rc2), the test takes 0.387 seconds for n=1500).  That is fast enough.
