### ISSUE TITLE
is_sorted() should only depend on less-than comparisons

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#916]
The `sorted()` function is [documented to only use less-than comparisons](https://docs.python.org/3/library/functions.html#sorted).  The `is_sorted()` predicate should do the same:

```
def is_sorted(iterable, key=None, reverse=False, strict=False):
    it = iterable if (key is None) else map(key, iterable)
    a, b = tee(it)
    next(b, None)
    if reverse:
        b, a = a, b
    return all(map(lt, a, b)) if strict else not any(map(lt, b, a))
```

Note:  This breaks some of the tests with *NaN* values when `strict=True`.  However, I think all of the *NaN* tests are dubious.

For example, `math.nan <= 0 <= math.nan <= 0` is `False` but `is_sorted(['nan', 0, 'nan', 0], key=float)` currently returns `True`.

In general, it doesn't make sense to claim a dataset containing a *NaN* is sorted.  When `data = [8.0, 4.0, 0.0, math.nan, 6.0, 2.0]`, the call `is_sorted(sorted(data))` nonsensically returns `False`.

**Comment by pochmann3** [comment]
> When `data = [8.0, 4.0, 0.0, math.nan, 6.0, 2.0]`, the call `is_sorted(sorted(data))` nonsensically returns `False`.

With what implementation? I get `True` both with the current more-itertools implementation and with yours. (I'm just not using Python 3.13 yet, did `sorted` change here?)

**Comment by rhettinger** [comment]
```
% python3.13
Python 3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import more_itertools
>>> more_itertools.__version__
'10.5.0'
>>> from more_itertools import is_sorted
>>> import math
>>> data = [8.0, 4.0, 0.0, math.nan, 6.0, 2.0]
>>> is_sorted(sorted(data))
False
```

**Comment by pochmann3** [comment]
Interesting. What does `sorted([8.0, 4.0, 0.0, math.nan, 6.0, 2.0])` give you? 

> Are you in doubt that _NaN_ values wreck our ability to meaningfully reason about ordering?

Not at all, I even said something like that myself [in the previous issue](https://github.com/more-itertools/more-itertools/issues/876#issuecomment-2215418616), calling such cases neither sorted nor sortable.

**Comment by JamesParrott** [comment]
How would an implementation satisfy `is_sorted([1,1], strict=False) is True` whilst only relying on `.__lt__` ?

Just my two pence.  NaNs are an edge case.  If they're using NaNs (or haven't cleaned their data from them) then onus is on the user to define a key function to handle them however they so wish.

> In general, it doesn't make sense to claim a dataset containing a NaN is sorted. 

Mathematically I agree entirely.  Pythonically, `sort` will happily plough on though.  is_sorted` could provide a useful check for a false postive in Python.

**Comment by pochmann3** [comment]
> How would a correct implementation satisfy `is_sorted([1,1], strict=False) is True` whilst only relying on `operator.lt` ?

Not sure what you mean, as our implementations already do that.

**Comment by JamesParrott** [comment]
> 

Oh right.  Brilliant.  I didn't realise an implementation had already  been created, and the one below didn't occur to me.

```
return all(map(lt, a, b)) if strict else not any(map(lt, b, a))
```
Very cunning!
