### ISSUE TITLE
Add is_prime()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#920]
Consider adding an `is_prime()` function. It is not an iterator but does fit nicely with the other math tools.

Here's some code (tested) that gets the job done and that has fast paths for smaller inputs:

```
from random import randrange
from functools import lru_cache

# https://en.wikipedia.org/wiki/Miller–Rabin_primality_test#Testing_against_small_sets_of_bases
perfect_tests = [
    (2047, (2,)),
    (9080191, (31, 73)),
    (4_759_123_141, (2, 7, 61)),
    (1122004669633, (2, 13, 23, 1662803)),
    (2152302898747, (2, 3, 5, 7, 11)),
    (3474749660383, (2, 3, 5, 7, 11, 13)),
    (341550071728321, (2, 3, 5, 7, 11, 13, 17)),
    (3825123056546413051, (2, 3, 5, 7, 11, 13, 17, 19, 23)),
    (318665857834031151167461, (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37)),
    (3317044064679887385961981, (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41)),
]

@lru_cache
def shift_to_odd(n):
    'Return s, d such that 2**s * d == n'
    s = ((n - 1) ^ n).bit_length() - 1
    d = n >> s
    assert (1 << s) * d == n and d & 1
    return s, d

def strong_probable_prime(n, base):
    assert n > 2 and n & 1
    s, d = shift_to_odd(n - 1)
    x = pow(base, d, n)
    if x == 1 or x == n - 1:
        return True
    for _ in range(s - 1):
        x = x * x % n
        if x == n - 1:
            return True
    return False

def is_prime(n):
    if n < 17:
        return n in {2, 3, 5, 7, 11, 13}
    if not (n&1 and n%3 and n%5 and n%7 and n%11 and n%13):
        return False
    for limit, bases in perfect_tests:
        if n < limit:
            break
    else:
        bases = [randrange(2, n - 1) for i in range(32)]
    return all(strong_probable_prime(n, base) for base in bases)
```

**Comment by JamesParrott** [comment]
This is great.  k=30 gives a false positive with probability 10^-18, for >= 81 bit numbers.  Is it fair to assume that anyone remotely likely to find 30 false witnesses from randomly chosen bases, will be using other tools or will have read the source code?

**Comment by bbayles** [comment]
I love this stuff (I have a function like this in my private Project Euler package), but I think I'm -0 for this in `more_itertools`. (though if Raymond adds it to `itertools` as a recipe, I'll have no choice - ha!)

I think `nth_prime` would probably fit better (we have that for permutations, combinations, products)?

**Comment by rhettinger** [comment]
I was uncertain whether to propose this for `more-itertools`. On the one hand, `is_prime` is not an iterator. On the other hand, it would be commonly used and isn't something that people easily build for themselves. Since there was no other place with a natural fit, I decided to go forward with the proposal.

**Comment by JamesParrott** [comment]
I got curious about other possible homes for this code.  Sagemath uses PARI, a C Library.  Sympy already uses MillerRabin for 64 bit numbers (after testing for low hanging fruit), but differs for larger numbers, preferring a strong BPSW test to 30 random bases/witnesses.

https://github.com/sympy/sympy/blob/91ab0d56601537db30574666941424d4c24f3083/sympy/ntheory/primetest.py#L704
https://en.wikipedia.org/wiki/Baillie%E2%80%93PSW_primality_test

**Comment by bbayles** [comment]
[GMPY2](https://gmpy2.readthedocs.io/en/latest/mpz.html#gmpy2.mpz.is_prime) is the one I use where possible, and it does Miller-Rabin

**Comment by rhettinger** [comment]
@JamesParrott I bumped up *k* to 32. If someone needs more certainty than `1E-19`, the test can be run more than once, `is_prime(n) and is_prime(n)`.  That would give the same assurance as an `md5` checksum match.

@bbayles For most folks `GMPY2` is obscure. Also, it presents installation challenges (right now, I can't get it to build for `CPython 3.14a` or `pypy3`).  There are some nice advantages to `more-itertools` being written in pure python.

**Comment by JamesParrott** [comment]
Great.  I had hash collisions in mind too as a reference for extremely small probabilities.

**Comment by rhettinger** [comment]
> though if Raymond adds it to itertools as a recipe, I'll have no choice - ha!

I do expect add an `is_prime()` itertools recipe but only to demonstrate an application for `sieve()`. Don't let that force your hand; it would be reasonable to omit the function from `more-itertools`.

> I think nth_prime would probably fit better (we have that for permutations, combinations, products)?

Here's an implementation:

```
from more_itertools import sieve, nth
from math import log, ceil

def nth_prime_ub(n: int) -> float:
    "Upper bound for the nth prime (counting from 1)."
    # https://en.wikipedia.org/wiki/Prime-counting_function#Inequalities
    return n * log(n * log(n)) if n >= 6 else 11.1

def nth_prime(n):
    "Return the nth prime (counting from 0)."
    if n < 0:
        raise ValueError
    limit = ceil(nth_prime_ub(n + 1))
    return nth(sieve(limit), n)
```

And some tests:

```
for n, p in enumerate(sieve(10 ** 8)):
    assert nth_prime_ub(n+1) > p  

for n, p in enumerate(sieve(10 ** 5)):
    assert nth_prime(n) == p
```

**Comment by rhettinger** [comment]
> I think nth_prime would probably fit better (we have that for permutations, combinations, products)?

Here's another possibility that would fit in with the current offerings:

```
from random import randrange

def random_prime(n):
    "Random prime less than n. Equivalent to random.choice(list(sieve(n)))."
    if n <= 2:
        raise ValueError
    while True:
        p = randrange(n)
        if is_prime(p):
            return p
```

**Comment by bbayles** [comment]
OK, I've come around - `is_prime` and `nth_prime` are in https://github.com/more-itertools/more-itertools/pull/922. I'll take `next_prime` if somebody's got a nice implementation, also.

I had use for a `next_permutation` and `next_product` recently - when working on the little puzzle described in [this article](https://32bits.substack.com/p/under-the-microscope-tony-hawks-pro), so if somebody wants to take on those I'm open to them*.

* I'm still looking for an input sequence that hashes to `(0xEFCC5A6F, 0xD62EC6D8)` if you want to get nerd sniped.

**Comment by bbayles** [comment]
Way to go! I came up with DXDXDXDXDXDXDXDXS too.

**Comment by jbosboom** [comment]
@bbayles [Here's the code](https://gist.github.com/jbosboom/73928ecf1c935b678fd4193ce0de6a0d#file-thps2-codes-cpp), pretty straightforward under the C++ verbosity.  The other file in the gist lists strings matching the hashes in your Python code and the hash you mentioned here, 100 for each single hash and 1-3 for the double hashes.

It was fun, though I am disappointed I didn't finish it in time to be useful.

**Comment by bbayles** [comment]
@jbosboom - really cool! I wound up using brute force, but with a restricted alphabet. That is "assume only 1 distinct button, check as many repetitions as you have time for;" then "assume 2 distinct buttons; check as many repetitions as you have time for," etc.

I'm writing another article about the game this hash came from (Tony Hawk's Pro Skater 3) - mind if I link to your code?

**Comment by jbosboom** [comment]
@bbayles Go ahead; that's why I published it.
