### ISSUE TITLE
Consider making factor() more powerful

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#929]
The current `factor()` from the itertools recipes uses trial division. That is reasonably effective up to about `10 ** 15` though the underlying `sieve()` eats memory like crazy.  

There are [other algorithms](https://stackoverflow.com/a/2274520/424499) that handle much larger inputs and use very little memory.  Here is a first draft using [Pollard's Rho Algorithm](https://en.wikipedia.org/wiki/Pollard%27s_rho_algorithm). It doesn't begin to bog down until `10 ** 30`.  

Further improvements are possible (listed in referenced article). I just wanted to get a sketch up and running to see if you would be interested in something like this.

**Main code**:

```
from more_itertools import factor as factor_small, is_prime
from math import gcd

def pollard(n):
    'Return a non-trivial factor of a composite n.'
    for b in range(1, n - 2):
        x = y = 2
        d = 1
        while d == 1:
            x = (x * x + b) % n
            y = (y * y + b) % n
            y = (y * y + b) % n
            d = gcd(x - y, n)
        if d != n:
            return d
    raise ValueError(f'prime or under 5')

def factor(n):
    todo = [n] if n > 1 else []
    while todo:
        n = todo.pop()
        if is_prime(n):
            yield n
        elif n < 1000:
            yield from factor_small(n)
        else:
            fact = pollard(n)
            todo += (n // fact, fact)
```

**Demonstration and tests**:

```
from collections import Counter
from random import seed, randrange
from math import prod

for n in range(100_000):
    assert Counter(factor(n)) == Counter(factor_small(n))

seed(8675309)
for i in range(20):
    n = randrange(10 ** 25)
    factors = list(factor(n))
    assert prod(factors) == n and all(map(is_prime, factors))
    print(f'{n:,}: {factors}')
```

**Output**:

```
9,869,602,325,083,211,630,749,747: [4136608051, 2385916722928897]
4,573,804,804,328,949,139,154,601: [3, 3, 7027, 36997, 1954783451491231]
3,985,828,998,088,783,078,306,188: [3, 3, 2, 2, 4999, 2411, 9186198265711447]
1,213,036,987,311,438,672,884,787: [3, 3, 11, 37, 13, 61, 15227, 27425186502559]
320,097,820,909,839,163,017,286: [2, 2063, 80143757, 968018810273]
2,056,565,487,725,687,980,272,202: [2, 2131, 266089, 1813435764650639]
6,491,522,496,841,641,382,228,938: [3, 7, 3, 2, 71329, 722287145707965947]
2,603,976,484,230,244,518,758,553: [3, 107, 1756663807, 4617887749799]
6,500,694,336,153,090,155,592,949: [6500694336153090155592949]
3,903,368,629,694,986,387,124,384: [2, 2, 2, 2, 2, 13, 19553, 479880205980464633]
7,630,023,212,177,997,234,899,609: [814519661, 9367512630463069]
4,284,851,646,165,198,181,579,572: [3, 2, 2, 11, 3049, 27308417, 389859308837]
2,076,514,068,333,688,913,860,647: [3, 29, 10137187, 2354497139782363]
6,125,479,605,228,782,433,229,343: [7, 109473107, 7993456466277907]
7,147,764,838,882,517,029,314,012: [3, 3, 3, 2, 2, 43, 103, 30013, 20873, 23853193909]
3,336,096,809,997,208,438,930,133: [7, 11, 3467, 88499, 424913, 332319401]
5,499,158,913,066,851,896,481,729: [83, 7537, 8790623147599316299]
5,988,544,417,700,083,510,486,399: [5988544417700083510486399]
1,647,403,876,764,101,672,307,088: [2, 2, 2, 2, 19, 23, 109471, 13571009, 158594251]
1,755,395,861,949,707,706,066,732: [3, 2, 2, 26463804541, 5527662822221]
```

**Open question**: 

Would it be worth giving up laziness in order to sort the output?

**Comment by bbayles** [comment]
Hmm, I'm conflicted on this. It's better to have a more efficient algorithm, but this changes the order of output as well as the laziness property. I could add it as an additional function, but then why have the original aside from the fact that it was there first?

Perhaps I should explain that the existing recipe uses trial division and link to a well-regarded [alternative implementation](https://docs.sympy.org/latest/modules/ntheory.html#sympy.ntheory.factor_.pollard_rho)?

**Comment by rhettinger** [comment]
> but this changes the order of output as well as the laziness property. 

Small clarification:  It either loses output ordering or laziness _but not both_.  The above code is lazy but doesn't sort the output. Personally, I value laziness more than ordering. The latter property was never explicitly promised and is easily added after the fact with `sorted(factor(n))`.

> I could add it as an additional function

That would solve the 100% compatibility problem. However, given a choice between `factor()` and `much_better_factor()`, I don't think I would ever use the first one. Unlike most itertools, the current `factor()` code is unexpectedly memory intensive. Eliminating the memory requirement is a huge win.  Also the speed-up can be enormous — I get a 35x improvement when factoring a 13-digit semiprime like `1637927 * 4514317`.  And when you consider the vastly larger input range, the second function would always win.

> Hmm, I'm conflicted on this.

I'm glad you're in the driver seat on this one. You have a great track record for making the right decisions when trade-offs need to be made. As always, I 100% support whatever you decide. You've been an excellent steward for this project.
